// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: sms.proto

package server

import (
	"context"

	"github.com/feihua/zero-admin/rpc/sms/internal/logic/drawparticipationservice"
	"github.com/feihua/zero-admin/rpc/sms/internal/svc"
	"github.com/feihua/zero-admin/rpc/sms/smsclient"
)

type DrawParticipationServiceServer struct {
	svcCtx *svc.ServiceContext
	smsclient.UnimplementedDrawParticipationServiceServer
}

func NewDrawParticipationServiceServer(svcCtx *svc.ServiceContext) *DrawParticipationServiceServer {
	return &DrawParticipationServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *DrawParticipationServiceServer) QueryDrawActivityLanding(ctx context.Context, in *smsclient.QueryDrawActivityLandingReq) (*smsclient.QueryDrawActivityLandingResp, error) {
	l := drawparticipationservicelogic.NewQueryDrawActivityLandingLogic(ctx, s.svcCtx)
	return l.QueryDrawActivityLanding(in)
}

func (s *DrawParticipationServiceServer) PreviewDrawEligibility(ctx context.Context, in *smsclient.PreviewDrawEligibilityReq) (*smsclient.PreviewDrawEligibilityResp, error) {
	l := drawparticipationservicelogic.NewPreviewDrawEligibilityLogic(ctx, s.svcCtx)
	return l.PreviewDrawEligibility(in)
}

func (s *DrawParticipationServiceServer) ParticipateDraw(ctx context.Context, in *smsclient.ParticipateDrawReq) (*smsclient.ParticipateDrawResp, error) {
	l := drawparticipationservicelogic.NewParticipateDrawLogic(ctx, s.svcCtx)
	return l.ParticipateDraw(in)
}

func (s *DrawParticipationServiceServer) QueryMemberDrawRecordList(ctx context.Context, in *smsclient.QueryMemberDrawRecordListReq) (*smsclient.QueryMemberDrawRecordListResp, error) {
	l := drawparticipationservicelogic.NewQueryMemberDrawRecordListLogic(ctx, s.svcCtx)
	return l.QueryMemberDrawRecordList(in)
}
