// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: sys.proto

package server

import (
	"context"

	"github.com/feihua/zero-admin/rpc/sys/internal/logic/menutemplateservice"
	"github.com/feihua/zero-admin/rpc/sys/internal/svc"
	"github.com/feihua/zero-admin/rpc/sys/sysclient"
)

type MenuTemplateServiceServer struct {
	svcCtx *svc.ServiceContext
	sysclient.UnimplementedMenuTemplateServiceServer
}

func NewMenuTemplateServiceServer(svcCtx *svc.ServiceContext) *MenuTemplateServiceServer {
	return &MenuTemplateServiceServer{
		svcCtx: svcCtx,
	}
}

// 添加菜单模板
func (s *MenuTemplateServiceServer) AddMenuTemplate(ctx context.Context, in *sysclient.AddMenuTemplateReq) (*sysclient.AddMenuTemplateResp, error) {
	l := menutemplateservicelogic.NewAddMenuTemplateLogic(ctx, s.svcCtx)
	return l.AddMenuTemplate(in)
}

// 删除菜单模板
func (s *MenuTemplateServiceServer) DeleteMenuTemplate(ctx context.Context, in *sysclient.DeleteMenuTemplateReq) (*sysclient.DeleteMenuTemplateResp, error) {
	l := menutemplateservicelogic.NewDeleteMenuTemplateLogic(ctx, s.svcCtx)
	return l.DeleteMenuTemplate(in)
}

// 更新菜单模板
func (s *MenuTemplateServiceServer) UpdateMenuTemplate(ctx context.Context, in *sysclient.UpdateMenuTemplateReq) (*sysclient.UpdateMenuTemplateResp, error) {
	l := menutemplateservicelogic.NewUpdateMenuTemplateLogic(ctx, s.svcCtx)
	return l.UpdateMenuTemplate(in)
}

// 查询菜单模板详情
func (s *MenuTemplateServiceServer) QueryMenuTemplateDetail(ctx context.Context, in *sysclient.QueryMenuTemplateDetailReq) (*sysclient.QueryMenuTemplateDetailResp, error) {
	l := menutemplateservicelogic.NewQueryMenuTemplateDetailLogic(ctx, s.svcCtx)
	return l.QueryMenuTemplateDetail(in)
}

// 查询菜单模板列表
func (s *MenuTemplateServiceServer) QueryMenuTemplateList(ctx context.Context, in *sysclient.QueryMenuTemplateListReq) (*sysclient.QueryMenuTemplateListResp, error) {
	l := menutemplateservicelogic.NewQueryMenuTemplateListLogic(ctx, s.svcCtx)
	return l.QueryMenuTemplateList(in)
}

// 根据作用域查询可用菜单ID
func (s *MenuTemplateServiceServer) QueryMenuIdsByScope(ctx context.Context, in *sysclient.QueryMenuTemplateByScope) (*sysclient.QueryMenuTemplateByScopeResp, error) {
	l := menutemplateservicelogic.NewQueryMenuIdsByScopeLogic(ctx, s.svcCtx)
	return l.QueryMenuIdsByScope(in)
}
