package productattributegroupservicelogic
import (
	"context"; "errors"
	"github.com/feihua/zero-admin/pkg/pointerprocess"; pkgscope "github.com/feihua/zero-admin/pkg/scope"; "github.com/feihua/zero-admin/pkg/time_util"
	logiccommon "github.com/feihua/zero-admin/rpc/pms/internal/logic/common"; "github.com/feihua/zero-admin/rpc/pms/internal/svc"; "github.com/feihua/zero-admin/rpc/pms/pmsclient"; "github.com/zeromicro/go-zero/core/logc"; "github.com/zeromicro/go-zero/core/logx"; "gorm.io/gorm")

type QueryProductAttributeGroupDetailLogic struct { ctx context.Context; svcCtx *svc.ServiceContext; logx.Logger }
func NewQueryProductAttributeGroupDetailLogic(ctx context.Context, svcCtx *svc.ServiceContext) *QueryProductAttributeGroupDetailLogic { return &QueryProductAttributeGroupDetailLogic{ctx:ctx, svcCtx:svcCtx, Logger:logx.WithContext(ctx)} }
func (l *QueryProductAttributeGroupDetailLogic) QueryProductAttributeGroupDetail(in *pmsclient.QueryProductAttributeGroupDetailReq) (*pmsclient.QueryProductAttributeGroupDetailResp, error) { current, err := logiccommon.NormalizeProtoScope(in.Scope); if err != nil { return nil, err }; var item logiccommon.ProductAttributeGroupRow; scopeWhere, scopeArgs := pkgscope.ScopeFilterSQL("", current); err = l.svcCtx.DB.WithContext(l.ctx).Table("pms_product_attribute_group").Where("id = ? AND is_deleted = 0", in.Id).Where(scopeWhere, scopeArgs...).Take(&item).Error; switch { case errors.Is(err, gorm.ErrRecordNotFound): logc.Errorf(l.ctx, "商品属性分组不存在, 请求参数：%+v, 异常信息: %s", in, err.Error()); return nil, errors.New("商品属性分组不存在"); case err != nil: logc.Errorf(l.ctx, "查询商品属性分组异常, 请求参数：%+v, 异常信息: %s", in, err.Error()); return nil, errors.New("查询商品属性分组异常") }; return &pmsclient.QueryProductAttributeGroupDetailResp{Id:item.ID,CategoryId:item.CategoryID,Name:item.Name,Sort:item.Sort,Status:item.Status,CreateBy:item.CreateBy,CreateTime:time_util.TimeToStr(item.CreateTime),UpdateBy:pointerprocess.DefaltData(item.UpdateBy).(int64),UpdateTime:time_util.TimeToString(item.UpdateTime),IsDeleted:item.IsDeleted,ScopeType:current.ScopeType,PlatformId:item.PlatformID,TenantId:item.TenantID,MerchantId:item.MerchantID}, nil }
