// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: sys.proto

package server

import (
	"context"

	"github.com/feihua/zero-admin/rpc/sys/internal/logic/tenantservice"
	"github.com/feihua/zero-admin/rpc/sys/internal/svc"
	"github.com/feihua/zero-admin/rpc/sys/sysclient"
)

type TenantServiceServer struct {
	svcCtx *svc.ServiceContext
	sysclient.UnimplementedTenantServiceServer
}

func NewTenantServiceServer(svcCtx *svc.ServiceContext) *TenantServiceServer {
	return &TenantServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *TenantServiceServer) CreateTenant(ctx context.Context, in *sysclient.CreateTenantReq) (*sysclient.CreateTenantResp, error) {
	l := tenantservicelogic.NewCreateTenantLogic(ctx, s.svcCtx)
	return l.CreateTenant(in)
}

func (s *TenantServiceServer) QueryTenantDetail(ctx context.Context, in *sysclient.QueryTenantDetailReq) (*sysclient.QueryTenantDetailResp, error) {
	l := tenantservicelogic.NewQueryTenantDetailLogic(ctx, s.svcCtx)
	return l.QueryTenantDetail(in)
}

func (s *TenantServiceServer) QueryTenantList(ctx context.Context, in *sysclient.QueryTenantListReq) (*sysclient.QueryTenantListResp, error) {
	l := tenantservicelogic.NewQueryTenantListLogic(ctx, s.svcCtx)
	return l.QueryTenantList(in)
}

func (s *TenantServiceServer) EnableTenant(ctx context.Context, in *sysclient.ChangeTenantStatusReq) (*sysclient.ChangeTenantStatusResp, error) {
	l := tenantservicelogic.NewEnableTenantLogic(ctx, s.svcCtx)
	return l.EnableTenant(in)
}

func (s *TenantServiceServer) DisableTenant(ctx context.Context, in *sysclient.ChangeTenantStatusReq) (*sysclient.ChangeTenantStatusResp, error) {
	l := tenantservicelogic.NewDisableTenantLogic(ctx, s.svcCtx)
	return l.DisableTenant(in)
}

func (s *TenantServiceServer) ArchiveTenant(ctx context.Context, in *sysclient.ChangeTenantStatusReq) (*sysclient.ChangeTenantStatusResp, error) {
	l := tenantservicelogic.NewArchiveTenantLogic(ctx, s.svcCtx)
	return l.ArchiveTenant(in)
}
