// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: sms.proto

package operatedashboardservice

import (
	"context"

	"github.com/feihua/zero-admin/rpc/sms/smsclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddCouponRecordReq                      = smsclient.AddCouponRecordReq
	AddCouponRecordResp                     = smsclient.AddCouponRecordResp
	AddCouponReq                            = smsclient.AddCouponReq
	AddCouponResp                           = smsclient.AddCouponResp
	AddCouponScopeData                      = smsclient.AddCouponScopeData
	AddCouponScopeReq                       = smsclient.AddCouponScopeReq
	AddCouponScopeResp                      = smsclient.AddCouponScopeResp
	AddCouponTypeReq                        = smsclient.AddCouponTypeReq
	AddCouponTypeResp                       = smsclient.AddCouponTypeResp
	AddDrawActivityReq                      = smsclient.AddDrawActivityReq
	AddDrawActivityResp                     = smsclient.AddDrawActivityResp
	AddHomeAdvertiseReq                     = smsclient.AddHomeAdvertiseReq
	AddHomeAdvertiseResp                    = smsclient.AddHomeAdvertiseResp
	AddSeckillActivityReq                   = smsclient.AddSeckillActivityReq
	AddSeckillActivityResp                  = smsclient.AddSeckillActivityResp
	AddSeckillProductData                   = smsclient.AddSeckillProductData
	AddSeckillProductReq                    = smsclient.AddSeckillProductReq
	AddSeckillProductResp                   = smsclient.AddSeckillProductResp
	AddSeckillReservationReq                = smsclient.AddSeckillReservationReq
	AddSeckillReservationResp               = smsclient.AddSeckillReservationResp
	AddSeckillSessionReq                    = smsclient.AddSeckillSessionReq
	AddSeckillSessionResp                   = smsclient.AddSeckillSessionResp
	CouponListData                          = smsclient.CouponListData
	CouponRecordListData                    = smsclient.CouponRecordListData
	CouponScopeData                         = smsclient.CouponScopeData
	CouponScopeListData                     = smsclient.CouponScopeListData
	CouponTypeListData                      = smsclient.CouponTypeListData
	DeleteCouponRecordReq                   = smsclient.DeleteCouponRecordReq
	DeleteCouponRecordResp                  = smsclient.DeleteCouponRecordResp
	DeleteCouponReq                         = smsclient.DeleteCouponReq
	DeleteCouponResp                        = smsclient.DeleteCouponResp
	DeleteCouponScopeReq                    = smsclient.DeleteCouponScopeReq
	DeleteCouponScopeResp                   = smsclient.DeleteCouponScopeResp
	DeleteCouponTypeReq                     = smsclient.DeleteCouponTypeReq
	DeleteCouponTypeResp                    = smsclient.DeleteCouponTypeResp
	DeleteDrawActivityReq                   = smsclient.DeleteDrawActivityReq
	DeleteDrawActivityResp                  = smsclient.DeleteDrawActivityResp
	DeleteHomeAdvertiseReq                  = smsclient.DeleteHomeAdvertiseReq
	DeleteHomeAdvertiseResp                 = smsclient.DeleteHomeAdvertiseResp
	DeleteSeckillActivityReq                = smsclient.DeleteSeckillActivityReq
	DeleteSeckillActivityResp               = smsclient.DeleteSeckillActivityResp
	DeleteSeckillProductReq                 = smsclient.DeleteSeckillProductReq
	DeleteSeckillProductResp                = smsclient.DeleteSeckillProductResp
	DeleteSeckillReservationReq             = smsclient.DeleteSeckillReservationReq
	DeleteSeckillReservationResp            = smsclient.DeleteSeckillReservationResp
	DeleteSeckillSessionReq                 = smsclient.DeleteSeckillSessionReq
	DeleteSeckillSessionResp                = smsclient.DeleteSeckillSessionResp
	DrawActivityAuditRecord                 = smsclient.DrawActivityAuditRecord
	DrawActivityListData                    = smsclient.DrawActivityListData
	DrawCardTemplateData                    = smsclient.DrawCardTemplateData
	DrawHomeEntryConfig                     = smsclient.DrawHomeEntryConfig
	DrawLandingCardPreview                  = smsclient.DrawLandingCardPreview
	DrawLandingPoolPreview                  = smsclient.DrawLandingPoolPreview
	DrawLandingRecentWin                    = smsclient.DrawLandingRecentWin
	DrawMemberRecordData                    = smsclient.DrawMemberRecordData
	DrawPoolData                            = smsclient.DrawPoolData
	DrawPoolTemplateData                    = smsclient.DrawPoolTemplateData
	DrawReadinessItem                       = smsclient.DrawReadinessItem
	GovernanceScope                         = smsclient.GovernanceScope
	HandleExpirationCouponReq               = smsclient.HandleExpirationCouponReq
	HandleExpirationCouponResp              = smsclient.HandleExpirationCouponResp
	HomeAdvertiseListData                   = smsclient.HomeAdvertiseListData
	OperateCouponRedeemBucketPoint          = smsclient.OperateCouponRedeemBucketPoint
	OperateFunnelActivityOption             = smsclient.OperateFunnelActivityOption
	OperateTrafficBucketPoint               = smsclient.OperateTrafficBucketPoint
	ParticipateDrawReq                      = smsclient.ParticipateDrawReq
	ParticipateDrawResp                     = smsclient.ParticipateDrawResp
	PreviewDrawActivityPublishReadinessReq  = smsclient.PreviewDrawActivityPublishReadinessReq
	PreviewDrawActivityPublishReadinessResp = smsclient.PreviewDrawActivityPublishReadinessResp
	PreviewDrawEligibilityReq               = smsclient.PreviewDrawEligibilityReq
	PreviewDrawEligibilityResp              = smsclient.PreviewDrawEligibilityResp
	QueryAvailableCouponsReq                = smsclient.QueryAvailableCouponsReq
	QueryAvailableCouponsResp               = smsclient.QueryAvailableCouponsResp
	QueryCouponByCodeReq                    = smsclient.QueryCouponByCodeReq
	QueryCouponByCodeResp                   = smsclient.QueryCouponByCodeResp
	QueryCouponByScopeIdReq                 = smsclient.QueryCouponByScopeIdReq
	QueryCouponByScopeIdResp                = smsclient.QueryCouponByScopeIdResp
	QueryCouponData                         = smsclient.QueryCouponData
	QueryCouponDetailReq                    = smsclient.QueryCouponDetailReq
	QueryCouponDetailResp                   = smsclient.QueryCouponDetailResp
	QueryCouponListReq                      = smsclient.QueryCouponListReq
	QueryCouponListResp                     = smsclient.QueryCouponListResp
	QueryCouponRecordDetailReq              = smsclient.QueryCouponRecordDetailReq
	QueryCouponRecordDetailResp             = smsclient.QueryCouponRecordDetailResp
	QueryCouponRecordListReq                = smsclient.QueryCouponRecordListReq
	QueryCouponRecordListResp               = smsclient.QueryCouponRecordListResp
	QueryCouponScopeDetailReq               = smsclient.QueryCouponScopeDetailReq
	QueryCouponScopeDetailResp              = smsclient.QueryCouponScopeDetailResp
	QueryCouponScopeListReq                 = smsclient.QueryCouponScopeListReq
	QueryCouponScopeListResp                = smsclient.QueryCouponScopeListResp
	QueryCouponTypeDetailReq                = smsclient.QueryCouponTypeDetailReq
	QueryCouponTypeDetailResp               = smsclient.QueryCouponTypeDetailResp
	QueryCouponTypeListReq                  = smsclient.QueryCouponTypeListReq
	QueryCouponTypeListResp                 = smsclient.QueryCouponTypeListResp
	QueryDrawActivityDetailReq              = smsclient.QueryDrawActivityDetailReq
	QueryDrawActivityDetailResp             = smsclient.QueryDrawActivityDetailResp
	QueryDrawActivityLandingReq             = smsclient.QueryDrawActivityLandingReq
	QueryDrawActivityLandingResp            = smsclient.QueryDrawActivityLandingResp
	QueryDrawActivityListReq                = smsclient.QueryDrawActivityListReq
	QueryDrawActivityListResp               = smsclient.QueryDrawActivityListResp
	QueryFlashPromotionListByDateResp       = smsclient.QueryFlashPromotionListByDateResp
	QueryHomeAdvertiseDetailReq             = smsclient.QueryHomeAdvertiseDetailReq
	QueryHomeAdvertiseDetailResp            = smsclient.QueryHomeAdvertiseDetailResp
	QueryHomeAdvertiseListReq               = smsclient.QueryHomeAdvertiseListReq
	QueryHomeAdvertiseListResp              = smsclient.QueryHomeAdvertiseListResp
	QueryMemberCouponListReq                = smsclient.QueryMemberCouponListReq
	QueryMemberCouponListResp               = smsclient.QueryMemberCouponListResp
	QueryMemberDrawRecordListReq            = smsclient.QueryMemberDrawRecordListReq
	QueryMemberDrawRecordListResp           = smsclient.QueryMemberDrawRecordListResp
	QueryOperateActivityOptionsReq          = smsclient.QueryOperateActivityOptionsReq
	QueryOperateActivityOptionsResp         = smsclient.QueryOperateActivityOptionsResp
	QueryOperateCouponRedeemReq             = smsclient.QueryOperateCouponRedeemReq
	QueryOperateCouponRedeemResp            = smsclient.QueryOperateCouponRedeemResp
	QueryOperateTrafficFunnelReq            = smsclient.QueryOperateTrafficFunnelReq
	QueryOperateTrafficFunnelResp           = smsclient.QueryOperateTrafficFunnelResp
	QuerySeckillActivityDetailReq           = smsclient.QuerySeckillActivityDetailReq
	QuerySeckillActivityDetailResp          = smsclient.QuerySeckillActivityDetailResp
	QuerySeckillActivityListByDateReq       = smsclient.QuerySeckillActivityListByDateReq
	QuerySeckillActivityListReq             = smsclient.QuerySeckillActivityListReq
	QuerySeckillActivityListResp            = smsclient.QuerySeckillActivityListResp
	QuerySeckillProductBySkuIdReq           = smsclient.QuerySeckillProductBySkuIdReq
	QuerySeckillProductDetailReq            = smsclient.QuerySeckillProductDetailReq
	QuerySeckillProductDetailResp           = smsclient.QuerySeckillProductDetailResp
	QuerySeckillProductListReq              = smsclient.QuerySeckillProductListReq
	QuerySeckillProductListResp             = smsclient.QuerySeckillProductListResp
	QuerySeckillReservationDetailReq        = smsclient.QuerySeckillReservationDetailReq
	QuerySeckillReservationDetailResp       = smsclient.QuerySeckillReservationDetailResp
	QuerySeckillReservationListReq          = smsclient.QuerySeckillReservationListReq
	QuerySeckillReservationListResp         = smsclient.QuerySeckillReservationListResp
	QuerySeckillSessionDetailReq            = smsclient.QuerySeckillSessionDetailReq
	QuerySeckillSessionDetailResp           = smsclient.QuerySeckillSessionDetailResp
	QuerySeckillSessionListByTimeReq        = smsclient.QuerySeckillSessionListByTimeReq
	QuerySeckillSessionListByTimeResp       = smsclient.QuerySeckillSessionListByTimeResp
	QuerySeckillSessionListReq              = smsclient.QuerySeckillSessionListReq
	QuerySeckillSessionListResp             = smsclient.QuerySeckillSessionListResp
	RecordOperateFunnelEventReq             = smsclient.RecordOperateFunnelEventReq
	RecordOperateFunnelEventResp            = smsclient.RecordOperateFunnelEventResp
	SeckillActivityListData                 = smsclient.SeckillActivityListData
	SeckillProductListData                  = smsclient.SeckillProductListData
	SeckillReservationListData              = smsclient.SeckillReservationListData
	SeckillSessionListData                  = smsclient.SeckillSessionListData
	UpdateCouponRecordReq                   = smsclient.UpdateCouponRecordReq
	UpdateCouponRecordResp                  = smsclient.UpdateCouponRecordResp
	UpdateCouponReq                         = smsclient.UpdateCouponReq
	UpdateCouponResp                        = smsclient.UpdateCouponResp
	UpdateCouponScopeReq                    = smsclient.UpdateCouponScopeReq
	UpdateCouponScopeResp                   = smsclient.UpdateCouponScopeResp
	UpdateCouponStatusReq                   = smsclient.UpdateCouponStatusReq
	UpdateCouponStatusResp                  = smsclient.UpdateCouponStatusResp
	UpdateCouponTypeReq                     = smsclient.UpdateCouponTypeReq
	UpdateCouponTypeResp                    = smsclient.UpdateCouponTypeResp
	UpdateCouponTypeStatusReq               = smsclient.UpdateCouponTypeStatusReq
	UpdateCouponTypeStatusResp              = smsclient.UpdateCouponTypeStatusResp
	UpdateDrawActivityReq                   = smsclient.UpdateDrawActivityReq
	UpdateDrawActivityResp                  = smsclient.UpdateDrawActivityResp
	UpdateDrawActivityStatusReq             = smsclient.UpdateDrawActivityStatusReq
	UpdateDrawActivityStatusResp            = smsclient.UpdateDrawActivityStatusResp
	UpdateHomeAdvertiseReq                  = smsclient.UpdateHomeAdvertiseReq
	UpdateHomeAdvertiseResp                 = smsclient.UpdateHomeAdvertiseResp
	UpdateHomeAdvertiseStatusReq            = smsclient.UpdateHomeAdvertiseStatusReq
	UpdateHomeAdvertiseStatusResp           = smsclient.UpdateHomeAdvertiseStatusResp
	UpdateSeckillActivityReq                = smsclient.UpdateSeckillActivityReq
	UpdateSeckillActivityResp               = smsclient.UpdateSeckillActivityResp
	UpdateSeckillActivityStatusReq          = smsclient.UpdateSeckillActivityStatusReq
	UpdateSeckillActivityStatusResp         = smsclient.UpdateSeckillActivityStatusResp
	UpdateSeckillProductReq                 = smsclient.UpdateSeckillProductReq
	UpdateSeckillProductResp                = smsclient.UpdateSeckillProductResp
	UpdateSeckillProductStatusReq           = smsclient.UpdateSeckillProductStatusReq
	UpdateSeckillProductStatusResp          = smsclient.UpdateSeckillProductStatusResp
	UpdateSeckillReservationReq             = smsclient.UpdateSeckillReservationReq
	UpdateSeckillReservationResp            = smsclient.UpdateSeckillReservationResp
	UpdateSeckillReservationStatusReq       = smsclient.UpdateSeckillReservationStatusReq
	UpdateSeckillReservationStatusResp      = smsclient.UpdateSeckillReservationStatusResp
	UpdateSeckillSessionReq                 = smsclient.UpdateSeckillSessionReq
	UpdateSeckillSessionResp                = smsclient.UpdateSeckillSessionResp
	UpdateSeckillSessionStatusReq           = smsclient.UpdateSeckillSessionStatusReq
	UpdateSeckillSessionStatusResp          = smsclient.UpdateSeckillSessionStatusResp

	OperateDashboardService interface {
		RecordOperateFunnelEvent(ctx context.Context, in *RecordOperateFunnelEventReq, opts ...grpc.CallOption) (*RecordOperateFunnelEventResp, error)
		QueryOperateTrafficFunnel(ctx context.Context, in *QueryOperateTrafficFunnelReq, opts ...grpc.CallOption) (*QueryOperateTrafficFunnelResp, error)
		QueryOperateCouponRedeem(ctx context.Context, in *QueryOperateCouponRedeemReq, opts ...grpc.CallOption) (*QueryOperateCouponRedeemResp, error)
		QueryOperateActivityOptions(ctx context.Context, in *QueryOperateActivityOptionsReq, opts ...grpc.CallOption) (*QueryOperateActivityOptionsResp, error)
	}

	defaultOperateDashboardService struct {
		cli zrpc.Client
	}
)

func NewOperateDashboardService(cli zrpc.Client) OperateDashboardService {
	return &defaultOperateDashboardService{
		cli: cli,
	}
}

func (m *defaultOperateDashboardService) RecordOperateFunnelEvent(ctx context.Context, in *RecordOperateFunnelEventReq, opts ...grpc.CallOption) (*RecordOperateFunnelEventResp, error) {
	client := smsclient.NewOperateDashboardServiceClient(m.cli.Conn())
	return client.RecordOperateFunnelEvent(ctx, in, opts...)
}

func (m *defaultOperateDashboardService) QueryOperateTrafficFunnel(ctx context.Context, in *QueryOperateTrafficFunnelReq, opts ...grpc.CallOption) (*QueryOperateTrafficFunnelResp, error) {
	client := smsclient.NewOperateDashboardServiceClient(m.cli.Conn())
	return client.QueryOperateTrafficFunnel(ctx, in, opts...)
}

func (m *defaultOperateDashboardService) QueryOperateCouponRedeem(ctx context.Context, in *QueryOperateCouponRedeemReq, opts ...grpc.CallOption) (*QueryOperateCouponRedeemResp, error) {
	client := smsclient.NewOperateDashboardServiceClient(m.cli.Conn())
	return client.QueryOperateCouponRedeem(ctx, in, opts...)
}

func (m *defaultOperateDashboardService) QueryOperateActivityOptions(ctx context.Context, in *QueryOperateActivityOptionsReq, opts ...grpc.CallOption) (*QueryOperateActivityOptionsResp, error) {
	client := smsclient.NewOperateDashboardServiceClient(m.cli.Conn())
	return client.QueryOperateActivityOptions(ctx, in, opts...)
}
