// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: sys.proto

package server

import (
	"context"

	"github.com/feihua/zero-admin/rpc/sys/internal/logic/merchantservice"
	"github.com/feihua/zero-admin/rpc/sys/internal/svc"
	"github.com/feihua/zero-admin/rpc/sys/sysclient"
)

type MerchantServiceServer struct {
	svcCtx *svc.ServiceContext
	sysclient.UnimplementedMerchantServiceServer
}

func NewMerchantServiceServer(svcCtx *svc.ServiceContext) *MerchantServiceServer {
	return &MerchantServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *MerchantServiceServer) CreateMerchant(ctx context.Context, in *sysclient.CreateMerchantReq) (*sysclient.CreateMerchantResp, error) {
	l := merchantservicelogic.NewCreateMerchantLogic(ctx, s.svcCtx)
	return l.CreateMerchant(in)
}

func (s *MerchantServiceServer) QueryMerchantDetail(ctx context.Context, in *sysclient.QueryMerchantDetailReq) (*sysclient.QueryMerchantDetailResp, error) {
	l := merchantservicelogic.NewQueryMerchantDetailLogic(ctx, s.svcCtx)
	return l.QueryMerchantDetail(in)
}

func (s *MerchantServiceServer) QueryMerchantList(ctx context.Context, in *sysclient.QueryMerchantListReq) (*sysclient.QueryMerchantListResp, error) {
	l := merchantservicelogic.NewQueryMerchantListLogic(ctx, s.svcCtx)
	return l.QueryMerchantList(in)
}

func (s *MerchantServiceServer) ApproveMerchant(ctx context.Context, in *sysclient.ReviewMerchantReq) (*sysclient.ReviewMerchantResp, error) {
	l := merchantservicelogic.NewApproveMerchantLogic(ctx, s.svcCtx)
	return l.ApproveMerchant(in)
}

func (s *MerchantServiceServer) RejectMerchant(ctx context.Context, in *sysclient.ReviewMerchantReq) (*sysclient.ReviewMerchantResp, error) {
	l := merchantservicelogic.NewRejectMerchantLogic(ctx, s.svcCtx)
	return l.RejectMerchant(in)
}

func (s *MerchantServiceServer) RequestMerchantMaterial(ctx context.Context, in *sysclient.ReviewMerchantReq) (*sysclient.ReviewMerchantResp, error) {
	l := merchantservicelogic.NewRequestMerchantMaterialLogic(ctx, s.svcCtx)
	return l.RequestMerchantMaterial(in)
}

func (s *MerchantServiceServer) EnableMerchant(ctx context.Context, in *sysclient.ChangeMerchantStatusReq) (*sysclient.ChangeMerchantStatusResp, error) {
	l := merchantservicelogic.NewEnableMerchantLogic(ctx, s.svcCtx)
	return l.EnableMerchant(in)
}

func (s *MerchantServiceServer) DisableMerchant(ctx context.Context, in *sysclient.ChangeMerchantStatusReq) (*sysclient.ChangeMerchantStatusResp, error) {
	l := merchantservicelogic.NewDisableMerchantLogic(ctx, s.svcCtx)
	return l.DisableMerchant(in)
}

func (s *MerchantServiceServer) ArchiveMerchant(ctx context.Context, in *sysclient.ChangeMerchantStatusReq) (*sysclient.ChangeMerchantStatusResp, error) {
	l := merchantservicelogic.NewArchiveMerchantLogic(ctx, s.svcCtx)
	return l.ArchiveMerchant(in)
}
