// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: sys.proto

package server

import (
	"context"

	"github.com/feihua/zero-admin/rpc/sys/internal/logic/auditcenterservice"
	"github.com/feihua/zero-admin/rpc/sys/internal/svc"
	"github.com/feihua/zero-admin/rpc/sys/sysclient"
)

type AuditCenterServiceServer struct {
	svcCtx *svc.ServiceContext
	sysclient.UnimplementedAuditCenterServiceServer
}

func NewAuditCenterServiceServer(svcCtx *svc.ServiceContext) *AuditCenterServiceServer {
	return &AuditCenterServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AuditCenterServiceServer) QueryAuditCenterList(ctx context.Context, in *sysclient.QueryAuditCenterListReq) (*sysclient.QueryAuditCenterListResp, error) {
	l := auditcenterservicelogic.NewQueryAuditCenterListLogic(ctx, s.svcCtx)
	return l.QueryAuditCenterList(in)
}

func (s *AuditCenterServiceServer) QueryAuditCenterDetail(ctx context.Context, in *sysclient.QueryAuditCenterDetailReq) (*sysclient.QueryAuditCenterDetailResp, error) {
	l := auditcenterservicelogic.NewQueryAuditCenterDetailLogic(ctx, s.svcCtx)
	return l.QueryAuditCenterDetail(in)
}
