CREATE TABLE IF NOT EXISTS sys_merchant
(
    id                    BIGINT AUTO_INCREMENT COMMENT '商户主键' PRIMARY KEY,
    platform_id           BIGINT DEFAULT 1 NOT NULL COMMENT '平台ID',
    tenant_id             BIGINT NOT NULL COMMENT '归属租户ID',
    merchant_code         VARCHAR(32) NOT NULL COMMENT '商户编码',
    merchant_name         VARCHAR(64) NOT NULL COMMENT '商户名称',
    merchant_short_name   VARCHAR(64) DEFAULT '' NOT NULL COMMENT '商户简称',
    contact_name          VARCHAR(32) NOT NULL COMMENT '联系人姓名',
    contact_mobile        CHAR(11) NOT NULL COMMENT '联系人手机号',
    contact_email         VARCHAR(64) DEFAULT '' NOT NULL COMMENT '联系人邮箱',
    available_channels    VARCHAR(500) DEFAULT '[]' NOT NULL COMMENT '可用渠道(JSON数组)',
    capability_flags      VARCHAR(1000) DEFAULT '[]' NOT NULL COMMENT '能力包(JSON数组)',
    review_status         TINYINT DEFAULT 0 NOT NULL COMMENT '审核状态(0:待审核,1:补充材料,2:驳回,3:已通过)',
    review_reason         VARCHAR(255) DEFAULT '' NOT NULL COMMENT '审核结论说明',
    reviewed_by           BIGINT DEFAULT 0 NOT NULL COMMENT '审核处理人ID',
    reviewed_by_name      VARCHAR(50) DEFAULT '' NOT NULL COMMENT '审核处理人名称',
    reviewed_at           DATETIME NULL COMMENT '审核处理时间',
    business_status       TINYINT DEFAULT 0 NOT NULL COMMENT '经营状态(0:待激活,1:已启用,2:已停用,3:已归档)',
    status_reason         VARCHAR(255) DEFAULT '' NOT NULL COMMENT '经营状态说明',
    visible_scope_hint    VARCHAR(255) DEFAULT '' NOT NULL COMMENT '可见范围提示',
    primary_admin_user_id BIGINT DEFAULT 0 NOT NULL COMMENT '首个后台管理员用户ID',
    remark                VARCHAR(255) DEFAULT '' NOT NULL COMMENT '备注',
    archived_at           DATETIME NULL COMMENT '归档时间',
    created_by            VARCHAR(50) DEFAULT 'admin' NOT NULL COMMENT '创建者',
    created_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间',
    updated_by            VARCHAR(50) DEFAULT '' NOT NULL COMMENT '更新者',
    updated_at            DATETIME NULL COMMENT '更新时间',
    CONSTRAINT uk_sys_merchant_tenant_code UNIQUE (tenant_id, merchant_code),
    KEY idx_sys_merchant_status (platform_id, tenant_id, review_status, business_status),
    KEY idx_sys_merchant_name (platform_id, tenant_id, merchant_name),
    KEY idx_sys_merchant_primary_admin (primary_admin_user_id)
) COMMENT='商户主体治理表';
