// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: ums.proto

package server

import (
	"context"

	"github.com/feihua/zero-admin/rpc/ums/internal/logic/memberidentityservice"
	"github.com/feihua/zero-admin/rpc/ums/internal/svc"
	"github.com/feihua/zero-admin/rpc/ums/umsclient"
)

type MemberIdentityServiceServer struct {
	svcCtx *svc.ServiceContext
	umsclient.UnimplementedMemberIdentityServiceServer
}

func NewMemberIdentityServiceServer(svcCtx *svc.ServiceContext) *MemberIdentityServiceServer {
	return &MemberIdentityServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *MemberIdentityServiceServer) QueryMemberIdentityProfile(ctx context.Context, in *umsclient.QueryMemberIdentityProfileReq) (*umsclient.QueryMemberIdentityProfileResp, error) {
	l := memberidentityservicelogic.NewQueryMemberIdentityProfileLogic(ctx, s.svcCtx)
	return l.QueryMemberIdentityProfile(in)
}
