// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: pms.proto

package server

import (
	"context"

	"github.com/feihua/zero-admin/rpc/pms/internal/logic/productcategoryservice"
	"github.com/feihua/zero-admin/rpc/pms/internal/svc"
	"github.com/feihua/zero-admin/rpc/pms/pmsclient"
)

type ProductCategoryServiceServer struct {
	svcCtx *svc.ServiceContext
	pmsclient.UnimplementedProductCategoryServiceServer
}

func NewProductCategoryServiceServer(svcCtx *svc.ServiceContext) *ProductCategoryServiceServer {
	return &ProductCategoryServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductCategoryServiceServer) AddProductCategory(ctx context.Context, in *pmsclient.AddProductCategoryReq) (*pmsclient.AddProductCategoryResp, error) {
	l := productcategoryservicelogic.NewAddProductCategoryLogic(ctx, s.svcCtx)
	return l.AddProductCategory(in)
}

func (s *ProductCategoryServiceServer) DeleteProductCategory(ctx context.Context, in *pmsclient.DeleteProductCategoryReq) (*pmsclient.DeleteProductCategoryResp, error) {
	l := productcategoryservicelogic.NewDeleteProductCategoryLogic(ctx, s.svcCtx)
	return l.DeleteProductCategory(in)
}

func (s *ProductCategoryServiceServer) UpdateProductCategory(ctx context.Context, in *pmsclient.UpdateProductCategoryReq) (*pmsclient.UpdateProductCategoryResp, error) {
	l := productcategoryservicelogic.NewUpdateProductCategoryLogic(ctx, s.svcCtx)
	return l.UpdateProductCategory(in)
}

func (s *ProductCategoryServiceServer) UpdateCategoryNavStatus(ctx context.Context, in *pmsclient.UpdateProductCategoryStatusReq) (*pmsclient.UpdateProductCategoryStatusResp, error) {
	l := productcategoryservicelogic.NewUpdateCategoryNavStatusLogic(ctx, s.svcCtx)
	return l.UpdateCategoryNavStatus(in)
}

func (s *ProductCategoryServiceServer) UpdateProductCategoryStatus(ctx context.Context, in *pmsclient.UpdateProductCategoryStatusReq) (*pmsclient.UpdateProductCategoryStatusResp, error) {
	l := productcategoryservicelogic.NewUpdateProductCategoryStatusLogic(ctx, s.svcCtx)
	return l.UpdateProductCategoryStatus(in)
}

func (s *ProductCategoryServiceServer) QueryProductCategoryDetail(ctx context.Context, in *pmsclient.QueryProductCategoryDetailReq) (*pmsclient.QueryProductCategoryDetailResp, error) {
	l := productcategoryservicelogic.NewQueryProductCategoryDetailLogic(ctx, s.svcCtx)
	return l.QueryProductCategoryDetail(in)
}

func (s *ProductCategoryServiceServer) QueryProductCategoryList(ctx context.Context, in *pmsclient.QueryProductCategoryListReq) (*pmsclient.QueryProductCategoryListResp, error) {
	l := productcategoryservicelogic.NewQueryProductCategoryListLogic(ctx, s.svcCtx)
	return l.QueryProductCategoryList(in)
}

func (s *ProductCategoryServiceServer) QueryProductCategoryTreeList(ctx context.Context, in *pmsclient.QueryProductCategoryTreeListReq) (*pmsclient.QueryProductCategoryListTreeResp, error) {
	l := productcategoryservicelogic.NewQueryProductCategoryTreeListLogic(ctx, s.svcCtx)
	return l.QueryProductCategoryTreeList(in)
}
