package productspecvalueservicelogic
import (
	"context"; "errors"
	"github.com/feihua/zero-admin/pkg/pointerprocess"; pkgscope "github.com/feihua/zero-admin/pkg/scope"; "github.com/feihua/zero-admin/pkg/time_util"
	logiccommon "github.com/feihua/zero-admin/rpc/pms/internal/logic/common"; "github.com/feihua/zero-admin/rpc/pms/internal/svc"; "github.com/feihua/zero-admin/rpc/pms/pmsclient"; "github.com/zeromicro/go-zero/core/logc"; "github.com/zeromicro/go-zero/core/logx")

type QueryProductSpecValueListLogic struct { ctx context.Context; svcCtx *svc.ServiceContext; logx.Logger }
func NewQueryProductSpecValueListLogic(ctx context.Context, svcCtx *svc.ServiceContext) *QueryProductSpecValueListLogic { return &QueryProductSpecValueListLogic{ctx:ctx, svcCtx:svcCtx, Logger:logx.WithContext(ctx)} }
func (l *QueryProductSpecValueListLogic) QueryProductSpecValueList(in *pmsclient.QueryProductSpecValueListReq) (*pmsclient.QueryProductSpecValueListResp, error) { current, err := logiccommon.NormalizeProtoScope(in.Scope); if err != nil { return nil, err }; db := pkgscope.ApplyGovernanceScope(l.svcCtx.DB.WithContext(l.ctx).Table("pms_product_spec_value").Where("is_deleted = 0"), current, ""); if in.SpecId != 0 { db = db.Where("spec_id = ?", in.SpecId) }; if in.Status != 2 { db = db.Where("status = ?", in.Status) }; var total int64; if err := db.Count(&total).Error; err != nil { logc.Errorf(l.ctx, "查询商品规格值总数失败,参数:%+v,异常:%s", in, err.Error()); return nil, errors.New("查询商品规格值列表失败") }; var rows []logiccommon.ProductSpecValueRow; if err := db.Order("sort asc, id desc").Offset(int((in.PageNum-1)*in.PageSize)).Limit(int(in.PageSize)).Scan(&rows).Error; err != nil { logc.Errorf(l.ctx, "查询商品规格值列表失败,参数:%+v,异常:%s", in, err.Error()); return nil, errors.New("查询商品规格值列表失败") }; list := make([]*pmsclient.ProductSpecValueListData,0,len(rows)); for _, item := range rows { list = append(list, &pmsclient.ProductSpecValueListData{Id:item.ID,SpecId:item.SpecID,Value:item.Value,Sort:item.Sort,Status:item.Status,CreateBy:item.CreateBy,CreateTime:time_util.TimeToStr(item.CreateTime),UpdateBy:pointerprocess.DefaltData(item.UpdateBy).(int64),UpdateTime:time_util.TimeToString(item.UpdateTime),ScopeType:current.ScopeType,PlatformId:item.PlatformID,TenantId:item.TenantID,MerchantId:item.MerchantID}) }; return &pmsclient.QueryProductSpecValueListResp{Total:total,List:list}, nil }
