package productspecvalueservicelogic
import (
	"context"; "errors"
	"github.com/feihua/zero-admin/pkg/pointerprocess"; pkgscope "github.com/feihua/zero-admin/pkg/scope"; "github.com/feihua/zero-admin/pkg/time_util"
	logiccommon "github.com/feihua/zero-admin/rpc/pms/internal/logic/common"; "github.com/feihua/zero-admin/rpc/pms/internal/svc"; "github.com/feihua/zero-admin/rpc/pms/pmsclient"; "github.com/zeromicro/go-zero/core/logc"; "github.com/zeromicro/go-zero/core/logx"; "gorm.io/gorm")

type QueryProductSpecValueDetailLogic struct { ctx context.Context; svcCtx *svc.ServiceContext; logx.Logger }
func NewQueryProductSpecValueDetailLogic(ctx context.Context, svcCtx *svc.ServiceContext) *QueryProductSpecValueDetailLogic { return &QueryProductSpecValueDetailLogic{ctx:ctx, svcCtx:svcCtx, Logger:logx.WithContext(ctx)} }
func (l *QueryProductSpecValueDetailLogic) QueryProductSpecValueDetail(in *pmsclient.QueryProductSpecValueDetailReq) (*pmsclient.QueryProductSpecValueDetailResp, error) { current, err := logiccommon.NormalizeProtoScope(in.Scope); if err != nil { return nil, err }; var item logiccommon.ProductSpecValueRow; scopeWhere, scopeArgs := pkgscope.ScopeFilterSQL("", current); err = l.svcCtx.DB.WithContext(l.ctx).Table("pms_product_spec_value").Where("id = ? AND is_deleted = 0", in.Id).Where(scopeWhere, scopeArgs...).Take(&item).Error; switch { case errors.Is(err, gorm.ErrRecordNotFound): logc.Errorf(l.ctx, "商品规格值不存在, 请求参数：%+v, 异常信息: %s", in, err.Error()); return nil, errors.New("商品规格值不存在"); case err != nil: logc.Errorf(l.ctx, "查询商品规格值异常, 请求参数：%+v, 异常信息: %s", in, err.Error()); return nil, errors.New("查询商品规格值异常") }; return &pmsclient.QueryProductSpecValueDetailResp{Id:item.ID,SpecId:item.SpecID,Value:item.Value,Sort:item.Sort,Status:item.Status,CreateBy:item.CreateBy,CreateTime:time_util.TimeToStr(item.CreateTime),UpdateBy:pointerprocess.DefaltData(item.UpdateBy).(int64),UpdateTime:time_util.TimeToString(item.UpdateTime),ScopeType:current.ScopeType,PlatformId:item.PlatformID,TenantId:item.TenantID,MerchantId:item.MerchantID}, nil }
