package productspecservicelogic
import (
	"context"; "errors"
	"github.com/feihua/zero-admin/pkg/pointerprocess"; pkgscope "github.com/feihua/zero-admin/pkg/scope"; "github.com/feihua/zero-admin/pkg/time_util"
	logiccommon "github.com/feihua/zero-admin/rpc/pms/internal/logic/common"; "github.com/feihua/zero-admin/rpc/pms/internal/svc"; "github.com/feihua/zero-admin/rpc/pms/pmsclient"; "github.com/zeromicro/go-zero/core/logc"; "github.com/zeromicro/go-zero/core/logx")

type QueryProductSpecListLogic struct { ctx context.Context; svcCtx *svc.ServiceContext; logx.Logger }
func NewQueryProductSpecListLogic(ctx context.Context, svcCtx *svc.ServiceContext) *QueryProductSpecListLogic { return &QueryProductSpecListLogic{ctx:ctx, svcCtx:svcCtx, Logger:logx.WithContext(ctx)} }
func (l *QueryProductSpecListLogic) QueryProductSpecList(in *pmsclient.QueryProductSpecListReq) (*pmsclient.QueryProductSpecListResp, error) { current, err := logiccommon.NormalizeProtoScope(in.Scope); if err != nil { return nil, err }; db := pkgscope.ApplyGovernanceScope(l.svcCtx.DB.WithContext(l.ctx).Table("pms_product_spec").Where("is_deleted = 0"), current, ""); if in.CategoryId != 0 { db = db.Where("category_id = ?", in.CategoryId) }; if in.Name != "" { db = db.Where("name LIKE ?", "%"+in.Name+"%") }; if in.Status != 2 { db = db.Where("status = ?", in.Status) }; var total int64; if err := db.Count(&total).Error; err != nil { logc.Errorf(l.ctx, "查询商品规格总数失败,参数:%+v,异常:%s", in, err.Error()); return nil, errors.New("查询商品规格列表失败") }; var rows []logiccommon.ProductSpecRow; if err := db.Order("sort asc, id desc").Offset(int((in.PageNum-1)*in.PageSize)).Limit(int(in.PageSize)).Scan(&rows).Error; err != nil { logc.Errorf(l.ctx, "查询商品规格列表失败,参数:%+v,异常:%s", in, err.Error()); return nil, errors.New("查询商品规格列表失败") }; list := make([]*pmsclient.ProductSpecListData,0,len(rows)); for _, item := range rows { list = append(list, &pmsclient.ProductSpecListData{Id:item.ID,CategoryId:item.CategoryID,Name:item.Name,Sort:item.Sort,Status:item.Status,CreateBy:item.CreateBy,CreateTime:time_util.TimeToStr(item.CreateTime),UpdateBy:pointerprocess.DefaltData(item.UpdateBy).(int64),UpdateTime:time_util.TimeToString(item.UpdateTime),IsDeleted:item.IsDeleted,ScopeType:current.ScopeType,PlatformId:item.PlatformID,TenantId:item.TenantID,MerchantId:item.MerchantID}) }; return &pmsclient.QueryProductSpecListResp{Total:total,List:list}, nil }
