// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: sms.proto

package server

import (
	"context"

	"github.com/feihua/zero-admin/rpc/sms/internal/logic/operatedashboardservice"
	"github.com/feihua/zero-admin/rpc/sms/internal/svc"
	"github.com/feihua/zero-admin/rpc/sms/smsclient"
)

type OperateDashboardServiceServer struct {
	svcCtx *svc.ServiceContext
	smsclient.UnimplementedOperateDashboardServiceServer
}

func NewOperateDashboardServiceServer(svcCtx *svc.ServiceContext) *OperateDashboardServiceServer {
	return &OperateDashboardServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *OperateDashboardServiceServer) RecordOperateFunnelEvent(ctx context.Context, in *smsclient.RecordOperateFunnelEventReq) (*smsclient.RecordOperateFunnelEventResp, error) {
	l := operatedashboardservicelogic.NewRecordOperateFunnelEventLogic(ctx, s.svcCtx)
	return l.RecordOperateFunnelEvent(in)
}

func (s *OperateDashboardServiceServer) QueryOperateTrafficFunnel(ctx context.Context, in *smsclient.QueryOperateTrafficFunnelReq) (*smsclient.QueryOperateTrafficFunnelResp, error) {
	l := operatedashboardservicelogic.NewQueryOperateTrafficFunnelLogic(ctx, s.svcCtx)
	return l.QueryOperateTrafficFunnel(in)
}

func (s *OperateDashboardServiceServer) QueryOperateCouponRedeem(ctx context.Context, in *smsclient.QueryOperateCouponRedeemReq) (*smsclient.QueryOperateCouponRedeemResp, error) {
	l := operatedashboardservicelogic.NewQueryOperateCouponRedeemLogic(ctx, s.svcCtx)
	return l.QueryOperateCouponRedeem(in)
}

func (s *OperateDashboardServiceServer) QueryOperateActivityOptions(ctx context.Context, in *smsclient.QueryOperateActivityOptionsReq) (*smsclient.QueryOperateActivityOptionsResp, error) {
	l := operatedashboardservicelogic.NewQueryOperateActivityOptionsLogic(ctx, s.svcCtx)
	return l.QueryOperateActivityOptions(in)
}
