// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: ums.proto

package server

import (
	"context"

	"github.com/feihua/zero-admin/rpc/ums/internal/logic/membermessageservice"
	"github.com/feihua/zero-admin/rpc/ums/internal/svc"
	"github.com/feihua/zero-admin/rpc/ums/umsclient"
)

type MemberMessageServiceServer struct {
	svcCtx *svc.ServiceContext
	umsclient.UnimplementedMemberMessageServiceServer
}

func NewMemberMessageServiceServer(svcCtx *svc.ServiceContext) *MemberMessageServiceServer {
	return &MemberMessageServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *MemberMessageServiceServer) AddMemberMessage(ctx context.Context, in *umsclient.AddMemberMessageReq) (*umsclient.AddMemberMessageResp, error) {
	l := membermessageservicelogic.NewAddMemberMessageLogic(ctx, s.svcCtx)
	return l.AddMemberMessage(in)
}

func (s *MemberMessageServiceServer) QueryMemberMessageList(ctx context.Context, in *umsclient.QueryMemberMessageListReq) (*umsclient.QueryMemberMessageListResp, error) {
	l := membermessageservicelogic.NewQueryMemberMessageListLogic(ctx, s.svcCtx)
	return l.QueryMemberMessageList(in)
}

func (s *MemberMessageServiceServer) QueryMemberMessageDetail(ctx context.Context, in *umsclient.QueryMemberMessageDetailReq) (*umsclient.QueryMemberMessageDetailResp, error) {
	l := membermessageservicelogic.NewQueryMemberMessageDetailLogic(ctx, s.svcCtx)
	return l.QueryMemberMessageDetail(in)
}

func (s *MemberMessageServiceServer) MarkMessageAsRead(ctx context.Context, in *umsclient.MarkMessageAsReadReq) (*umsclient.MarkMessageAsReadResp, error) {
	l := membermessageservicelogic.NewMarkMessageAsReadLogic(ctx, s.svcCtx)
	return l.MarkMessageAsRead(in)
}

func (s *MemberMessageServiceServer) MarkAllMessagesAsRead(ctx context.Context, in *umsclient.MarkAllMessagesAsReadReq) (*umsclient.MarkAllMessagesAsReadResp, error) {
	l := membermessageservicelogic.NewMarkAllMessagesAsReadLogic(ctx, s.svcCtx)
	return l.MarkAllMessagesAsRead(in)
}

func (s *MemberMessageServiceServer) DeleteMemberMessage(ctx context.Context, in *umsclient.DeleteMemberMessageReq) (*umsclient.DeleteMemberMessageResp, error) {
	l := membermessageservicelogic.NewDeleteMemberMessageLogic(ctx, s.svcCtx)
	return l.DeleteMemberMessage(in)
}

func (s *MemberMessageServiceServer) QueryUnreadCount(ctx context.Context, in *umsclient.QueryUnreadCountReq) (*umsclient.QueryUnreadCountResp, error) {
	l := membermessageservicelogic.NewQueryUnreadCountLogic(ctx, s.svcCtx)
	return l.QueryUnreadCount(in)
}
