// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddCommentReq struct {
	ProductId        int64  `json:"productId"`
	MemberNickName   string `json:"memberNickName"`
	ProductName      string `json:"productName"`
	Star             int32  `json:"star"`
	ProductAttribute string `json:"productAttribute"`
	Content          string `json:"content"`
	Pics             string `json:"pics"`
	MemberIcon       string `json:"memberIcon"`
	OrderId          int64  `json:"orderId"`
}

type AddCommentResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type AddCouponReq struct {
	CouponId int64 `json:"couponId"`
}

type AddCouponResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type AddressReq struct {
	Id            int64  `json:"id,optional"`   //主键ID
	ReceiverName  string `json:"receiverName"`  //收货人姓名
	ReceiverPhone string `json:"receiverPhone"` //收货人电话
	Province      string `json:"province"`      //省份
	City          string `json:"city"`          //城市
	District      string `json:"district"`      //区县
	DetailAddress string `json:"detailAddress"` //详细地址
	PostalCode    string `json:"postalCode"`    //邮政编码
	Tag           string `json:"tag"`           //地址标签：家、公司等
	IsDefault     int32  `json:"isDefault"`     //是否默认地址
}

type AddressResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type AdvertiseList struct {
	Id           int64  `json:"id"`           //编号
	Name         string `json:"name"`         //名称
	Type         int32  `json:"type"`         //轮播位置：0->PC首页轮播；1->app首页轮播
	Pic          string `json:"pic"`          //图片地址
	StartTime    string `json:"startTime"`    //开始时间
	EndTime      string `json:"endTime"`      //结束时间
	Status       int32  `json:"status"`       //上下线状态：0->下线；1->上线
	ClickCount   int32  `json:"clickCount"`   //点击数
	OrderCount   int32  `json:"orderCount"`   //下单数
	Url          string `json:"url"`          //链接地址
	ActivityType string `json:"activityType"` //活动类型
	ActivityId   int64  `json:"activityId"`   //活动ID
	Remark       string `json:"remark"`       //备注
	Sort         int32  `json:"sort"`         //排序
}

type AppVersionPolicyData struct {
	CurrentVersion       string   `json:"currentVersion"`
	MinSupportedVersion  string   `json:"minSupportedVersion"`
	RecommendedVersion   string   `json:"recommendedVersion"`
	RequiredVersion      string   `json:"requiredVersion"`
	UpdateMode           string   `json:"updateMode"`
	EffectiveAt          string   `json:"effectiveAt"`
	DeadlineAt           string   `json:"deadlineAt"`
	AffectedCapabilities []string `json:"affectedCapabilities"`
	Blocking             bool     `json:"blocking"`
	ReleaseNotesSummary  string   `json:"releaseNotesSummary"`
	UpgradeUrl           string   `json:"upgradeUrl"`
	StoreTarget          string   `json:"storeTarget"`
	RecoveryHint         string   `json:"recoveryHint"`
	TraceId              string   `json:"traceId"`
	Platform             string   `json:"platform"`
	Channel              string   `json:"channel"`
	InstallerStore       string   `json:"installerStore"`
	Scene                string   `json:"scene"`
	TargetType           string   `json:"targetType"`
	TargetId             int64    `json:"targetId"`
}

type AppVersionPolicyReq struct {
	Scene          string `form:"scene,optional"`
	TargetType     string `form:"targetType,optional"`
	TargetId       int64  `form:"targetId,optional"`
	Channel        string `form:"channel,optional"`
	InstallerStore string `form:"installerStore,optional"`
}

type AppVersionPolicyResp struct {
	Code    int64                `json:"code"`
	Message string               `json:"message"`
	Data    AppVersionPolicyData `json:"data"`
}

type ApplyAfterSalesReq struct {
	OrderId     int64  `json:"orderId"`     // 关联订单ID
	Type        int32  `json:"type"`        // 售后类型：0=退货退款, 1=仅退款, 2=换货
	ReasonId    int64  `json:"reasonId"`    // 退货原因ID
	Description string `json:"description"` // 问题描述（可选）
	ProofPics   string `json:"proofPics"`   // 凭证图片（base64，逗号分隔）
}

type ApplyAfterSalesResp struct {
	Code     int64  `json:"code"`
	Message  string `json:"message"`
	ReturnId int64  `json:"returnId"` // 售后单ID
	ReturnNo string `json:"returnNo"` // 售后单号
}

type AttentionReq struct {
	BrandId   int64  `json:"brandId"`   // 品牌id
	BrandName string `json:"brandName"` // 品牌名称
	BrandLogo string `json:"brandLogo"` // 品牌Logo
	BrandCity string `json:"brandCity"` // 品牌所在城市
}

type AttentionResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type BrandData struct {
	Id                  int64  `json:"id"`                  //
	Name                string `json:"name"`                //品牌名称
	Logo                string `json:"logo"`                //品牌logo
	BigPic              string `json:"bigPic"`              //专区大图
	Description         string `json:"description"`         //描述
	FirstLetter         string `json:"firstLetter"`         //首字母
	Sort                int32  `json:"sort"`                //排序
	RecommendStatus     int32  `json:"recommendStatus"`     //推荐状态
	ProductCount        int32  `json:"productCount"`        //产品数量
	ProductCommentCount int32  `json:"productCommentCount"` //产品评论数量
}

type BrandDetailData struct {
	BrandData        BrandData          `json:"brandData"`
	BrandProductData []BrandProductData `json:"brandProductData"`
}

type BrandListReq struct {
	Current  int32 `form:"current,default=1"`
	PageSize int32 `form:"pageSize,default=6"`
}

type BrandListResp struct {
	Code    int64       `json:"code"`
	Message string      `json:"message"`
	Data    []BrandData `json:"data"`
}

type BrandProductData struct {
	Id                  int64   `json:"id"`                  //商品SpuId
	Name                string  `json:"name"`                //商品名称
	ProductSn           string  `json:"productSn"`           //商品货号
	CategoryId          int64   `json:"categoryId"`          //商品分类ID
	CategoryIds         string  `json:"categoryIds"`         //商品分类ID集合
	CategoryName        string  `json:"categoryName"`        //商品分类名称
	BrandId             int64   `json:"brandId"`             //品牌ID
	BrandName           string  `json:"brandName"`           //品牌名称
	Unit                string  `json:"unit"`                //单位
	Weight              float32 `json:"weight"`              //重量(kg)
	Keywords            string  `json:"keywords"`            //关键词
	AlbumPics           string  `json:"albumPics"`           //画册图片，最多8张，以逗号分割
	MainPic             string  `json:"mainPic"`             //主图
	Price               string  `json:"price"`               //价格
	PriceRange          string  `json:"priceRange"`          //价格区间
	PublishStatus       int32   `json:"publishStatus"`       //上架状态：0-下架，1-上架
	NewStatus           int32   `json:"newStatus"`           //新品状态:0->不是新品；1->新品
	RecommendStatus     int32   `json:"recommendStatus"`     //推荐状态；0->不推荐；1->推荐
	VerifyStatus        int32   `json:"verifyStatus"`        //审核状态：0->未审核；1->审核通过
	PreviewStatus       int32   `json:"previewStatus"`       //是否为预告商品：0->不是；1->是
	Sort                int32   `json:"sort"`                //排序
	NewStatusSort       int32   `json:"newStatusSort"`       //新品排序
	RecommendStatusSort int32   `json:"recommendStatusSort"` //推荐排序
	Sales               int32   `json:"sales"`               //销量
	Stock               int32   `json:"stock"`               //库存
	LowStock            int32   `json:"lowStock"`            //预警库存
	PromotionType       int32   `json:"promotionType"`       //促销类型：0->没有促销使用原价;1->使用促销价；2->使用会员价；3->使用阶梯价格；4->使用满减价格；5->秒杀
	SubTitle            string  `json:"subTitle"`            //副标题
	DetailHtml          string  `json:"detailHtml"`          //产品详情网页内容
	DetailMobileHtml    string  `json:"detailMobileHtml"`    //移动端网页详情
}

type CalcAmount struct {
	TotalAmount     int64 `json:"totalAmount"`
	FreightAmount   int64 `json:"freightAmount"`
	PromotionAmount int64 `json:"promotionAmount"`
	PayAmount       int64 `json:"payAmount"`
}

type CancelUserOrderReq struct {
	OrderId int64 `form:"orderId"`
}

type CancelUserOrderResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type CarItemListPromotionReq struct {
	Ids []int64 `json:"ids,optional"`
}

type CarItemtListPromotionResp struct {
	Code    int64                       `json:"code"`
	Message string                      `json:"message"`
	Data    []CarItemtPromotionListData `json:"data"`
}

type CarItemtPromotionListData struct {
	Id                int64   `json:"id"`                //主键ID
	MemberId          int64   `json:"memberId"`          //会员ID
	ProductId         int64   `json:"productId"`         //商品ID
	ProductSkuId      int64   `json:"productSkuId"`      //商品SKU ID
	Quantity          int32   `json:"quantity"`          //购买数量
	Price             float32 `json:"price"`             //添加到购物车时的价格
	Selected          int32   `json:"selected"`          //是否选中 0-未选中 1-选中
	ProductName       string  `json:"productName"`       //商品名称
	ProductSubTitle   string  `json:"productSubTitle"`   //商品副标题
	ProductPic        string  `json:"productPic"`        //商品主图URL
	ProductSkuCode    string  `json:"productSkuCode"`    //商品SKU编码
	ProductSn         string  `json:"productSn"`         //商品货号
	ProductBrand      string  `json:"productBrand"`      //商品品牌
	ProductCategoryId int64   `json:"productCategoryId"` //商品分类ID
	ProductAttr       string  `json:"productAttr"`       //商品销售属性JSON
	MemberNickname    string  `json:"memberNickname"`    //会员昵称
	Source            int32   `json:"source"`            //来源 1-PC 2-H5 3-小程序 4-APP
	ActivityType      string  `json:"activityType"`      //活动类型
	ActivityId        int64   `json:"activityId"`        //活动ID
	DeleteStatus      int32   `json:"deleteStatus"`      //删除状态 0-正常 1-删除
	ExpireTime        string  `json:"expireTime"`        //过期时间
	CreateTime        string  `json:"createTime"`        //创建时间
	UpdateTime        string  `json:"updateTime"`        //更新时间
	PromotionMessage  string  `json:"promotionMessage"`  //促销活动信息
	ReduceAmount      int64   `json:"reduceAmount"`      //促销活动减去的金额，针对每个商品
	RealStock         int32   `json:"realStock"`         //商品的真实库存（剩余库存-锁定库存）
	Integration       int32   `json:"integration"`       //购买商品赠送积分
	Growth            int32   `json:"growth"`            //购买商品赠送成长值
	FulfillmentMode   string  `json:"fulfillmentMode"`   //履约模式：physical_delivery-实物发货 / digital_asset-提货卡
}

type CartItemDeleteReq struct {
	Ids []int64 `json:"ids"`
}

type CartItemListResp struct {
	Code    int64          `json:"code"`
	Message string         `json:"message"`
	Data    []CartListData `json:"data"`
}

type CartItemProductAttributeList struct {
	Id           int64  `json:"id"`           //主键id
	GroupId      int64  `json:"groupId"`      //属性分组ID
	Name         string `json:"name"`         //属性名称
	InputType    int32  `json:"inputType"`    //输入类型：1-手动输入，2-单选，3-多选
	ValueType    int32  `json:"valueType"`    //值类型：1-文本，2-数字，3-日期
	InputList    string `json:"inputList"`    //可选值列表，用逗号分隔
	Unit         string `json:"unit"`         //单位
	IsRequired   int32  `json:"isRequired"`   //是否必填
	IsSearchable int32  `json:"isSearchable"` //是否支持搜索
	IsShow       int32  `json:"isShow"`       //是否显示
	Sort         int32  `json:"sort"`         //排序
	CreateBy     int64  `json:"createBy"`     //创建人ID
	CreateTime   string `json:"createTime"`   //创建时间
	UpdateBy     int64  `json:"updateBy"`     //更新人ID
	UpdateTime   string `json:"updateTime"`   //更新时间
}

type CartItemReq struct {
	Id                int64   `json:"id,optional"`           //主键ID
	ProductId         int64   `json:"productId"`             //商品ID
	ProductSkuId      int64   `json:"productSkuId"`          //商品SKU ID
	Quantity          int32   `json:"quantity"`              //购买数量
	Price             float32 `json:"price"`                 //添加到购物车时的价格
	Selected          int32   `json:"selected,default=1"`    //是否选中 0-未选中 1-选中
	ProductName       string  `json:"productName"`           //商品名称
	ProductSubTitle   string  `json:"productSubTitle"`       //商品副标题
	ProductPic        string  `json:"productPic"`            //商品主图URL
	ProductSkuCode    string  `json:"productSkuCode"`        //商品SKU编码
	ProductSn         string  `json:"productSn"`             //商品货号
	ProductBrand      string  `json:"productBrand"`          //商品品牌
	ProductCategoryId int64   `json:"productCategoryId"`     //商品分类ID
	ProductAttr       string  `json:"productAttr"`           //商品销售属性JSON
	MemberNickname    string  `json:"memberNickname"`        //会员昵称
	Source            int32   `json:"source,default=4"`      //来源 1-PC 2-H5 3-小程序 4-APP
	ActivityType      string  `json:"activityType,optional"` //活动类型
	ActivityId        int64   `json:"activityId,optional"`   //活动ID
}

type CartItemResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type CartItemSkuStockList struct {
	Id                 int64   `json:"id"`                 //商品SpuId
	SpuId              int64   `json:"spuId"`              //商品SpuId
	Name               string  `json:"name"`               //SKU名称
	SkuCode            string  `json:"skuCode"`            //SKU编码
	MainPic            string  `json:"mainPic"`            //主图
	AlbumPics          string  `json:"albumPics"`          //图片集
	Price              float32 `json:"price"`              //价格
	PromotionPrice     float32 `json:"promotionPrice"`     //单品促销价格
	PromotionStartTime string  `json:"promotionStartTime"` //促销开始时间
	PromotionEndTime   string  `json:"promotionEndTime"`   //促销结束时间
	Stock              int32   `json:"stock"`              //库存
	LowStock           int32   `json:"lowStock"`           //预警库存
	SpecData           string  `json:"specData"`           //规格数据
	Weight             float32 `json:"weight"`             //重量(kg)
	PublishStatus      int32   `json:"publishStatus"`      //上架状态：0-下架，1-上架
	VerifyStatus       int32   `json:"verifyStatus"`       //审核状态：0-未审核，1-审核通过，2-审核不通过
	Sort               int32   `json:"sort"`               //排序
	Sales              int32   `json:"sales"`              //销量
	CreateBy           int64   `json:"createBy"`           //创建人ID
	CreateTime         string  `json:"createTime"`         //创建时间
	UpdateBy           int64   `json:"updateBy"`           //更新人ID
	UpdateTime         string  `json:"updateTime"`         //更新时间
}

type CartListData struct {
	Id                int64   `json:"id"`                //主键ID
	MemberId          int64   `json:"memberId"`          //会员ID
	ProductId         int64   `json:"productId"`         //商品ID
	ProductSkuId      int64   `json:"productSkuId"`      //商品SKU ID
	Quantity          int32   `json:"quantity"`          //购买数量
	Price             float32 `json:"price"`             //添加到购物车时的价格
	Selected          int32   `json:"selected"`          //是否选中 0-未选中 1-选中
	ProductName       string  `json:"productName"`       //商品名称
	ProductSubTitle   string  `json:"productSubTitle"`   //商品副标题
	ProductPic        string  `json:"productPic"`        //商品主图URL
	ProductSkuCode    string  `json:"productSkuCode"`    //商品SKU编码
	ProductSn         string  `json:"productSn"`         //商品货号
	ProductBrand      string  `json:"productBrand"`      //商品品牌
	ProductCategoryId int64   `json:"productCategoryId"` //商品分类ID
	ProductAttr       string  `json:"productAttr"`       //商品销售属性JSON
	MemberNickname    string  `json:"memberNickname"`    //会员昵称
	Source            int32   `json:"source"`            //来源 1-PC 2-H5 3-小程序 4-APP
	ActivityType      string  `json:"activityType"`      //活动类型
	ActivityId        int64   `json:"activityId"`        //活动ID
	ExpireTime        string  `json:"expireTime"`        //过期时间
	CreateTime        string  `json:"createTime"`        //创建时间
	UpdateTime        string  `json:"updateTime"`        //更新时间
}

type CartProductData struct {
	ProductAttributeList []CartItemProductAttributeList `json:"productAttributeList"`
	SkuStockList         []CartItemSkuStockList         `json:"skuStockList"`
}

type CartProductReq struct {
	ProductId int64 `path:"productId"`
}

type CartProductResp struct {
	Code    int64           `json:"code"`
	Message string          `json:"message"`
	Data    CartProductData `json:"data"`
}

type CartPromotionItemList struct {
	Id                int64   `json:"id"`
	ProductId         int64   `json:"productId"`
	ProductSkuId      int64   `json:"productSkuId"`
	MemberId          int64   `json:"memberId"`
	Quantity          int32   `json:"quantity"`          // 购买数量
	Price             float32 `json:"price"`             // 添加到购物车的价格
	ProductPic        string  `json:"productPic"`        // 商品主图
	ProductName       string  `json:"productName"`       // 商品名称
	ProductSubTitle   string  `json:"productSubTitle"`   // 商品副标题（卖点）
	ProductSkuCode    string  `json:"productSkuCode"`    // 商品sku条码
	MemberNickname    string  `json:"memberNickname"`    // 会员昵称
	CreateDate        string  `json:"createDate"`        // 创建时间
	ModifyDate        string  `json:"modifyDate"`        // 修改时间
	DeleteStatus      int32   `json:"deleteStatus"`      // 是否删除
	ProductCategoryId int64   `json:"productCategoryId"` // 商品分类
	ProductBrand      string  `json:"productBrand"`
	ProductSn         string  `json:"productSn"`
	ProductAttr       string  `json:"productAttr"`      // 商品销售属性:[{"key":"颜色","value":"颜色"},{"key":"容量","value":"4G"}]
	PromotionMessage  string  `json:"promotionMessage"` //促销活动信息
	ReduceAmount      int64   `json:"reduceAmount"`     //促销活动减去的金额，针对每个商品
	RealStock         int32   `json:"realStock"`        //商品的真实库存（剩余库存-锁定库存）
	Integration       int32   `json:"integration"`      //购买商品赠送积分
	Growth            int32   `json:"growth"`           //购买商品赠送成长值
	FulfillmentMode   string  `json:"fulfillmentMode"`  //履约模式：physical_delivery-实物发货 / digital_asset-提货卡
}

type CartValidateReq struct {
	Ids []int64 `json:"ids"` // 购物车项ID列表（前端传已选商品的购物车ID）
}

type CartValidateResp struct {
	Code       int64                `json:"code"`
	Message    string               `json:"message"`
	RequestId  string               `json:"requestId"`  // MEDIUM-7: 请求链路追踪ID
	ServerTime int64                `json:"serverTime"` // MEDIUM-7: 服务器时间戳（毫秒）
	Data       []CartValidateResult `json:"data"`
}

type CartValidateResult struct {
	Id           int64  `json:"id"`           // 购物车项ID
	Valid        bool   `json:"valid"`        // 是否有效
	ErrorCode    string `json:"errorCode"`    // 错误码，无效时返回具体错误码
	ErrorMessage string `json:"errorMessage"` // 错误信息
	TraceId      string `json:"traceId"`      // MEDIUM-7: 该项校验的链路ID
}

type CollectionDeleteReq struct {
	Ids []string `form:"ids"`
}

type CollectionList struct {
	Id              string `json:"id"`              // 编号
	MemberId        int64  `json:"memberId"`        // 会员id
	MemberNickName  string `json:"memberNickName"`  // 会员姓名
	MemberIcon      string `json:"memberIcon"`      // 会员头像
	ProductId       int64  `json:"productId"`       // 商品id
	ProductName     string `json:"productName"`     // 商品名称
	ProductPic      string `json:"productPic"`      // 商品图片
	ProductSubTitle string `json:"productSubTitle"` // 商品标题
	ProductPrice    int64  `json:"productPrice"`    // 商品价格
	CreateTime      string `json:"createTime"`      // 浏览时间
}

type CollectionListResp struct {
	Code    int64            `json:"code"`
	Message string           `json:"message"`
	Data    []CollectionList `json:"data"` //收藏列表
}

type CollectionReq struct {
	ProductId       int64  `json:"productId"`       // 商品id
	ProductName     string `json:"productName"`     // 商品名称
	ProductPic      string `json:"productPic"`      // 商品图片
	ProductSubTitle string `json:"productSubTitle"` // 商品标题
	ProductPrice    int64  `json:"productPrice"`    // 商品价格
}

type CollectionResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type CommentListItem struct {
	Id               string `json:"id"`
	ProductId        int64  `json:"productId"`
	MemberId         int64  `json:"memberId"`
	MemberNickName   string `json:"memberNickName"`
	MemberIcon       string `json:"memberIcon"`
	Star             int32  `json:"star"`
	Content          string `json:"content"`
	Pics             string `json:"pics"`
	ProductAttribute string `json:"productAttribute"`
	ShowStatus       int32  `json:"showStatus"`
	ReplayCount      int32  `json:"replayCount"`
	MemberIp         string `json:"memberIp"`
	CreateTime       string `json:"createTime"`
}

type CommentReplayItem struct {
	Id             string `json:"id"`
	CommentId      string `json:"commentId"`
	Type           int32  `json:"type"`
	MemberNickName string `json:"memberNickName"`
	MemberIcon     string `json:"memberIcon"`
	Content        string `json:"content"`
	CreateTime     string `json:"createTime"`
}

type ConfirmReceiveOrderReq struct {
	OrderId int64 `form:"orderId"`
}

type ConfirmReceiveOrderResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type CouponData struct {
	Id            int64   `json:"id"`                     //优惠券ID
	TypeId        int64   `json:"typeId"`                 //优惠券类型ID
	Name          string  `json:"name"`                   //优惠券名称
	Code          string  `json:"code"`                   //优惠券码
	Amount        float32 `json:"amount"`                 //优惠金额/折扣率
	MinAmount     float32 `json:"minAmount"`              //最低使用金额
	StartTime     string  `json:"startTime"`              //生效时间
	EndTime       string  `json:"endTime"`                //失效时间
	PerLimit      int32   `json:"perLimit"`               //每人限领数量
	Status        int32   `json:"status"`                 //状态：0-未开始，1-进行中，2-已结束，3-已取消
	Description   string  `json:"description"`            //使用说明
	ScopeType     int32   `json:"scopeType"`              //范围类型：0-全场，1-分类，2-商品
	ReceiveStatus int32   `json:"receiveStatus"`          //领取状态：0-可领取，1-已领取，2-已领完，3-未开始，4-已过期
	TotalCount    int32   `json:"totalCount"`             //发放总量
	ReceivedCount int32   `json:"receivedCount"`          //已领取数量
	DisableReason string  `json:"disableReason,optional"` //不可用原因
}

type CouponListByCartData struct {
	EnableList  interface{} `json:"enableList"`
	DisableList interface{} `json:"disableList"`
}

type CouponListByCartReq struct {
	Type int32 `form:"type"` // 使用状态-使用可用:0->不可用；1->可用
}

type CouponListByCartResp struct {
	Code    int64                `json:"code"`
	Message string               `json:"message"`
	Data    CouponListByCartData `json:"data"`
}

type Data struct {
	AdvertiseList      []AdvertiseList         `json:"advertiseList"`      //获取首页广告
	BrandList          []IndexBrandData        `json:"brandList"`          //获取推荐品牌
	HomeFlashPromotion HomeFlashPromotion      `json:"homeFlashPromotion"` //获取秒杀信息
	NewProductList     []IndexProductData      `json:"newProductList"`     //获取新品推荐
	HotProductList     []IndexProductData      `json:"hotProductList"`     //获取人气推荐
	SubjectList        []SubjectList           `json:"subjectList"`        //获取推荐专题
	PreferredAreaList  []PreferredAreaListData `json:"preferredAreaList"`  //获取优选专区
}

type DeleteAddressReq struct {
	Ids []int64 `form:"ids"`
}

type DeleteAttentionReq struct {
	BrandIds []int64 `form:"brandIds"`
}

type DeleteOrderReq struct {
	OrderIds []int64 `form:"orderIds"`
}

type DeleteOrderResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type DirectOrderItemReq struct {
	ProductId    int64 `json:"productId"`
	ProductSkuId int64 `json:"productSkuId"`
	Quantity     int32 `json:"quantity"`
}

type DrawActivityLandingData struct {
	ActivityId                  int64                  `json:"activityId"`                  //活动ID
	ActivityCode                string                 `json:"activityCode"`                //活动编码
	Name                        string                 `json:"name"`                        //活动名称
	RuleSummary                 string                 `json:"ruleSummary"`                 //规则摘要
	ParticipantConditionSummary string                 `json:"participantConditionSummary"` //参与条件摘要
	ConsumeRuleSummary          string                 `json:"consumeRuleSummary"`          //消耗规则摘要
	ConsumeType                 string                 `json:"consumeType"`                 //消耗类型:points-积分,free-免费
	ConsumeAmount               int32                  `json:"consumeAmount"`               //每次消耗积分数
	ProbabilityRule             string                 `json:"probabilityRule"`             //概率说明
	ComplianceRuleSummary       string                 `json:"complianceRuleSummary"`       //合规摘要
	CirculationLimitSummary     string                 `json:"circulationLimitSummary"`     //流转限制摘要
	StartTime                   string                 `json:"startTime"`                   //开始时间
	EndTime                     string                 `json:"endTime"`                     //结束时间
	RealNameRequired            int32                  `json:"realNameRequired"`            //是否实名要求
	Eligibility                 DrawEligibilitySummary `json:"eligibility"`                 //资格摘要
	Identity                    DrawIdentitySummary    `json:"identity"`                    //实名摘要
	CardPreviews                []DrawCardPreview      `json:"cardPreviews"`                //卡片预览
	Pools                       []DrawPoolPreview      `json:"pools"`                       //卡池预览
	RecentWins                  []DrawRecentWin        `json:"recentWins"`                  //最近中奖
	MyRecords                   []DrawMemberRecord     `json:"myRecords"`                   //我的记录
}

type DrawActivityLandingReq struct {
	ActivityId  int64  `form:"activityId"`           //活动ID
	Channel     string `form:"channel,optional"`     //渠道
	EntrySource string `form:"entrySource,optional"` //入口来源
}

type DrawActivityLandingResp struct {
	Code    string                  `json:"code"`
	Message string                  `json:"message"`
	Data    DrawActivityLandingData `json:"data"`
}

type DrawCardPreview struct {
	TemplateId    int64   `json:"templateId"`    //模板ID
	TemplateCode  string  `json:"templateCode"`  //模板编码
	TemplateName  string  `json:"templateName"`  //模板名称
	CardFaceImage string  `json:"cardFaceImage"` //卡面资源
	Rarity        string  `json:"rarity"`        //稀有度
	DisplayCopy   string  `json:"displayCopy"`   //展示文案
	SlotIndex     int32   `json:"slotIndex"`     //格位序号(1-5)，转盘定位用
	Probability   float64 `json:"probability"`   //格位概率(0-1)，转盘扇形渲染用
}

type DrawEligibilitySummary struct {
	EligibilityStatus     string `json:"eligibilityStatus"`     //资格状态
	EligibilityCode       string `json:"eligibilityCode"`       //资格编码
	EligibilityMessage    string `json:"eligibilityMessage"`    //资格提示
	NextAction            string `json:"nextAction"`            //下一步动作
	RemainingLotteryTimes int32  `json:"remainingLotteryTimes"` //剩余抽奖次数
}

type DrawIdentitySummary struct {
	RealNameStatus     string `json:"realNameStatus"`     //实名状态
	RealNameStatusText string `json:"realNameStatusText"` //实名状态文案
	RealNameMasked     string `json:"realNameMasked"`     //脱敏实名
	CredentialRef      string `json:"credentialRef"`      //凭证引用
	VerifiedAt         string `json:"verifiedAt"`         //实名时间
}

type DrawMemberRecord struct {
	Id                 int64  `json:"id"`                 //参与记录ID
	ActivityId         int64  `json:"activityId"`         //活动ID
	RequestId          string `json:"requestId"`          //请求ID
	ResultType         string `json:"resultType"`         //结果类型
	ResultStatus       string `json:"resultStatus"`       //结果状态
	ResultStatusText   string `json:"resultStatusText"`   //结果文案
	FailureCode        string `json:"failureCode"`        //失败码
	FailureReason      string `json:"failureReason"`      //失败原因
	PoolId             int64  `json:"poolId"`             //卡池ID
	TemplateId         int64  `json:"templateId"`         //模板ID
	TemplateName       string `json:"templateName"`       //模板名称
	Rarity             string `json:"rarity"`             //稀有度
	ConsumeAmount      int32  `json:"consumeAmount"`      //消耗次数
	CurrencyBefore int32  `json:"currencyBefore"` //扣减前货币数量（lottery_times 或 points）
	CurrencyAfter  int32  `json:"currencyAfter"`  //扣减后货币数量
	AssetInstanceId    int64  `json:"assetInstanceId"`    //资产实例ID
	AssetNo            string `json:"assetNo"`            //资产编号
	AssetStatus        string `json:"assetStatus"`        //资产状态
	AssetStatusText    string `json:"assetStatusText"`    //资产状态文案
	AssetCreatedAt     string `json:"assetCreatedAt"`     //资产创建时间
	CreateTime         string `json:"createTime"`         //参与时间
}

type DrawPoolPreview struct {
	PoolId          int64             `json:"poolId"`          //卡池ID
	PoolName        string            `json:"poolName"`        //卡池名称
	ProbabilityRule string            `json:"probabilityRule"` //概率说明
	Cards           []DrawCardPreview `json:"cards"`           //卡片预览
}

type DrawRecentWin struct {
	RecordId         int64  `json:"recordId"`         //记录ID
	MemberId         int64  `json:"memberId"`         //会员ID
	MemberNameMasked string `json:"memberNameMasked"` //脱敏会员昵称
	ResultStatus     string `json:"resultStatus"`     //结果状态
	ResultStatusText string `json:"resultStatusText"` //结果文案
	TemplateName     string `json:"templateName"`     //模板名称
	Rarity           string `json:"rarity"`           //稀有度
	CreateTime       string `json:"createTime"`       //创建时间
}

type GenerateConfirmOrderReq struct {
	Ids        []int64            `json:"ids,optional"`
	DirectItem DirectOrderItemReq `json:"directItem,optional"`
}

type GenerateConfirmOrderResp struct {
	Code    int64            `json:"code"`
	Message string           `json:"message"`
	Data    OrderDetailModel `json:"data"`
}

type GenerateOrderData struct {
	Id                int64  `json:"id"`                // 订单id
	OrderSn           string `json:"orderSn"`           // 订单编号（Story 5.4 新增）
	MemberId          int64  `json:"memberId"`          // 会员id
	MemberUsername    string `json:"memberUserName"`    // 用户帐号
	TotalAmount       int64  `json:"totalAmount"`       // 订单总金额
	PayAmount         int64  `json:"payAmount"`         // 应付金额（实际支付金额）
	FreightAmount     int64  `json:"freightAmount"`     // 运费金额
	PromotionAmount   int64  `json:"promotionAmount"`   // 促销优化金额（促销价、满减、阶梯价）
	IntegrationAmount int64  `json:"integrationAmount"` // 积分抵扣金额
	CouponAmount      int64  `json:"couponAmount"`      // 优惠券抵扣金额
	DiscountAmount    int64  `json:"discountAmount"`    // 管理员后台调整订单使用的折扣金额
	PayType           int32  `json:"payType"`           // 支付方式：0->未支付；1->支付宝；2->微信
	SourceType        int32  `json:"sourceType"`        // 订单来源：0->PC订单；1->app订单
	Status            int32  `json:"status"`            // 订单状态：0->待付款；1->待发货；2->已发货；3->已完成；4->已关闭；5->无效订单
	OrderType         int32  `json:"orderType"`         // 订单类型：0->正常订单；1->秒杀订单
	Integration       int32  `json:"integration"`       // 可以获得的积分
	Growth            int32  `json:"growth"`            // 可以活动的成长值
	PromotionInfo     string `json:"promotionInfo"`     // 活动信息
	Note              string `json:"note"`              // 订单备注
	UseIntegration    int32  `json:"useIntegration"`    // 下单时使用的积分
}

type GenerateOrderReq struct {
	CartIds                []int64            `json:"cartIds,optional"` //购物车id
	DirectItem             DirectOrderItemReq `json:"directItem,optional"`
	CouponId               int64              `json:"couponId"`                //优惠券id
	MemberReceiveAddressId int64              `json:"memberReceiveAddressId"`  //
	PayType                int32              `json:"payType"`                 //支付方式
	UseIntegration         int32              `json:"useIntegration"`          //使用的积分
	IdempotencyKey         string             `json:"idempotencyKey,optional"` //幂等键，格式：{userId}:{timestamp}:{hash}（Story 5.4 新增）
}

type GenerateOrderResp struct {
	Code    int64             `json:"code"`
	Message string            `json:"message"`
	Data    GenerateOrderData `json:"data"`
}

type HomeFlashPromotion struct {
	StartTime     string             `json:"startTime"`
	EndTime       string             `json:"endTime"`
	NextStartTime string             `json:"nextStartTime"`
	NextEndTime   string             `json:"nextEndTime"`
	ProductList   []IndexProductData `json:"productList"`
}

type HomeReq struct {
	AdvertiseType       string `form:"advertiseType,default=app"`     // app或者pc
	BrandNumber         int32  `form:"brandNumber,default=6"`         //
	HomeFlashNumber     int32  `form:"homeFlashNumber,default=4"`     //
	NewProductNumber    int32  `form:"newProductNumber,default=4"`    //
	HotProductNumber    int32  `form:"hotProductNumber,default=4"`    //
	SubjectNumber       int32  `form:"subjectNumber,default=4"`       //
	PreferredAreaNumber int32  `form:"preferredAreaNumber,default=4"` //
}

type HomeResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
	Data    Data   `json:"data"`
}

type IndexBrandData struct {
	Id                  int64  `json:"id"`                  //
	Name                string `json:"name"`                //品牌名称
	Logo                string `json:"logo"`                //品牌logo
	BigPic              string `json:"bigPic"`              //专区大图
	Description         string `json:"description"`         //描述
	FirstLetter         string `json:"firstLetter"`         //首字母
	Sort                int32  `json:"sort"`                //排序
	RecommendStatus     int32  `json:"recommendStatus"`     //推荐状态
	ProductCount        int32  `json:"productCount"`        //产品数量
	ProductCommentCount int32  `json:"productCommentCount"` //产品评论数量
}

type IndexProductData struct {
	Id                  int64   `json:"id"`                  //商品SpuId
	Name                string  `json:"name"`                //商品名称
	ProductSn           string  `json:"productSn"`           //商品货号
	CategoryId          int64   `json:"categoryId"`          //商品分类ID
	CategoryIds         string  `json:"categoryIds"`         //商品分类ID集合
	CategoryName        string  `json:"categoryName"`        //商品分类名称
	BrandId             int64   `json:"brandId"`             //品牌ID
	BrandName           string  `json:"brandName"`           //品牌名称
	Unit                string  `json:"unit"`                //单位
	Weight              float32 `json:"weight"`              //重量(kg)
	Keywords            string  `json:"keywords"`            //关键词
	AlbumPics           string  `json:"albumPics"`           //画册图片，最多8张，以逗号分割
	MainPic             string  `json:"mainPic"`             //主图
	Price               string  `json:"price"`               //价格
	PriceRange          string  `json:"priceRange"`          //价格区间
	PublishStatus       int32   `json:"publishStatus"`       //上架状态：0-下架，1-上架
	NewStatus           int32   `json:"newStatus"`           //新品状态:0->不是新品；1->新品
	RecommendStatus     int32   `json:"recommendStatus"`     //推荐状态；0->不推荐；1->推荐
	VerifyStatus        int32   `json:"verifyStatus"`        //审核状态：0->未审核；1->审核通过
	PreviewStatus       int32   `json:"previewStatus"`       //是否为预告商品：0->不是；1->是
	Sort                int32   `json:"sort"`                //排序
	NewStatusSort       int32   `json:"newStatusSort"`       //新品排序
	RecommendStatusSort int32   `json:"recommendStatusSort"` //推荐排序
	Sales               int32   `json:"sales"`               //销量
	Stock               int32   `json:"stock"`               //库存
	LowStock            int32   `json:"lowStock"`            //预警库存
	PromotionType       int32   `json:"promotionType"`       //促销类型：0->没有促销使用原价;1->使用促销价；2->使用会员价；3->使用阶梯价格；4->使用满减价格；5->秒杀
	SubTitle            string  `json:"subTitle"`            //副标题
	DetailHtml          string  `json:"detailHtml"`          //产品详情网页内容
	DetailMobileHtml    string  `json:"detailMobileHtml"`    //移动端网页详情
}

type InfoResp struct {
	Code    int64      `json:"code"`
	Message string     `json:"message"`
	Data    MemberData `json:"data"`
}

type IntegrationConsumeSetting struct {
	Id                 int64 `json:"id"`
	DeductionPerAmount int32 `json:"deductionPerAmount"`
	MaxPercentPerOrder int32 `json:"maxPercentPerOrder"`
	UseUnit            int32 `json:"useUnit"`
	CouponStatus       int32 `json:"couponStatus"`
}

type ListAttentionData struct {
	Id             string `json:"id"`
	MemberId       int64  `json:"memberId"`       // 会员id
	MemberNickName string `json:"memberNickName"` // 会员姓名
	MemberIcon     string `json:"memberIcon"`     // 会员头像
	BrandId        int64  `json:"brandId"`        // 品牌id
	BrandName      string `json:"brandName"`      // 品牌名称
	BrandLogo      string `json:"brandLogo"`      // 品牌Logo
	BrandCity      string `json:"brandCity"`      // 品牌所在城市
	CreateTime     string `json:"createTime"`     // 关注时间
}

type ListAttentionResp struct {
	Data    []ListAttentionData `json:"data"`
	Success bool                `json:"success"`
	Code    int64               `json:"code"`
	Message string              `json:"message"`
}

type ListCouponReq struct {
	UseStatus int32 `form:"useStatus,default=3"` // 使用状态：0->未使用；1->已使用；2->已过期
}

type ListCouponResp struct {
	Code    int64         `json:"code"`
	Message string        `json:"message"`
	Data    []*CouponData `json:"data"`
}

// Story 3.1.1: 手机号验证码登录注册合并接口类型
//
// 旧的 LoginReq/LoginResp/RegisterReq/RegisterResp（手机号+密码）已下线。
// LoginData 改造为本接口的通用 token 数据结构，并新增 IsNewUser 字段，
// 客户端可据此向新用户展示欢迎语。

type LoginData struct {
	Token     string `json:"token"`
	TokenHead string `json:"tokenHead"`
	IsNewUser bool   `json:"isNewUser,omitempty"`
}

// SmsLoginReq POST /api/member/auth/login 请求体
type SmsLoginReq struct {
	Mobile string `json:"mobile"`           //手机号
	Code   string `json:"code"`             //6 位短信验证码
	Source int32  `json:"source,default=1"` //登录来源：0-PC，1-APP，2-小程序
}

// SmsLoginResp POST /api/member/auth/login 响应体
type SmsLoginResp struct {
	Code    int64     `json:"code"`
	Message string    `json:"message"`
	Data    LoginData `json:"data"`
}

// SendSmsCodeReq POST /api/member/auth/sms/send 请求体
type SendSmsCodeReq struct {
	Mobile string `json:"mobile"`          //手机号
	Scene  int32  `json:"scene,default=1"` //1=member_login，预留其他场景
}

// SendSmsCodeData 短信验证码响应数据（绝不包含验证码原文）
type SendSmsCodeData struct {
	ExpireSeconds int32 `json:"expireSeconds"`
}

// SendSmsCodeResp POST /api/member/auth/sms/send 响应体
type SendSmsCodeResp struct {
	Code    int64           `json:"code"`
	Message string          `json:"message"`
	Data    SendSmsCodeData `json:"data"`
}

type LogisticsData struct {
	DeliveryCompany string          `json:"deliveryCompany"` // 物流公司
	DeliveryNo      string          `json:"deliveryNo"`      // 物流单号
	CurrentStatus   string          `json:"currentStatus"`   // 当前状态描述
	LogisticsNodes  []LogisticsNode `json:"logisticsNodes"`  // 轨迹节点列表
}

type LogisticsNode struct {
	Status      string `json:"status"`      // completed/pending/current/error
	Description string `json:"description"` // 状态描述
	Time        string `json:"time"`        // 时间
}

type MemberData struct {
	Id                 int64   `json:"id"`                 //主键ID
	MemberId           int64   `json:"memberId"`           //会员ID
	LevelId            int64   `json:"levelId"`            //等级ID
	Nickname           string  `json:"nickname"`           //昵称
	Mobile             string  `json:"mobile"`             //手机号码
	Source             int32   `json:"source"`             //注册来源：0-PC，1-APP，2-小程序
	Avatar             string  `json:"avatar"`             //头像
	Signature          string  `json:"signature"`          //个性签名
	Gender             int32   `json:"gender"`             //性别：0-未知，1-男，2-女
	Birthday           string  `json:"birthday"`           //生日
	GrowthPoint        int32   `json:"growthPoint"`        //成长值
	Points             int32   `json:"points"`             //积分
	TotalPoints        int32   `json:"totalPoints"`        //累计获得积分
	SpendAmount        float64 `json:"spendAmount"`        //累计消费金额
	OrderCount         int32   `json:"orderCount"`         //订单数
	CouponCount        int32   `json:"couponCount"`        //优惠券数量
	CommentCount       int32   `json:"commentCount"`       //评价数
	ReturnCount        int32   `json:"returnCount"`        //退货数
	LotteryTimes       int32   `json:"lotteryTimes"`       //剩余抽奖次数
	LastLogin          string  `json:"lastLogin"`          //最后登录
	RealNameStatus     string  `json:"realNameStatus"`     //实名状态
	RealNameStatusText string  `json:"realNameStatusText"` //实名状态文案
	RealNameMasked     string  `json:"realNameMasked"`     //脱敏实名
	CredentialRef      string  `json:"credentialRef"`      //凭证引用
	VerifiedAt         string  `json:"verifiedAt"`         //实名时间
}

type MemberPriceList struct {
	Id              int64  `json:"id"`              //
	ProductId       int64  `json:"productId"`       //商品id
	MemberLevelId   int64  `json:"memberLevelId"`   //会员等级id
	MemberPrice     int64  `json:"memberPrice"`     //会员价格
	MemberLevelName string `json:"memberLevelName"` //会员等级名称
}

type MemberReceiveAddressList struct {
	Id            int64  `json:"id"`            //主键ID
	MemberId      int64  `json:"memberId"`      //会员ID
	ReceiverName  string `json:"receiverName"`  //收货人姓名
	ReceiverPhone string `json:"receiverPhone"` //收货人电话
	Province      string `json:"province"`      //省份
	City          string `json:"city"`          //城市
	District      string `json:"district"`      //区县
	DetailAddress string `json:"detailAddress"` //详细地址
	PostalCode    string `json:"postalCode"`    //邮政编码
	Tag           string `json:"tag"`           //地址标签：家、公司等
	IsDefault     int32  `json:"isDefault"`     //是否默认地址
}

type MemberResp struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type OrderDetailModel struct {
	CartPromotionItemList     []CartPromotionItemList    `json:"cartPromotionItemList"`
	MemberReceiveAddressList  []MemberReceiveAddressList `json:"memberReceiveAddressList"`
	CouponHistoryDetailList   interface{}                `json:"couponHistoryDetailList"`
	IntegrationConsumeSetting IntegrationConsumeSetting  `json:"integrationConsumeSetting"`
	MemberIntegration         int64                      `json:"memberIntegration"`
	CalcAmount                CalcAmount                 `json:"calcAmount"`
}

type OrderDetailReq struct {
	OrderId int64 `form:"orderId"`
}

type OrderDetailResp struct {
	Code    int64          `json:"code"`
	Message string         `json:"message"`
	Data    QueryOrderData `json:"data"`
}

type OrderItemData struct {
	Id              int64   `json:"id"`              //
	OrderId         int64   `json:"orderId"`         //订单ID
	OrderNo         string  `json:"orderNo"`         //订单编号
	OrderItemStatus int32   `json:"orderItemStatus"` //订单商品状态：1-正常,2-退货申请中,3-已退货,4-已拒绝
	SkuId           int64   `json:"skuId"`           //商品SKU ID
	SkuName         string  `json:"skuName"`         //商品名称
	SkuPic          string  `json:"skuPic"`          //商品图片
	SkuPrice        float64 `json:"skuPrice"`        //商品单价
	SkuQuantity     int32   `json:"skuQuantity"`     //商品数量
	SpecData        string  `json:"specData"`        //规格数据
	SkuTotalAmount  float64 `json:"skuTotalAmount"`  //商品总金额
	PromotionAmount float64 `json:"promotionAmount"` //促销分摊金额
	CouponAmount    float64 `json:"couponAmount"`    //优惠券分摊金额
	PointsAmount    float64 `json:"pointsAmount"`    //积分分摊金额
	DiscountAmount  float64 `json:"discountAmount"`  //优惠分摊金额
	RealAmount      float64 `json:"realAmount"`      //实付金额
	CreateTime      string  `json:"createTime"`      //创建时间
	IsDeleted       int32   `json:"isDeleted"`       //是否删除
}

type OrderListReq struct {
	Current  int32 `form:"current,default=1"`
	PageSize int32 `form:"pageSize,default=5"`
	Status   int32 `form:"status,default=6"` // 订单状态：0->待付款；1->待发货；2->已发货；3->已完成；4->已关闭；5->无效订单
}

type OrderListResp struct {
	Code     int64             `json:"code"`
	Message  string            `json:"message"`
	PageNum  int64             `json:"pageNum"`
	PageSize int64             `json:"pageSize"`
	Total    int64             `json:"total"`
	Data     []*QueryOrderData `json:"data"`
}

type OrderOperationLogItem struct {
	Id            int64  `json:"id"`
	OperationType int    `json:"operationType"` // 操作类型：1=创建,2=支付,3=发货,4=确认收货,5=取消,6=退款
	OperatorType  int    `json:"operatorType"`  // 操作人类型：1=用户,2=系统,3=管理员
	OperatorNote  string `json:"operatorNote"`  // 操作备注
	CreateTime    string `json:"createTime"`    // 操作时间
}

type OrderPayQueryReq struct {
	OrderId int64 `json:"orderId"`
}

type OrderPayQueryResp struct {
	Code                 int64    `json:"code"`
	Message              string   `json:"message"`
	Data                 string   `json:"data"`
	OrderStatus          int64    `json:"orderStatus"`          // 0=待支付 1=已支付 2=已取消
	PayStatus            int64    `json:"payStatus"`            // 0=未支付 1=已支付
	ExpireTime           int64    `json:"expireTime"`           // 剩余支付秒数
	ConsistencyStage     int      `json:"consistencyStage"`     // 一致性阶段
	ConsistencyStageText string   `json:"consistencyStageText"` // 一致性阶段文案
	ConsistencyResult    int      `json:"consistencyResult"`    // 一致性结果
	ConsistencyMessage   string   `json:"consistencyMessage"`   // 一致性提示
	LastConsistencyAt    string   `json:"lastConsistencyAt"`    // 最近一致性时间
	PendingActions       int      `json:"pendingActions"`       // 待处理动作位掩码
	PendingActionsText   []string `json:"pendingActionsText"`   // 待处理动作文本
	AftersaleStatus      int32    `json:"aftersaleStatus"`      // 售后状态
	AftersaleStatusText  string   `json:"aftersaleStatusText"`  // 售后状态文本
	ReturnId             int64    `json:"returnId"`             // 售后单ID
	ReturnNo             string   `json:"returnNo"`             // 售后单号
}

type OrderPayReq struct {
	OrderId int64  `json:"orderId"`
	PayType int64  `json:"payType"` // 支付方式：1=支付宝，2=微信
	Remark  string `json:"remark,optional"`
}

type OrderPayResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
	Data    string `json:"data"` // 支付唤起参数（支付宝orderInfo字符串 / 微信mweb_url）
}

type ParticipateDrawData struct {
	Record      DrawMemberRecord       `json:"record"`      //参与结果
	Eligibility DrawEligibilitySummary `json:"eligibility"` //资格结果
}

type ParticipateDrawReq struct {
	ActivityId  int64  `json:"activityId"`           //活动ID
	RequestId   string `json:"requestId"`            //请求ID
	Channel     string `json:"channel,optional"`     //渠道
	EntrySource string `json:"entrySource,optional"` //入口来源
}

type ParticipateDrawResp struct {
	Code    string              `json:"code"`
	Message string              `json:"message"`
	Data    ParticipateDrawData `json:"data"`
}

type PreferredAreaListData struct {
	Id         int64  `json:"id"`         //专区id
	Name       string `json:"name"`       //专区名称
	SubTitle   string `json:"subTitle"`   //子标题
	Pic        string `json:"pic"`        //展示图片
	Sort       int32  `json:"sort"`       //排序
	ShowStatus int32  `json:"showStatus"` //显示状态：0->不显示；1->显示
}

type PreviewDrawEligibilityReq struct {
	ActivityId  int64  `form:"activityId"`           //活动ID
	Channel     string `form:"channel,optional"`     //渠道
	EntrySource string `form:"entrySource,optional"` //入口来源
}

type PreviewDrawEligibilityResp struct {
	Code    string                 `json:"code"`
	Message string                 `json:"message"`
	Data    DrawEligibilitySummary `json:"data"`
}

type PriceBreakdown struct {
	OrderAmount     float64 `json:"orderAmount"`     // 商品总额
	FreightAmount   float64 `json:"freightAmount"`   // 运费
	PromotionAmount float64 `json:"promotionAmount"` // 促销优惠
	CouponAmount    float64 `json:"couponAmount"`    // 优惠券优惠
	PointsAmount    float64 `json:"pointsAmount"`    // 积分抵扣
	DiscountAmount  float64 `json:"discountAmount"`  // 其他优惠
	PayAmount       float64 `json:"payAmount"`       // 实付金额
}

type ProductAttributeList struct {
	Id           int64  `json:"id"`           //主键id
	GroupId      int64  `json:"groupId"`      //属性分组ID
	Name         string `json:"name"`         //属性名称
	InputType    int32  `json:"inputType"`    //输入类型：1-手动输入，2-单选，3-多选
	ValueType    int32  `json:"valueType"`    //值类型：1-文本，2-数字，3-日期
	InputList    string `json:"inputList"`    //可选值列表，用逗号分隔
	Unit         string `json:"unit"`         //单位
	IsRequired   int32  `json:"isRequired"`   //是否必填
	IsSearchable int32  `json:"isSearchable"` //是否支持搜索
	IsShow       int32  `json:"isShow"`       //是否显示
	Sort         int32  `json:"sort"`         //排序
}

type ProductAttributeValueList struct {
	Id          int64  `json:"id"`          //主键id
	SpuId       int64  `json:"spuId"`       //商品SPU ID
	AttributeId int64  `json:"attributeId"` //属性ID
	Value       string `json:"value"`       //属性值
}

type ProductCateData struct {
	Id       int64             `json:"id"`
	Key      string            `json:"key"`
	Name     string            `json:"name"`
	Label    string            `json:"label"`
	ImageUrl string            `json:"imageUrl"`
	Children []ProductCateData `json:"children"`
}

type ProductData struct {
	Id                  int64   `json:"id"`                  //商品SpuId
	Name                string  `json:"name"`                //商品名称
	ProductSn           string  `json:"productSn"`           //商品货号
	CategoryId          int64   `json:"categoryId"`          //商品分类ID
	CategoryIds         string  `json:"categoryIds"`         //商品分类ID集合
	CategoryName        string  `json:"categoryName"`        //商品分类名称
	BrandId             int64   `json:"brandId"`             //品牌ID
	BrandName           string  `json:"brandName"`           //品牌名称
	Unit                string  `json:"unit"`                //单位
	Weight              float32 `json:"weight"`              //重量(kg)
	Keywords            string  `json:"keywords"`            //关键词
	AlbumPics           string  `json:"albumPics"`           //画册图片，最多8张，以逗号分割
	MainPic             string  `json:"mainPic"`             //主图
	Price               string  `json:"price"`               //价格
	PriceRange          string  `json:"priceRange"`          //价格区间
	PublishStatus       int32   `json:"publishStatus"`       //上架状态：0-下架，1-上架
	NewStatus           int32   `json:"newStatus"`           //新品状态:0->不是新品；1->新品
	RecommendStatus     int32   `json:"recommendStatus"`     //推荐状态；0->不推荐；1->推荐
	VerifyStatus        int32   `json:"verifyStatus"`        //审核状态：0->未审核；1->审核通过
	PreviewStatus       int32   `json:"previewStatus"`       //是否为预告商品：0->不是；1->是
	Sort                int32   `json:"sort"`                //排序
	NewStatusSort       int32   `json:"newStatusSort"`       //新品排序
	RecommendStatusSort int32   `json:"recommendStatusSort"` //推荐排序
	Sales               int32   `json:"sales"`               //销量
	Stock               int32   `json:"stock"`               //库存
	LowStock            int32   `json:"lowStock"`            //预警库存
	PromotionType       int32   `json:"promotionType"`       //促销类型：0->没有促销使用原价;1->使用促销价；2->使用会员价；3->使用阶梯价格；4->使用满减价格；5->秒杀
	SubTitle            string  `json:"subTitle"`            //副标题
	DetailHtml          string  `json:"detailHtml"`          //产品详情网页内容
	DetailMobileHtml    string  `json:"detailMobileHtml"`    //移动端网页详情
}

type ProductDetailData struct {
	ProductData        ProductData                 `json:"product"`                   //商品信息
	BrandData          BrandData                   `json:"brand"`                     //商品品牌
	AttributeList      []ProductAttributeList      `json:"productAttributeList"`      //商品属性
	AttributeValueList []ProductAttributeValueList `json:"productAttributeValueList"` //商品属性值
	SkuList            []SkuStockList              `json:"skuStockList"`              //商品SKU库存信息
	LadderList         []ProductLadderList         `json:"productLadderList"`         //商品阶梯价格
	FullList           []ProductFullReductionList  `json:"productFullReductionList"`  //商品满减信息
	MemberPriceList    []MemberPriceList           `json:"memberPriceList"`           //商品会员价格
	CouponList         []CouponData                `json:"couponList"`                //优惠券信息
	Visibility         ProductVisibilityData       `json:"visibility"`                //商品可见性与可售反馈
}

type ProductFullReductionList struct {
	Id          int64 `json:"id"`          //
	ProductId   int64 `json:"productId"`   //商品id
	FullPrice   int64 `json:"fullPrice"`   //商品满多少
	ReducePrice int64 `json:"reducePrice"` //商品减多少
}

type ProductLadderList struct {
	Id        int64 `json:"id"`        //
	ProductId int64 `json:"productId"` //商品id
	Count     int32 `json:"count"`     //满足的商品数量
	Discount  int64 `json:"discount"`  //折扣
	Price     int64 `json:"price"`     //折后价格
}

type ProductVisibilityData struct {
	Visible        bool   `json:"visible"`        //当前是否允许展示完整详情
	Purchasable    bool   `json:"purchasable"`    //当前是否允许购买
	ShowPrice      bool   `json:"showPrice"`      //是否展示价格
	ShowStock      bool   `json:"showStock"`      //是否展示库存
	Status         string `json:"status"`         //visible/hidden/not-saleable
	ReasonCode     string `json:"reasonCode"`     //product_not_found/owner_disabled/pending_review/review_rejected/off_shelf/preview_only/sold_out
	ReasonMessage  string `json:"reasonMessage"`  //给商城端展示的明确反馈
	RecoveryHint   string `json:"recoveryHint"`   //下一步建议
	FallbackAction string `json:"fallbackAction"` //browse_product_list/browse_similar/go_home
	FallbackTarget string `json:"fallbackTarget"` //替代落点标识
}

type QueryAddressDetailData struct {
	Id            int64  `json:"id"`            //主键ID
	MemberId      int64  `json:"memberId"`      //会员ID
	ReceiverName  string `json:"receiverName"`  //收货人姓名
	ReceiverPhone string `json:"receiverPhone"` //收货人电话
	Province      string `json:"province"`      //省份
	City          string `json:"city"`          //城市
	District      string `json:"district"`      //区县
	DetailAddress string `json:"detailAddress"` //详细地址
	PostalCode    string `json:"postalCode"`    //邮政编码
	Tag           string `json:"tag"`           //地址标签：家、公司等
	IsDefault     int32  `json:"isDefault"`     //是否默认地址
	CreateTime    string `json:"createTime"`    //创建时间
	UpdateTime    string `json:"updateTime"`    //更新时间
}

type QueryAddressDetailReq struct {
	Id int64 `form:"id"`
}

type QueryAddressDetailResp struct {
	Code    int64                  `json:"code"`
	Message string                 `json:"message"`
	Data    QueryAddressDetailData `json:"data"`
}

type QueryAddressListReq struct {
	Current  int64 `form:"current,default=1"`   //第几页
	PageSize int64 `form:"pageSize,default=20"` //每页的数量
}

type QueryAddressListResp struct {
	Code     int64                     `json:"code"`
	Message  string                    `json:"message"`
	Current  int64                     `json:"current,default=1"`
	Data     []*QueryAddressDetailData `json:"data"`
	PageSize int64                     `json:"pageSize,default=20"`
	Success  bool                      `json:"success"`
	Total    int64                     `json:"total"`
}

type QueryAvailableCouponsReq struct {
	PageNum  int32 `form:"pageNum,default=1"`
	PageSize int32 `form:"pageSize,default=10"`
}

type QueryAvailableCouponsResp struct {
	Code    int64         `json:"code"`
	Message string        `json:"message"`
	Data    []*CouponData `json:"data"`
}

type QueryBrandDetailReq struct {
	BrandId  int64 `form:"brandId"`
	Current  int32 `form:"current,default=1"`
	PageSize int32 `form:"pageSize,default=6"`
}

type QueryBrandDetailResp struct {
	Code    int64           `json:"code"`
	Message string          `json:"message"`
	Data    BrandDetailData `json:"data"`
}

type QueryCommentDetailReq struct {
	Id        string `form:"id"`
	ProductId int64  `form:"productId,optional"`
}

type QueryCommentDetailResp struct {
	Code    int64               `json:"code"`
	Message string              `json:"message"`
	Data    CommentListItem     `json:"data"`
	Replays []CommentReplayItem `json:"replays"`
}

type QueryCommentListReq struct {
	ProductId int64 `form:"productId"`
	PageNum   int32 `form:"pageNum,default=1"`
	PageSize  int32 `form:"pageSize,default=10"`
}

type QueryCommentListResp struct {
	Code    int64             `json:"code"`
	Message string            `json:"message"`
	Data    []CommentListItem `json:"data"`
	Total   int64             `json:"total"`
}

type QueryLogisticsReq struct {
	OrderId int64 `form:"orderId"`
}

type QueryLogisticsResp struct {
	Code    int64         `json:"code"`
	Message string        `json:"message"`
	Data    LogisticsData `json:"data"`
}

type QueryMyDrawRecordListData struct {
	Total int64              `json:"total"` //总数
	List  []DrawMemberRecord `json:"list"`  //列表
}

type QueryMyDrawRecordListReq struct {
	ActivityId int64 `form:"activityId"`          //活动ID
	PageNum    int32 `form:"pageNum,default=1"`   //页码
	PageSize   int32 `form:"pageSize,default=10"` //页大小
}

type QueryMyDrawRecordListResp struct {
	Code    string                    `json:"code"`
	Message string                    `json:"message"`
	Data    QueryMyDrawRecordListData `json:"data"`
}

type QueryOrderData struct {
	Id                       int64                    `json:"id"`                 //
	OrderNo                  string                   `json:"orderNo"`            //订单编号
	UserId                   int64                    `json:"userId"`             //用户ID
	RequestTraceId           string                   `json:"requestTraceId"`     //请求链路追踪ID
	OrderStatus              int32                    `json:"orderStatus"`        //订单状态：1-待支付,2-已支付,3-已发货,4-已完成,5-已取消,6-已退款,7-售后中
	TotalAmount              float64                  `json:"totalAmount"`        //订单总金额
	PromotionAmount          float64                  `json:"promotionAmount"`    //促销金额
	CouponAmount             float64                  `json:"couponAmount"`       //优惠券金额
	PointsAmount             float64                  `json:"pointsAmount"`       //积分金额
	DiscountAmount           float64                  `json:"discountAmount"`     //优惠金额
	FreightAmount            float64                  `json:"freightAmount"`      //运费金额
	PayAmount                float64                  `json:"payAmount"`          //实付金额
	PayType                  int32                    `json:"payType"`            //支付方式：1-支付宝,2-微信,3-银联
	PayStatus                int32                    `json:"payStatus"`          //支付状态：0-未支付,1-已支付
	PayTime                  string                   `json:"payTime"`            //支付时间
	DeliveryTime             string                   `json:"deliveryTime"`       //发货时间
	ReceiveTime              string                   `json:"receiveTime"`        //收货时间
	CommentTime              string                   `json:"commentTime"`        //评价时间
	SourceType               int32                    `json:"sourceType"`         //订单来源：1-APP,2-PC,3-小程序
	ExpressOrderNumber       string                   `json:"expressOrderNumber"` //快递单号
	UsePoints                int32                    `json:"usePoints"`          //下单时使用的积分
	ReceiveStatus            int32                    `json:"receiveStatus"`      //是否确认收货：0->否,1->是
	Remark                   string                   `json:"remark"`             //订单备注
	CreateTime               string                   `json:"createTime"`         //提交时间
	UpdateTime               string                   `json:"updateTime"`         //
	Thumbnail                string                   `json:"thumbnail"`          //订单首商品缩略图
	OrderItemData            []*OrderItemData         `json:"orderItemData"`      // 商品数据
	MemberReceiveAddressList MemberReceiveAddressList `json:"memberReceiveAddress"`
	Timeline                 []TimelineNode           `json:"timeline"`       // 订单时间线
	PriceBreakdown           *PriceBreakdown          `json:"priceBreakdown"` // 金额拆分
	// Story 10.7：订单包含的提货卡摘要（C 端安全字段，仅当订单含数字卡商品时返回）
	DigitalCards []OrderDigitalCardItem `json:"digitalCards,omitempty"`
	// Story 10.7：订单是否含提货卡（订单列表页用，避免列表 API 拉全量摘要）
	HasDigitalCards bool `json:"hasDigitalCards,omitempty"`
}

// OrderDigitalCardItem 订单详情的提货卡摘要（C 端安全字段）。
//
// 严守 AGENTS.md C 端监管约束：禁止包含 chainStatus / tokenId / chainTxId /
// lastReceiptJson / chainType 等任何区块链底层字段。
type OrderDigitalCardItem struct {
	AssetInstanceId  int64  `json:"assetInstanceId"`
	AssetNoMasked    string `json:"assetNoMasked"`
	TemplateId       int64  `json:"templateId"`
	TemplateName     string `json:"templateName"`
	TemplateImage    string `json:"templateImage"`
	MintStatus       string `json:"mintStatus"`
	MintStatusText   string `json:"mintStatusText"`
	DisplayStatus    string `json:"displayStatus"`
	ComplianceStatus string `json:"complianceStatus"`
	ComplianceTip    string `json:"complianceTip"`
	OrderItemId      int64  `json:"orderItemId"`
	IssuedAt         string `json:"issuedAt"`
}

type QueryOrderStatusSnapshotReq struct {
	OrderId int64 `json:"orderId"` // 订单ID
}

type QueryOrderStatusSnapshotResp struct {
	Code                 int                     `json:"code"`
	Message              string                  `json:"message"`
	OrderId              int64                   `json:"orderId"`
	OrderNo              string                  `json:"orderNo"`
	RequestTraceId       string                  `json:"requestTraceId"`       // 请求链路追踪ID
	OrderStatus          int                     `json:"orderStatus"`          // OMS order_status
	PayStatus            int                     `json:"payStatus"`            // OMS pay_status
	OrderStatusText      string                  `json:"orderStatusText"`      // 中文状态
	PayStatusText        string                  `json:"payStatusText"`        // 中文支付状态
	OptLogs              []OrderOperationLogItem `json:"optLogs"`              // 操作日志列表
	ConsistencyStage     int                     `json:"consistencyStage"`     // 一致性阶段
	ConsistencyStageText string                  `json:"consistencyStageText"` // 一致性阶段文案
	ConsistencyResult    int                     `json:"consistencyResult"`    // 一致性结果
	ConsistencyMessage   string                  `json:"consistencyMessage"`   // 一致性提示
	LastConsistencyAt    string                  `json:"lastConsistencyAt"`    // 最近一致性时间
	PendingActions       int                     `json:"pendingActions"`       // 待处理动作位掩码
	PendingActionsText   []string                `json:"pendingActionsText"`   // 待处理动作文本
	AftersaleStatus      int32                   `json:"aftersaleStatus"`      // 售后状态
	AftersaleStatusText  string                  `json:"aftersaleStatusText"`  // 售后状态文本
	ReturnId             int64                   `json:"returnId"`             // 售后单ID
	ReturnNo             string                  `json:"returnNo"`             // 售后单号
}

type QueryProductCateListResp struct {
	Code    int64             `json:"code"`
	Message string            `json:"message"`
	Data    []ProductCateData `json:"data"`
}

type QueryProductDetailReq struct {
	ProductId int64 `form:"productId"`
}

type QueryProductDetailResp struct {
	Code    int64             `json:"code"`
	Message string            `json:"message"`
	Data    ProductDetailData `json:"data"`
}

type QueryProductListReq struct {
	Current           int32  `form:"current,default=1"`
	PageSize          int32  `form:"pageSize,default=10"`
	BrandId           int64  `form:"brandId,default=0"`
	ProductCategoryId int64  `form:"productCategoryId,default=0"`
	Keyword           string `form:"keyword,optional"`
	NewStatus         int32  `form:"newStatus,default=2"`       //新品状态:0->不是新品；1->新品
	RecommendStatus   int32  `form:"recommendStatus,default=2"` //推荐状态；0->不推荐；1->推荐
}

type QueryProductListResp struct {
	Code    int64         `json:"code"`
	Message string        `json:"message"`
	Data    []ProductData `json:"data"`
}

type SearchReq struct {
	Keyword    string `form:"keyword,optional" json:"keyword,optional"`       //关键字
	PageNum    int64  `form:"pageNum,default=1" json:"pageNum"`               //页码
	PageSize   int64  `form:"pageSize,default=20" json:"pageSize"`            //每页数量
	Sort       int32  `form:"sort,default=0" json:"sort"`                     //排序字段:0->按相关度；1->按新品；2->按销量；3->价格从低到高；4->价格从高到低
	CategoryId int64  `form:"categoryId,optional" json:"categoryId,optional"` //商品分类ID
	BrandId    int64  `form:"brandId,optional" json:"brandId,optional"`       //品牌ID
}

type ProductItem struct {
	Id            int64  `json:"id"`            //商品ID
	Name          string `json:"name"`          //商品名称
	Brief         string `json:"brief"`         //商品简介
	Price         string `json:"price"`         //展示价格
	OriginalPrice int64  `json:"originalPrice"` //原价
	MainPic       string `json:"mainPic"`       //主图
	Stock         int    `json:"stock"`         //库存
	Sales         int    `json:"sales"`         //销量
	CategoryId    int64  `json:"categoryId"`    //分类ID
	CategoryName  string `json:"categoryName"`  //分类名称
	BrandId       int64  `json:"brandId"`       //品牌ID
	BrandName     string `json:"brandName"`     //品牌名称
}

type SearchResp struct {
	Code      int64         `json:"code"`
	Message   string        `json:"message"`
	Data      []ProductItem `json:"data"`
	Total     int64         `json:"total"`              //总数
	Empty     bool          `json:"empty"`              //是否为空结果
	EmptyHint string        `json:"emptyHint,optional"` //空结果提示
}

type QueryReturnReasonListReq struct {
}

type QueryReturnReasonListResp struct {
	Code       int64              `json:"code"`
	Message    string             `json:"message"`
	ReasonList []ReturnReasonItem `json:"reasonList"`
}

type ReadHistoryDeleteReq struct {
	Ids []string `form:"ids"`
}

type ReadHistoryList struct {
	Id              string `json:"id"`              // 编号
	MemberId        int64  `json:"memberId"`        // 会员id
	MemberNickName  string `json:"memberNickName"`  // 会员姓名
	MemberIcon      string `json:"memberIcon"`      // 会员头像
	ProductId       int64  `json:"productId"`       // 商品id
	ProductName     string `json:"productName"`     // 商品名称
	ProductPic      string `json:"productPic"`      // 商品图片
	ProductSubTitle string `json:"productSubTitle"` // 商品标题
	ProductPrice    int64  `json:"productPrice"`    // 商品价格
	CreateTime      string `json:"createTime"`      // 浏览时间
}

type ReadHistoryListResp struct {
	Code    int64             `json:"code"`
	Message string            `json:"message"`
	Data    []ReadHistoryList `json:"data"` //浏览列表
}

type ReadHistoryReq struct {
	ProductId       int64  `json:"productId"`       // 商品id
	ProductName     string `json:"productName"`     // 商品名称
	ProductPic      string `json:"productPic"`      // 商品图片
	ProductSubTitle string `json:"productSubTitle"` // 商品标题
	ProductPrice    int64  `json:"productPrice"`    // 商品价格
}

type ReadHistoryResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type RecordHomeAdvertiseClickReq struct {
	AdvertiseId int64  `json:"advertiseId"`      //首页广告ID
	TraceId     string `json:"traceId,optional"` //幂等追踪ID
}

type RecordHomeAdvertiseClickResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type ReturnApplyReq struct {
	OrderId        int64            `json:"orderId"`         //关联订单ID
	Status         int32            `json:"status"`          //退货状态（0待审核 1审核通过 2已收货 3已退款 4已拒绝 5已关闭）
	Type           int32            `json:"type"`            //售后类型（0退货退款 1仅退款 2换货）
	Reason         string           `json:"reason"`          //退货原因
	Description    string           `json:"description"`     //问题描述
	ProofPic       string           `json:"proofPic"`        //凭证图片，逗号分隔
	RefundAmount   float32          `json:"refundAmount"`    //退款金额
	ReturnName     string           `json:"returnName"`      //退货人姓名
	ReturnPhone    string           `json:"returnPhone"`     //退货人电话
	CompanyAddress string           `json:"companyAddress"`  //退货收货地址
	Remark         string           `json:"remark,optional"` //备注
	ReturnItemData []ReturnItemData `json:"returnItemData"`  //备注
}

type ReturnApplyResp struct {
	Code     int64  `json:"code"`
	Message  string `json:"message"`
	ReturnId int64  `json:"returnId"` // 售后单ID
	ReturnNo string `json:"returnNo"` // 售后单号
}

type ReturnItemData struct {
	ReturnId     int64   `json:"returnId"`        //退货单ID（关联oms_order_return.id）
	OrderId      int64   `json:"orderId"`         //订单ID
	OrderItemId  int64   `json:"orderItemId"`     //订单明细ID
	SkuId        int64   `json:"skuId"`           //商品SKU ID
	SkuName      string  `json:"skuName"`         //商品名称
	SkuPic       string  `json:"skuPic"`          //商品图片
	SkuAttrs     string  `json:"skuAttrs"`        //商品销售属性
	Quantity     int32   `json:"quantity"`        //退货数量
	ProductPrice float32 `json:"productPrice"`    //商品单价
	RealAmount   float32 `json:"realAmount"`      //实际退款金额
	Reason       string  `json:"reason"`          //退货原因
	Remark       string  `json:"remark,optional"` //备注
}

type ReturnReasonItem struct {
	Id   int64  `json:"id"`   // 原因ID
	Name string `json:"name"` // 原因名称
}

type SkuStockList struct {
	Id                 int64   `json:"id"`                 //商品SpuId
	SpuId              int64   `json:"spuId"`              //商品SpuId
	Name               string  `json:"name"`               //SKU名称
	SkuCode            string  `json:"skuCode"`            //SKU编码
	MainPic            string  `json:"mainPic"`            //主图
	AlbumPics          string  `json:"albumPics"`          //图片集
	Price              float32 `json:"price"`              //价格
	PromotionPrice     float32 `json:"promotionPrice"`     //单品促销价格
	PromotionStartTime string  `json:"promotionStartTime"` //促销开始时间
	PromotionEndTime   string  `json:"promotionEndTime"`   //促销结束时间
	Stock              int32   `json:"stock"`              //库存
	LowStock           int32   `json:"lowStock"`           //预警库存
	SpecData           string  `json:"specData"`           //规格数据
	Weight             float32 `json:"weight"`             //重量(kg)
	PublishStatus      int32   `json:"publishStatus"`      //上架状态：0-下架，1-上架
	VerifyStatus       int32   `json:"verifyStatus"`       //审核状态：0-未审核，1-审核通过，2-审核不通过
	Sort               int32   `json:"sort"`               //排序
	Sales              int32   `json:"sales"`              //销量
}

type SubjectList struct {
	Id              int64  `json:"id"`              //专题id
	CategoryId      int64  `json:"categoryId"`      //专题分类id
	Title           string `json:"title"`           //专题标题
	Pic             string `json:"pic"`             //专题主图
	ProductCount    int32  `json:"productCount"`    //关联产品数量
	RecommendStatus int32  `json:"recommendStatus"` //推荐状态：0->不推荐；1->推荐
	CollectCount    int32  `json:"collectCount"`    //收藏数
	ReadCount       int32  `json:"readCount"`       //阅读数
	CommentCount    int32  `json:"commentCount"`    //评论数
	AlbumPics       string `json:"albumPics"`       //画册图片用逗号分割
	Description     string `json:"description"`     //专题内容
	ShowStatus      int32  `json:"showStatus"`      //显示状态：0->不显示；1->显示
	Content         string `json:"content"`         //专题内容
	ForwardCount    int32  `json:"forwardCount"`    //转发数
	CategoryName    string `json:"categoryName"`    //专题分类名称
	Sort            int32  `json:"sort"`            //排序
}

type SubmitCommentAppealReq struct {
	Id           string `json:"id"`
	AppealReason string `json:"appealReason"`
}

type SubmitCommentAppealResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type TimelineNode struct {
	Status string `json:"status"` // completed/current/interrupted
	Title  string `json:"title"`  // 节点标题
	Time   string `json:"time"`   // 节点时间
	Detail string `json:"detail"` // 节点补充说明
}

type UpdateAddressStatusReq struct {
	Id        int64 `json:"id"`        //主键ID
	IsDefault int32 `json:"isDefault"` //是否默认地址
}

type UpdateCartItemQuantityReq struct {
	Id       int64 `json:"id"`
	Quantity int32 `json:"quantity"` // 购买数量
}

type UpdateMemberReq struct {
	Id        int64  `json:"id"`                //主键ID
	Nickname  string `json:"nickname"`          //昵称
	Mobile    string `json:"mobile"`            //手机号码
	Avatar    string `json:"avatar"`            //头像
	Signature string `json:"signature"`         //个性签名
	Gender    int32  `json:"gender"`            //性别：1-男，2-女
	Birthday  string `json:"birthday,optional"` //生日
}

type UpdateOrderStatusReq struct {
	OrderId int64  `json:"orderId"`          // 订单ID
	Action  int    `json:"action"`           // 操作类型：1=创建订单,2=支付成功,3=支付失败,4=发货,5=确认收货,6=取消,7=退款,8=申请售后,9=售后关闭
	BizData string `json:"bizData,optional"` // 扩展业务数据（JSON 字符串）
}

type UpdateOrderStatusResp struct {
	Code      int    `json:"code"`
	Message   string `json:"message"`
	OldStatus int    `json:"oldStatus"` // 变更前 order_status
	NewStatus int    `json:"newStatus"` // 变更后 order_status
	PayStatus int    `json:"payStatus"` // 变更后 pay_status
	UpdatedAt string `json:"updatedAt"` // 变更时间
}

type UpdatePasswordReq struct {
	Password string `json:"password"` //密码
}
