// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: oms.proto

package orderservice

import (
	"context"

	"github.com/feihua/zero-admin/rpc/oms/omsclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddCartItemReq                    = omsclient.AddCartItemReq
	AddCompanyAddressReq              = omsclient.AddCompanyAddressReq
	AddCompanyAddressResp             = omsclient.AddCompanyAddressResp
	AddOrderDeliveryReq               = omsclient.AddOrderDeliveryReq
	AddOrderDeliveryResp              = omsclient.AddOrderDeliveryResp
	AddOrderOperationLogReq           = omsclient.AddOrderOperationLogReq
	AddOrderOperationLogResp          = omsclient.AddOrderOperationLogResp
	AddOrderPromotionReq              = omsclient.AddOrderPromotionReq
	AddOrderPromotionResp             = omsclient.AddOrderPromotionResp
	AddOrderReq                       = omsclient.AddOrderReq
	AddOrderResp                      = omsclient.AddOrderResp
	AddOrderReturnReasonReq           = omsclient.AddOrderReturnReasonReq
	AddOrderReturnReasonResp          = omsclient.AddOrderReturnReasonResp
	AddOrderSettingReq                = omsclient.AddOrderSettingReq
	AddOrderSettingResp               = omsclient.AddOrderSettingResp
	CancelOrderReq                    = omsclient.CancelOrderReq
	CancelOrderResp                   = omsclient.CancelOrderResp
	CartItemData                      = omsclient.CartItemData
	CartItemResp                      = omsclient.CartItemResp
	ChainMonitorItem                  = omsclient.ChainMonitorItem
	CloseOrderReq                     = omsclient.CloseOrderReq
	CloseOrderResp                    = omsclient.CloseOrderResp
	CompanyAddressListData            = omsclient.CompanyAddressListData
	ConfirmOrderReq                   = omsclient.ConfirmOrderReq
	ConfirmOrderResp                  = omsclient.ConfirmOrderResp
	DeleteCartItemReq                 = omsclient.DeleteCartItemReq
	DeleteCompanyAddressReq           = omsclient.DeleteCompanyAddressReq
	DeleteCompanyAddressResp          = omsclient.DeleteCompanyAddressResp
	DeleteOrderDeliveryReq            = omsclient.DeleteOrderDeliveryReq
	DeleteOrderDeliveryResp           = omsclient.DeleteOrderDeliveryResp
	DeleteOrderPromotionReq           = omsclient.DeleteOrderPromotionReq
	DeleteOrderPromotionResp          = omsclient.DeleteOrderPromotionResp
	DeleteOrderReq                    = omsclient.DeleteOrderReq
	DeleteOrderResp                   = omsclient.DeleteOrderResp
	DeleteOrderReturnReasonReq        = omsclient.DeleteOrderReturnReasonReq
	DeleteOrderReturnReasonResp       = omsclient.DeleteOrderReturnReasonResp
	DeleteOrderReturnReq              = omsclient.DeleteOrderReturnReq
	DeleteOrderSettingReq             = omsclient.DeleteOrderSettingReq
	DeleteOrderSettingResp            = omsclient.DeleteOrderSettingResp
	DeliveryData                      = omsclient.DeliveryData
	DeliveryReq                       = omsclient.DeliveryReq
	DeliveryResp                      = omsclient.DeliveryResp
	EscalateChainReq                  = omsclient.EscalateChainReq
	EscalateChainResp                 = omsclient.EscalateChainResp
	GovernanceScope                   = omsclient.GovernanceScope
	OperateCartBucketPoint            = omsclient.OperateCartBucketPoint
	OperateOrderBucketPoint           = omsclient.OperateOrderBucketPoint
	OrderDeliveryListData             = omsclient.OrderDeliveryListData
	OrderItemData                     = omsclient.OrderItemData
	OrderListData                     = omsclient.OrderListData
	OrderOperationLogData             = omsclient.OrderOperationLogData
	OrderOptLogData                   = omsclient.OrderOptLogData
	OrderPaymentData                  = omsclient.OrderPaymentData
	OrderPaymentReq                   = omsclient.OrderPaymentReq
	OrderPaymentResp                  = omsclient.OrderPaymentResp
	OrderPromotionListData            = omsclient.OrderPromotionListData
	OrderReturnData                   = omsclient.OrderReturnData
	OrderReturnItemData               = omsclient.OrderReturnItemData
	OrderReturnReasonListData         = omsclient.OrderReturnReasonListData
	OrderReturnReq                    = omsclient.OrderReturnReq
	OrderReturnResp                   = omsclient.OrderReturnResp
	OrderSettingListData              = omsclient.OrderSettingListData
	PauseCompensationChainReq         = omsclient.PauseCompensationChainReq
	PauseCompensationChainResp        = omsclient.PauseCompensationChainResp
	PaymentData                       = omsclient.PaymentData
	PromotionListData                 = omsclient.PromotionListData
	QueryCartItemDetailReq            = omsclient.QueryCartItemDetailReq
	QueryCartItemListReq              = omsclient.QueryCartItemListReq
	QueryCartItemListResp             = omsclient.QueryCartItemListResp
	QueryChainActionsReq              = omsclient.QueryChainActionsReq
	QueryChainActionsResp             = omsclient.QueryChainActionsResp
	QueryCompanyAddressDetailReq      = omsclient.QueryCompanyAddressDetailReq
	QueryCompanyAddressDetailResp     = omsclient.QueryCompanyAddressDetailResp
	QueryCompanyAddressListReq        = omsclient.QueryCompanyAddressListReq
	QueryCompanyAddressListResp       = omsclient.QueryCompanyAddressListResp
	QueryCompensationChainListReq     = omsclient.QueryCompensationChainListReq
	QueryCompensationChainListResp    = omsclient.QueryCompensationChainListResp
	QueryDefaultSettingReq            = omsclient.QueryDefaultSettingReq
	QueryManualRequiredOrdersReq      = omsclient.QueryManualRequiredOrdersReq
	QueryManualRequiredOrdersResp     = omsclient.QueryManualRequiredOrdersResp
	QueryOperateCartFunnelReq         = omsclient.QueryOperateCartFunnelReq
	QueryOperateCartFunnelResp        = omsclient.QueryOperateCartFunnelResp
	QueryOperateOrderFunnelReq        = omsclient.QueryOperateOrderFunnelReq
	QueryOperateOrderFunnelResp       = omsclient.QueryOperateOrderFunnelResp
	QueryRepeatPurchaseAnalysisReq    = omsclient.QueryRepeatPurchaseAnalysisReq
	QueryRepeatPurchaseAnalysisResp   = omsclient.QueryRepeatPurchaseAnalysisResp
	QueryRepeatPurchaseDetailListReq  = omsclient.QueryRepeatPurchaseDetailListReq
	QueryRepeatPurchaseDetailListResp = omsclient.QueryRepeatPurchaseDetailListResp
	QueryOrderDeliveryDetailReq       = omsclient.QueryOrderDeliveryDetailReq
	QueryOrderDeliveryDetailResp      = omsclient.QueryOrderDeliveryDetailResp
	QueryOrderDeliveryListReq         = omsclient.QueryOrderDeliveryListReq
	QueryOrderDeliveryListResp        = omsclient.QueryOrderDeliveryListResp
	QueryOrderDetailReq               = omsclient.QueryOrderDetailReq
	QueryOrderDetailResp              = omsclient.QueryOrderDetailResp
	QueryOrderListReq                 = omsclient.QueryOrderListReq
	QueryOrderListResp                = omsclient.QueryOrderListResp
	RepeatPurchaseDetailRow           = omsclient.RepeatPurchaseDetailRow
	RepeatPurchaseOverview            = omsclient.RepeatPurchaseOverview
	RepeatPurchaseTrendPoint          = omsclient.RepeatPurchaseTrendPoint
	QueryOrderOperationLogDetailReq   = omsclient.QueryOrderOperationLogDetailReq
	QueryOrderOperationLogListReq     = omsclient.QueryOrderOperationLogListReq
	QueryOrderOperationLogListResp    = omsclient.QueryOrderOperationLogListResp
	QueryOrderPaymentDetailReq        = omsclient.QueryOrderPaymentDetailReq
	QueryOrderPaymentListReq          = omsclient.QueryOrderPaymentListReq
	QueryOrderPaymentListResp         = omsclient.QueryOrderPaymentListResp
	QueryOrderPromotionDetailReq      = omsclient.QueryOrderPromotionDetailReq
	QueryOrderPromotionDetailResp     = omsclient.QueryOrderPromotionDetailResp
	QueryOrderPromotionListReq        = omsclient.QueryOrderPromotionListReq
	QueryOrderPromotionListResp       = omsclient.QueryOrderPromotionListResp
	QueryOrderReturnDetailReq         = omsclient.QueryOrderReturnDetailReq
	QueryOrderReturnListReq           = omsclient.QueryOrderReturnListReq
	QueryOrderReturnListResp          = omsclient.QueryOrderReturnListResp
	QueryOrderReturnReasonDetailReq   = omsclient.QueryOrderReturnReasonDetailReq
	QueryOrderReturnReasonDetailResp  = omsclient.QueryOrderReturnReasonDetailResp
	QueryOrderReturnReasonListReq     = omsclient.QueryOrderReturnReasonListReq
	QueryOrderReturnReasonListResp    = omsclient.QueryOrderReturnReasonListResp
	QueryOrderSettingDetailReq        = omsclient.QueryOrderSettingDetailReq
	QueryOrderSettingDetailResp       = omsclient.QueryOrderSettingDetailResp
	QueryOrderSettingListReq          = omsclient.QueryOrderSettingListReq
	QueryOrderSettingListResp         = omsclient.QueryOrderSettingListResp
	QueryTimeOutOrderListReq          = omsclient.QueryTimeOutOrderListReq
	ReleaseSkuStockLockData           = omsclient.ReleaseSkuStockLockData
	ReplayCompensationChainReq        = omsclient.ReplayCompensationChainReq
	ReplayCompensationChainResp       = omsclient.ReplayCompensationChainResp
	RetryCompensationChainReq         = omsclient.RetryCompensationChainReq
	RetryCompensationChainResp        = omsclient.RetryCompensationChainResp
	UpdateCartItemQuantityReq         = omsclient.UpdateCartItemQuantityReq
	UpdateCartItemReq                 = omsclient.UpdateCartItemReq
	UpdateCompanyAddressReq           = omsclient.UpdateCompanyAddressReq
	UpdateCompanyAddressResp          = omsclient.UpdateCompanyAddressResp
	UpdateCompanyAddressStatusReq     = omsclient.UpdateCompanyAddressStatusReq
	UpdateCompanyAddressStatusResp    = omsclient.UpdateCompanyAddressStatusResp
	UpdateOrderConsistencyReq         = omsclient.UpdateOrderConsistencyReq
	UpdateOrderConsistencyResp        = omsclient.UpdateOrderConsistencyResp
	UpdateOrderDeliveryReq            = omsclient.UpdateOrderDeliveryReq
	UpdateOrderDeliveryResp           = omsclient.UpdateOrderDeliveryResp
	UpdateOrderPaymentStatusReq       = omsclient.UpdateOrderPaymentStatusReq
	UpdateOrderReq                    = omsclient.UpdateOrderReq
	UpdateOrderResp                   = omsclient.UpdateOrderResp
	UpdateOrderReturnReasonReq        = omsclient.UpdateOrderReturnReasonReq
	UpdateOrderReturnReasonResp       = omsclient.UpdateOrderReturnReasonResp
	UpdateOrderReturnReasonStatusReq  = omsclient.UpdateOrderReturnReasonStatusReq
	UpdateOrderReturnReasonStatusResp = omsclient.UpdateOrderReturnReasonStatusResp
	UpdateOrderReturnStatusReq        = omsclient.UpdateOrderReturnStatusReq
	UpdateOrderSettingReq             = omsclient.UpdateOrderSettingReq
	UpdateOrderSettingResp            = omsclient.UpdateOrderSettingResp
	UpdateOrderSettingStatusReq       = omsclient.UpdateOrderSettingStatusReq
	UpdateOrderSettingStatusResp      = omsclient.UpdateOrderSettingStatusResp
	UpdateOrderStatusReq              = omsclient.UpdateOrderStatusReq
	UpdateOrderStatusResp             = omsclient.UpdateOrderStatusResp
	UpdateReceiverInfoResp            = omsclient.UpdateReceiverInfoResp

	OrderService interface {
		// 添加订单(app)
		AddOrder(ctx context.Context, in *AddOrderReq, opts ...grpc.CallOption) (*AddOrderResp, error)
		// 删除订单
		DeleteOrder(ctx context.Context, in *DeleteOrderReq, opts ...grpc.CallOption) (*DeleteOrderResp, error)
		// 更新订单
		UpdateOrder(ctx context.Context, in *UpdateOrderReq, opts ...grpc.CallOption) (*UpdateOrderResp, error)
		// 更新订单状态
		UpdateOrderStatus(ctx context.Context, in *UpdateOrderStatusReq, opts ...grpc.CallOption) (*UpdateOrderStatusResp, error)
		// 查询订单详情:订单信息、商品信息、操作记录
		QueryOrderDetail(ctx context.Context, in *QueryOrderDetailReq, opts ...grpc.CallOption) (*QueryOrderDetailResp, error)
		// 查询订单列表
		QueryOrderList(ctx context.Context, in *QueryOrderListReq, opts ...grpc.CallOption) (*QueryOrderListResp, error)
		// 查询经营漏斗订单聚合
		QueryOperateOrderFunnel(ctx context.Context, in *QueryOperateOrderFunnelReq, opts ...grpc.CallOption) (*QueryOperateOrderFunnelResp, error)
		QueryRepeatPurchaseAnalysis(ctx context.Context, in *QueryRepeatPurchaseAnalysisReq, opts ...grpc.CallOption) (*QueryRepeatPurchaseAnalysisResp, error)
		QueryRepeatPurchaseDetailList(ctx context.Context, in *QueryRepeatPurchaseDetailListReq, opts ...grpc.CallOption) (*QueryRepeatPurchaseDetailListResp, error)
		// 查询链路监控列表
		QueryCompensationChainList(ctx context.Context, in *QueryCompensationChainListReq, opts ...grpc.CallOption) (*QueryCompensationChainListResp, error)
		// 查询可用干预动作
		QueryChainActions(ctx context.Context, in *QueryChainActionsReq, opts ...grpc.CallOption) (*QueryChainActionsResp, error)
		// 重试补偿链路
		RetryCompensationChain(ctx context.Context, in *RetryCompensationChainReq, opts ...grpc.CallOption) (*RetryCompensationChainResp, error)
		// 回放补偿链路
		ReplayCompensationChain(ctx context.Context, in *ReplayCompensationChainReq, opts ...grpc.CallOption) (*ReplayCompensationChainResp, error)
		// 暂停补偿链路
		PauseCompensationChain(ctx context.Context, in *PauseCompensationChainReq, opts ...grpc.CallOption) (*PauseCompensationChainResp, error)
		// 升级为人工介入
		EscalateChain(ctx context.Context, in *EscalateChainReq, opts ...grpc.CallOption) (*EscalateChainResp, error)
		// 订单发货
		Delivery(ctx context.Context, in *DeliveryReq, opts ...grpc.CallOption) (*DeliveryResp, error)
		// 关闭订单
		CloseOrder(ctx context.Context, in *CloseOrderReq, opts ...grpc.CallOption) (*CloseOrderResp, error)
		// 取消订单(app)
		CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderResp, error)
		// 确认收货(app)
		ConfirmOrder(ctx context.Context, in *ConfirmOrderReq, opts ...grpc.CallOption) (*ConfirmOrderResp, error)
		// 查询超时、未支付的订单及订单详情
		QueryTimeOutOrderList(ctx context.Context, in *QueryTimeOutOrderListReq, opts ...grpc.CallOption) (*QueryOrderListResp, error)
		// 更新订单一致性阶段（用于补偿链路）
		UpdateOrderConsistency(ctx context.Context, in *UpdateOrderConsistencyReq, opts ...grpc.CallOption) (*UpdateOrderConsistencyResp, error)
		// 查询需要人工介入的补偿订单
		QueryManualRequiredOrders(ctx context.Context, in *QueryManualRequiredOrdersReq, opts ...grpc.CallOption) (*QueryManualRequiredOrdersResp, error)
	}

	defaultOrderService struct {
		cli zrpc.Client
	}
)

func NewOrderService(cli zrpc.Client) OrderService {
	return &defaultOrderService{
		cli: cli,
	}
}

// 添加订单(app)
func (m *defaultOrderService) AddOrder(ctx context.Context, in *AddOrderReq, opts ...grpc.CallOption) (*AddOrderResp, error) {
	client := omsclient.NewOrderServiceClient(m.cli.Conn())
	return client.AddOrder(ctx, in, opts...)
}

// 删除订单
func (m *defaultOrderService) DeleteOrder(ctx context.Context, in *DeleteOrderReq, opts ...grpc.CallOption) (*DeleteOrderResp, error) {
	client := omsclient.NewOrderServiceClient(m.cli.Conn())
	return client.DeleteOrder(ctx, in, opts...)
}

// 更新订单
func (m *defaultOrderService) UpdateOrder(ctx context.Context, in *UpdateOrderReq, opts ...grpc.CallOption) (*UpdateOrderResp, error) {
	client := omsclient.NewOrderServiceClient(m.cli.Conn())
	return client.UpdateOrder(ctx, in, opts...)
}

// 更新订单状态
func (m *defaultOrderService) UpdateOrderStatus(ctx context.Context, in *UpdateOrderStatusReq, opts ...grpc.CallOption) (*UpdateOrderStatusResp, error) {
	client := omsclient.NewOrderServiceClient(m.cli.Conn())
	return client.UpdateOrderStatus(ctx, in, opts...)
}

// 查询订单详情:订单信息、商品信息、操作记录
func (m *defaultOrderService) QueryOrderDetail(ctx context.Context, in *QueryOrderDetailReq, opts ...grpc.CallOption) (*QueryOrderDetailResp, error) {
	client := omsclient.NewOrderServiceClient(m.cli.Conn())
	return client.QueryOrderDetail(ctx, in, opts...)
}

// 查询订单列表
func (m *defaultOrderService) QueryOrderList(ctx context.Context, in *QueryOrderListReq, opts ...grpc.CallOption) (*QueryOrderListResp, error) {
	client := omsclient.NewOrderServiceClient(m.cli.Conn())
	return client.QueryOrderList(ctx, in, opts...)
}

// 查询经营漏斗订单聚合
func (m *defaultOrderService) QueryOperateOrderFunnel(ctx context.Context, in *QueryOperateOrderFunnelReq, opts ...grpc.CallOption) (*QueryOperateOrderFunnelResp, error) {
	client := omsclient.NewOrderServiceClient(m.cli.Conn())
	return client.QueryOperateOrderFunnel(ctx, in, opts...)
}

func (m *defaultOrderService) QueryRepeatPurchaseAnalysis(ctx context.Context, in *QueryRepeatPurchaseAnalysisReq, opts ...grpc.CallOption) (*QueryRepeatPurchaseAnalysisResp, error) {
	client := omsclient.NewOrderServiceClient(m.cli.Conn())
	return client.QueryRepeatPurchaseAnalysis(ctx, in, opts...)
}

func (m *defaultOrderService) QueryRepeatPurchaseDetailList(ctx context.Context, in *QueryRepeatPurchaseDetailListReq, opts ...grpc.CallOption) (*QueryRepeatPurchaseDetailListResp, error) {
	client := omsclient.NewOrderServiceClient(m.cli.Conn())
	return client.QueryRepeatPurchaseDetailList(ctx, in, opts...)
}

// 查询链路监控列表
func (m *defaultOrderService) QueryCompensationChainList(ctx context.Context, in *QueryCompensationChainListReq, opts ...grpc.CallOption) (*QueryCompensationChainListResp, error) {
	client := omsclient.NewOrderServiceClient(m.cli.Conn())
	return client.QueryCompensationChainList(ctx, in, opts...)
}

// 查询可用干预动作
func (m *defaultOrderService) QueryChainActions(ctx context.Context, in *QueryChainActionsReq, opts ...grpc.CallOption) (*QueryChainActionsResp, error) {
	client := omsclient.NewOrderServiceClient(m.cli.Conn())
	return client.QueryChainActions(ctx, in, opts...)
}

// 重试补偿链路
func (m *defaultOrderService) RetryCompensationChain(ctx context.Context, in *RetryCompensationChainReq, opts ...grpc.CallOption) (*RetryCompensationChainResp, error) {
	client := omsclient.NewOrderServiceClient(m.cli.Conn())
	return client.RetryCompensationChain(ctx, in, opts...)
}

// 回放补偿链路
func (m *defaultOrderService) ReplayCompensationChain(ctx context.Context, in *ReplayCompensationChainReq, opts ...grpc.CallOption) (*ReplayCompensationChainResp, error) {
	client := omsclient.NewOrderServiceClient(m.cli.Conn())
	return client.ReplayCompensationChain(ctx, in, opts...)
}

// 暂停补偿链路
func (m *defaultOrderService) PauseCompensationChain(ctx context.Context, in *PauseCompensationChainReq, opts ...grpc.CallOption) (*PauseCompensationChainResp, error) {
	client := omsclient.NewOrderServiceClient(m.cli.Conn())
	return client.PauseCompensationChain(ctx, in, opts...)
}

// 升级为人工介入
func (m *defaultOrderService) EscalateChain(ctx context.Context, in *EscalateChainReq, opts ...grpc.CallOption) (*EscalateChainResp, error) {
	client := omsclient.NewOrderServiceClient(m.cli.Conn())
	return client.EscalateChain(ctx, in, opts...)
}

// 订单发货
func (m *defaultOrderService) Delivery(ctx context.Context, in *DeliveryReq, opts ...grpc.CallOption) (*DeliveryResp, error) {
	client := omsclient.NewOrderServiceClient(m.cli.Conn())
	return client.Delivery(ctx, in, opts...)
}

// 关闭订单
func (m *defaultOrderService) CloseOrder(ctx context.Context, in *CloseOrderReq, opts ...grpc.CallOption) (*CloseOrderResp, error) {
	client := omsclient.NewOrderServiceClient(m.cli.Conn())
	return client.CloseOrder(ctx, in, opts...)
}

// 取消订单(app)
func (m *defaultOrderService) CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderResp, error) {
	client := omsclient.NewOrderServiceClient(m.cli.Conn())
	return client.CancelOrder(ctx, in, opts...)
}

// 确认收货(app)
func (m *defaultOrderService) ConfirmOrder(ctx context.Context, in *ConfirmOrderReq, opts ...grpc.CallOption) (*ConfirmOrderResp, error) {
	client := omsclient.NewOrderServiceClient(m.cli.Conn())
	return client.ConfirmOrder(ctx, in, opts...)
}

// 查询超时、未支付的订单及订单详情
func (m *defaultOrderService) QueryTimeOutOrderList(ctx context.Context, in *QueryTimeOutOrderListReq, opts ...grpc.CallOption) (*QueryOrderListResp, error) {
	client := omsclient.NewOrderServiceClient(m.cli.Conn())
	return client.QueryTimeOutOrderList(ctx, in, opts...)
}

// 更新订单一致性阶段（用于补偿链路）
func (m *defaultOrderService) UpdateOrderConsistency(ctx context.Context, in *UpdateOrderConsistencyReq, opts ...grpc.CallOption) (*UpdateOrderConsistencyResp, error) {
	client := omsclient.NewOrderServiceClient(m.cli.Conn())
	return client.UpdateOrderConsistency(ctx, in, opts...)
}

// 查询需要人工介入的补偿订单
func (m *defaultOrderService) QueryManualRequiredOrders(ctx context.Context, in *QueryManualRequiredOrdersReq, opts ...grpc.CallOption) (*QueryManualRequiredOrdersResp, error) {
	client := omsclient.NewOrderServiceClient(m.cli.Conn())
	return client.QueryManualRequiredOrders(ctx, in, opts...)
}
