// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: oms.proto

package server

import (
	"context"

	"github.com/feihua/zero-admin/rpc/oms/internal/logic/orderservice"
	"github.com/feihua/zero-admin/rpc/oms/internal/svc"
	"github.com/feihua/zero-admin/rpc/oms/omsclient"
)

type OrderServiceServer struct {
	svcCtx *svc.ServiceContext
	omsclient.UnimplementedOrderServiceServer
}

func NewOrderServiceServer(svcCtx *svc.ServiceContext) *OrderServiceServer {
	return &OrderServiceServer{
		svcCtx: svcCtx,
	}
}

// 添加订单(app)
func (s *OrderServiceServer) AddOrder(ctx context.Context, in *omsclient.AddOrderReq) (*omsclient.AddOrderResp, error) {
	l := orderservicelogic.NewAddOrderLogic(ctx, s.svcCtx)
	return l.AddOrder(in)
}

// 删除订单
func (s *OrderServiceServer) DeleteOrder(ctx context.Context, in *omsclient.DeleteOrderReq) (*omsclient.DeleteOrderResp, error) {
	l := orderservicelogic.NewDeleteOrderLogic(ctx, s.svcCtx)
	return l.DeleteOrder(in)
}

// 更新订单
func (s *OrderServiceServer) UpdateOrder(ctx context.Context, in *omsclient.UpdateOrderReq) (*omsclient.UpdateOrderResp, error) {
	l := orderservicelogic.NewUpdateOrderLogic(ctx, s.svcCtx)
	return l.UpdateOrder(in)
}

// 更新订单状态
func (s *OrderServiceServer) UpdateOrderStatus(ctx context.Context, in *omsclient.UpdateOrderStatusReq) (*omsclient.UpdateOrderStatusResp, error) {
	l := orderservicelogic.NewUpdateOrderStatusLogic(ctx, s.svcCtx)
	return l.UpdateOrderStatus(in)
}

// 查询订单详情:订单信息、商品信息、操作记录
func (s *OrderServiceServer) QueryOrderDetail(ctx context.Context, in *omsclient.QueryOrderDetailReq) (*omsclient.QueryOrderDetailResp, error) {
	l := orderservicelogic.NewQueryOrderDetailLogic(ctx, s.svcCtx)
	return l.QueryOrderDetail(in)
}

// 查询订单列表
func (s *OrderServiceServer) QueryOrderList(ctx context.Context, in *omsclient.QueryOrderListReq) (*omsclient.QueryOrderListResp, error) {
	l := orderservicelogic.NewQueryOrderListLogic(ctx, s.svcCtx)
	return l.QueryOrderList(in)
}

// 订单发货
func (s *OrderServiceServer) Delivery(ctx context.Context, in *omsclient.DeliveryReq) (*omsclient.DeliveryResp, error) {
	l := orderservicelogic.NewDeliveryLogic(ctx, s.svcCtx)
	return l.Delivery(in)
}

// 关闭订单
func (s *OrderServiceServer) CloseOrder(ctx context.Context, in *omsclient.CloseOrderReq) (*omsclient.CloseOrderResp, error) {
	l := orderservicelogic.NewCloseOrderLogic(ctx, s.svcCtx)
	return l.CloseOrder(in)
}

// 取消订单(app)
func (s *OrderServiceServer) CancelOrder(ctx context.Context, in *omsclient.CancelOrderReq) (*omsclient.CancelOrderResp, error) {
	l := orderservicelogic.NewCancelOrderLogic(ctx, s.svcCtx)
	return l.CancelOrder(in)
}

// 确认收货(app)
func (s *OrderServiceServer) ConfirmOrder(ctx context.Context, in *omsclient.ConfirmOrderReq) (*omsclient.ConfirmOrderResp, error) {
	l := orderservicelogic.NewConfirmOrderLogic(ctx, s.svcCtx)
	return l.ConfirmOrder(in)
}

// 查询超时、未支付的订单及订单详情
func (s *OrderServiceServer) QueryTimeOutOrderList(ctx context.Context, in *omsclient.QueryTimeOutOrderListReq) (*omsclient.QueryOrderListResp, error) {
	l := orderservicelogic.NewQueryTimeOutOrderListLogic(ctx, s.svcCtx)
	return l.QueryTimeOutOrderList(in)
}

// 更新订单一致性阶段（用于补偿链路）
func (s *OrderServiceServer) UpdateOrderConsistency(ctx context.Context, in *omsclient.UpdateOrderConsistencyReq) (*omsclient.UpdateOrderConsistencyResp, error) {
	l := orderservicelogic.NewUpdateOrderConsistencyLogic(ctx, s.svcCtx)
	return l.UpdateOrderConsistency(in)
}

// 查询需要人工介入的补偿订单
func (s *OrderServiceServer) QueryManualRequiredOrders(ctx context.Context, in *omsclient.QueryManualRequiredOrdersReq) (*omsclient.QueryManualRequiredOrdersResp, error) {
	l := orderservicelogic.NewQueryManualRequiredOrdersLogic(ctx, s.svcCtx)
	return l.QueryManualRequiredOrders(in)
}

// 查询补偿链路列表（支持一致性筛选+时间范围）
func (s *OrderServiceServer) QueryCompensationChainList(ctx context.Context, in *omsclient.QueryCompensationChainListReq) (*omsclient.QueryCompensationChainListResp, error) {
	l := orderservicelogic.NewQueryCompensationChainListLogic(ctx, s.svcCtx)
	return l.QueryCompensationChainList(in)
}

// 重试链路（7.6 新增）
func (s *OrderServiceServer) RetryCompensationChain(ctx context.Context, in *omsclient.RetryCompensationChainReq) (*omsclient.RetryCompensationChainResp, error) {
	l := orderservicelogic.NewRetryCompensationChainLogic(ctx, s.svcCtx)
	return l.RetryCompensationChain(in)
}

// 回放链路（7.6 新增）
func (s *OrderServiceServer) ReplayCompensationChain(ctx context.Context, in *omsclient.ReplayCompensationChainReq) (*omsclient.ReplayCompensationChainResp, error) {
	l := orderservicelogic.NewReplayCompensationChainLogic(ctx, s.svcCtx)
	return l.ReplayCompensationChain(in)
}

// 暂停链路（7.6 新增）
func (s *OrderServiceServer) PauseCompensationChain(ctx context.Context, in *omsclient.PauseCompensationChainReq) (*omsclient.PauseCompensationChainResp, error) {
	l := orderservicelogic.NewPauseCompensationChainLogic(ctx, s.svcCtx)
	return l.PauseCompensationChain(in)
}

// 升级链路（7.6 新增）
func (s *OrderServiceServer) EscalateChain(ctx context.Context, in *omsclient.EscalateChainReq) (*omsclient.EscalateChainResp, error) {
	l := orderservicelogic.NewEscalateChainLogic(ctx, s.svcCtx)
	return l.EscalateChain(in)
}

// 查询可用干预动作（7.6 新增）
func (s *OrderServiceServer) QueryChainActions(ctx context.Context, in *omsclient.QueryChainActionsReq) (*omsclient.QueryChainActionsResp, error) {
	l := orderservicelogic.NewQueryChainActionsLogic(ctx, s.svcCtx)
	return l.QueryChainActions(in)
}
