CREATE TABLE IF NOT EXISTS `sms_card_physical_fulfillment` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
    `platform_id` BIGINT NOT NULL DEFAULT 1 COMMENT '平台ID',
    `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
    `merchant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '商户ID',
    `asset_instance_id` BIGINT NOT NULL COMMENT '数字卡片资产实例ID',
    `participation_record_id` BIGINT NOT NULL DEFAULT 0 COMMENT '抽卡参与记录ID',
    `activity_id` BIGINT NOT NULL DEFAULT 0 COMMENT '活动ID',
    `template_id` BIGINT NOT NULL DEFAULT 0 COMMENT '卡片模板ID',
    `member_id` BIGINT NOT NULL DEFAULT 0 COMMENT '会员ID',
    `asset_no` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '卡片编号',
    `fulfillment_no` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '实体履约单号',
    `fulfillment_status` VARCHAR(32) NOT NULL DEFAULT 'pending_address' COMMENT '履约状态',
    `production_status` VARCHAR(32) NOT NULL DEFAULT 'not_started' COMMENT '制作状态',
    `quality_status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '质检状态',
    `shipping_status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '物流状态',
    `address_id` BIGINT NOT NULL DEFAULT 0 COMMENT '会员地址ID',
    `receiver_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '收货人姓名快照',
    `receiver_phone` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '收货人手机号快照',
    `receiver_province` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '省份快照',
    `receiver_city` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '城市快照',
    `receiver_district` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '区县快照',
    `receiver_address` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '详细地址快照',
    `receiver_postal_code` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '邮编快照',
    `production_batch_no` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '制作批次号',
    `carrier_code` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '承运商编码',
    `carrier_code_guard` VARCHAR(32) GENERATED ALWAYS AS (NULLIF(`carrier_code`, '')) STORED COMMENT '非空承运商唯一约束列',
    `carrier_name` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '承运商名称',
    `tracking_no` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '物流单号',
    `tracking_no_guard` VARCHAR(64) GENERATED ALWAYS AS (NULLIF(`tracking_no`, '')) STORED COMMENT '非空物流单唯一约束列',
    `shipped_at` DATETIME NULL DEFAULT NULL COMMENT '发货时间',
    `signed_at` DATETIME NULL DEFAULT NULL COMMENT '签收时间',
    `auto_sign_at` DATETIME NULL DEFAULT NULL COMMENT '自动签收时间',
    `failure_code` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '异常编码',
    `failure_reason` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '异常原因',
    `operator_id` BIGINT NOT NULL DEFAULT 0 COMMENT '最近操作人ID',
    `trace_id` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '链路追踪ID',
    `request_id` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '业务请求ID',
    `create_by` BIGINT NOT NULL DEFAULT 0 COMMENT '创建人ID',
    `update_by` BIGINT NOT NULL DEFAULT 0 COMMENT '更新人ID',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_card_physical_asset` (`asset_instance_id`, `is_deleted`),
    UNIQUE KEY `uk_card_physical_no` (`fulfillment_no`, `is_deleted`),
    UNIQUE KEY `uk_card_physical_tracking` (`tracking_no_guard`, `carrier_code_guard`, `is_deleted`),
    KEY `idx_card_physical_scope_status` (`platform_id`, `tenant_id`, `merchant_id`, `fulfillment_status`, `id`),
    KEY `idx_card_physical_activity_template` (`activity_id`, `template_id`, `id`),
    KEY `idx_card_physical_member` (`member_id`, `id`),
    KEY `idx_card_physical_asset_no` (`asset_no`, `is_deleted`),
    KEY `idx_card_physical_batch` (`production_batch_no`, `id`),
    KEY `idx_card_physical_tracking_lookup` (`tracking_no`, `carrier_code`, `is_deleted`),
    KEY `idx_card_physical_timeout` (`fulfillment_status`, `update_time`, `id`),
    KEY `idx_card_physical_trace` (`trace_id`)
) COMMENT='数字卡片实体履约单表';

CREATE TABLE IF NOT EXISTS `sms_card_physical_fulfillment_log` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
    `fulfillment_id` BIGINT NOT NULL COMMENT '实体履约单ID',
    `asset_instance_id` BIGINT NOT NULL COMMENT '数字卡片资产实例ID',
    `action` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '履约动作',
    `from_status` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '原履约状态',
    `to_status` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '新履约状态',
    `operator_type` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '操作者类型',
    `operator_id` BIGINT NOT NULL DEFAULT 0 COMMENT '操作者ID',
    `reason` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '操作原因',
    `payload_json` JSON NULL COMMENT '动作载荷快照',
    `trace_id` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '链路追踪ID',
    `request_id` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '业务请求ID',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`),
    KEY `idx_card_physical_log_fulfillment` (`fulfillment_id`, `id`),
    KEY `idx_card_physical_log_asset` (`asset_instance_id`, `id`),
    KEY `idx_card_physical_log_action` (`action`, `create_time`),
    KEY `idx_card_physical_log_trace` (`trace_id`)
) COMMENT='数字卡片实体履约日志表';
