CREATE TABLE IF NOT EXISTS `sms_draw_activity` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
    `platform_id` BIGINT NOT NULL DEFAULT 1 COMMENT '平台ID',
    `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
    `merchant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '商户ID',
    `activity_code` VARCHAR(64) NOT NULL COMMENT '活动编码',
    `name` VARCHAR(100) NOT NULL COMMENT '活动名称',
    `rule_summary` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '规则摘要',
    `start_time` DATETIME NOT NULL COMMENT '开始时间',
    `end_time` DATETIME NOT NULL COMMENT '结束时间',
    `real_name_required` TINYINT NOT NULL DEFAULT 0 COMMENT '是否实名要求',
    `participant_condition_summary` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '参与条件摘要',
    `consume_rule_summary` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '消耗规则摘要',
    `probability_rule` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '概率披露方式',
    `compliance_rule_summary` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '合规规则摘要',
    `circulation_limit_summary` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '流转限制摘要',
    `approval_record_ref` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '审批记录引用',
    `publish_failure_summary` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '发布失败摘要',
    `publish_readiness` TINYINT NOT NULL DEFAULT 0 COMMENT '可发布状态:0-缺少信息,1-可发布,2-待审批,3-已下线',
    `copyright_status` TINYINT NOT NULL DEFAULT 0 COMMENT '版权校验状态:0-缺失,1-待核验,2-通过,3-拒绝',
    `content_audit_status` TINYINT NOT NULL DEFAULT 0 COMMENT '内容审核状态:0-缺失,1-待审核,2-通过,3-拒绝',
    `status` TINYINT NOT NULL DEFAULT 0 COMMENT '活动状态:0-草稿/下线,1-已发布,2-已归档',
    `audit_status` TINYINT NOT NULL DEFAULT 0 COMMENT '审批状态:0-缺失,1-待审批,2-通过,3-拒绝',
    `is_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用',
    `show_on_home` TINYINT NOT NULL DEFAULT 0 COMMENT '首页是否显著展示',
    `home_entry_title` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '首页入口标题',
    `home_entry_subtitle` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '首页入口副标题',
    `home_entry_image` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '首页入口封面图',
    `home_entry_sort` INT NOT NULL DEFAULT 0 COMMENT '首页入口排序权重',
    `home_entry_enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '首页入口是否启用',
    `landing_target_type` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '落地目标类型',
    `landing_target_value` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '落地目标值',
    `create_by` BIGINT NOT NULL COMMENT '创建人ID',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` BIGINT NULL COMMENT '更新人ID',
    `update_time` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
    `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_draw_activity_code_scope` (`platform_id`, `tenant_id`, `merchant_id`, `activity_code`, `is_deleted`),
    KEY `idx_draw_activity_scope_status` (`platform_id`, `tenant_id`, `merchant_id`, `status`, `id`),
    KEY `idx_draw_activity_publish` (`publish_readiness`, `audit_status`, `is_enabled`, `id`)
) COMMENT='抽卡活动主表';

CREATE TABLE IF NOT EXISTS `sms_draw_pool` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
    `activity_id` BIGINT NOT NULL COMMENT '活动ID',
    `platform_id` BIGINT NOT NULL DEFAULT 1 COMMENT '平台ID',
    `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
    `merchant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '商户ID',
    `pool_code` VARCHAR(64) NOT NULL COMMENT '卡池编码',
    `pool_name` VARCHAR(100) NOT NULL COMMENT '卡池名称',
    `probability_rule` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '卡池概率规则',
    `sort` INT NOT NULL DEFAULT 0 COMMENT '排序',
    `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态',
    `audit_status` TINYINT NOT NULL DEFAULT 0 COMMENT '审批状态',
    `create_by` BIGINT NOT NULL COMMENT '创建人ID',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` BIGINT NULL COMMENT '更新人ID',
    `update_time` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
    `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_draw_pool_name` (`activity_id`, `pool_name`, `is_deleted`),
    UNIQUE KEY `uk_draw_pool_code` (`activity_id`, `pool_code`, `is_deleted`),
    KEY `idx_draw_pool_activity_status` (`activity_id`, `status`, `id`)
) COMMENT='抽卡活动卡池表';

CREATE TABLE IF NOT EXISTS `sms_card_template` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
    `platform_id` BIGINT NOT NULL DEFAULT 1 COMMENT '平台ID',
    `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
    `merchant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '商户ID',
    `template_code` VARCHAR(64) NOT NULL COMMENT '模板编码',
    `template_name` VARCHAR(100) NOT NULL COMMENT '模板名称',
    `card_face_image` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '卡面资源',
    `copyright_owner` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '版权归属',
    `copyright_proof_summary` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '版权凭证摘要',
    `rarity` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '稀有度',
    `issue_limit` BIGINT NOT NULL DEFAULT 0 COMMENT '发行上限',
    `display_copy` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '展示文案',
    `circulation_limit_summary` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '默认流转限制',
    `display_status` TINYINT NOT NULL DEFAULT 1 COMMENT '展示状态',
    `content_audit_status` TINYINT NOT NULL DEFAULT 0 COMMENT '内容审核状态',
    `provider_code` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '接入方编码',
    `credential_ref` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '实名/版权凭证引用',
    `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态',
    `audit_status` TINYINT NOT NULL DEFAULT 0 COMMENT '审批状态',
    `create_by` BIGINT NOT NULL COMMENT '创建人ID',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` BIGINT NULL COMMENT '更新人ID',
    `update_time` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
    `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_card_template_code` (`platform_id`, `tenant_id`, `merchant_id`, `template_code`, `is_deleted`),
    KEY `idx_card_template_scope_status` (`platform_id`, `tenant_id`, `merchant_id`, `status`, `id`)
) COMMENT='数字卡片模板表';

CREATE TABLE IF NOT EXISTS `sms_draw_pool_template` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
    `activity_id` BIGINT NOT NULL COMMENT '活动ID',
    `pool_id` BIGINT NOT NULL COMMENT '卡池ID',
    `template_id` BIGINT NOT NULL COMMENT '模板ID',
    `platform_id` BIGINT NOT NULL DEFAULT 1 COMMENT '平台ID',
    `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
    `merchant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '商户ID',
    `rarity` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '稀有度',
    `probability` DECIMAL(10,6) NOT NULL DEFAULT 0 COMMENT '概率值',
    `sale_limit` BIGINT NOT NULL DEFAULT 0 COMMENT '发售数量',
    `remaining_limit` BIGINT NOT NULL DEFAULT 0 COMMENT '剩余可发数量',
    `config_limit` BIGINT NOT NULL DEFAULT 0 COMMENT '配置上限',
    `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态',
    `audit_status` TINYINT NOT NULL DEFAULT 0 COMMENT '审批状态',
    `create_by` BIGINT NOT NULL COMMENT '创建人ID',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` BIGINT NULL COMMENT '更新人ID',
    `update_time` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
    `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_draw_pool_template` (`pool_id`, `template_id`, `is_deleted`),
    KEY `idx_draw_pool_template_activity_status` (`activity_id`, `status`, `id`)
) COMMENT='卡池模板映射表';

CREATE TABLE IF NOT EXISTS `sms_draw_activity_audit` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
    `activity_id` BIGINT NOT NULL COMMENT '活动ID',
    `platform_id` BIGINT NOT NULL DEFAULT 1 COMMENT '平台ID',
    `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
    `merchant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '商户ID',
    `operation_type` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '操作类型',
    `operator_id` BIGINT NOT NULL DEFAULT 0 COMMENT '操作人ID',
    `operator_name` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '操作人',
    `approval_result` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '审批结果',
    `rule_snapshot` TEXT NULL COMMENT '规则快照',
    `circulation_limit_snapshot` TEXT NULL COMMENT '流转限制快照',
    `failure_summary` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '失败摘要',
    `trace_id` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '链路追踪ID',
    `payload_json` LONGTEXT NULL COMMENT '完整审计载荷',
    `status` TINYINT NOT NULL DEFAULT 0 COMMENT '活动状态',
    `audit_status` TINYINT NOT NULL DEFAULT 0 COMMENT '审批状态',
    `create_by` BIGINT NOT NULL DEFAULT 0 COMMENT '记录创建人ID',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`),
    KEY `idx_draw_activity_audit_activity_status` (`activity_id`, `create_time`, `id`),
    KEY `idx_draw_activity_audit_trace` (`trace_id`)
) COMMENT='抽卡活动审计快照表';
