// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	orderdetail "github.com/feihua/zero-admin/api/front/internal/handler/order/order"
	orderlist "github.com/feihua/zero-admin/api/front/internal/handler/order/order"
	orderpay "github.com/feihua/zero-admin/api/front/internal/handler/order/pay"
	"github.com/feihua/zero-admin/api/front/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/orderPay",
				Handler: orderpay.OrderPayHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/orderPayQuery/:orderId",
				Handler: orderpay.OrderPayQueryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/orderPayQueryStatus",
				Handler: orderpay.OrderPayQueryStatusHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/order"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/queryOrderList",
				Handler: orderlist.QueryOrderListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/queryOrderDetail",
				Handler: orderdetail.QueryOrderDetailHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/order"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/notify",
				Handler: orderpay.NotifyHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/pay"),
	)
}
