// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: sys.proto

package tenantservice

import (
	"context"

	"github.com/feihua/zero-admin/rpc/sys/sysclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddDeptReq                   = sysclient.AddDeptReq
	AddDeptResp                  = sysclient.AddDeptResp
	AddDictItemReq               = sysclient.AddDictItemReq
	AddDictItemResp              = sysclient.AddDictItemResp
	AddDictTypeReq               = sysclient.AddDictTypeReq
	AddDictTypeResp              = sysclient.AddDictTypeResp
	AddMenuReq                   = sysclient.AddMenuReq
	AddMenuResp                  = sysclient.AddMenuResp
	AddMenuTemplateReq           = sysclient.AddMenuTemplateReq
	AddMenuTemplateResp          = sysclient.AddMenuTemplateResp
	AddNoticeReq                 = sysclient.AddNoticeReq
	AddNoticeResp                = sysclient.AddNoticeResp
	AddOperateLogReq             = sysclient.AddOperateLogReq
	AddOperateLogResp            = sysclient.AddOperateLogResp
	AddPostReq                   = sysclient.AddPostReq
	AddPostResp                  = sysclient.AddPostResp
	AddRoleReq                   = sysclient.AddRoleReq
	AddRoleResp                  = sysclient.AddRoleResp
	AddUserReq                   = sysclient.AddUserReq
	AddUserResp                  = sysclient.AddUserResp
	CancelAuthorizationReq       = sysclient.CancelAuthorizationReq
	CancelAuthorizationResp      = sysclient.CancelAuthorizationResp
	ChangeTenantStatusReq        = sysclient.ChangeTenantStatusReq
	ChangeTenantStatusResp       = sysclient.ChangeTenantStatusResp
	CreateTenantReq              = sysclient.CreateTenantReq
	CreateTenantResp             = sysclient.CreateTenantResp
	DeleteDeptReq                = sysclient.DeleteDeptReq
	DeleteDeptResp               = sysclient.DeleteDeptResp
	DeleteDictItemReq            = sysclient.DeleteDictItemReq
	DeleteDictItemResp           = sysclient.DeleteDictItemResp
	DeleteDictTypeReq            = sysclient.DeleteDictTypeReq
	DeleteDictTypeResp           = sysclient.DeleteDictTypeResp
	DeleteLoginLogReq            = sysclient.DeleteLoginLogReq
	DeleteLoginLogResp           = sysclient.DeleteLoginLogResp
	DeleteMenuReq                = sysclient.DeleteMenuReq
	DeleteMenuResp               = sysclient.DeleteMenuResp
	DeleteMenuTemplateReq        = sysclient.DeleteMenuTemplateReq
	DeleteMenuTemplateResp       = sysclient.DeleteMenuTemplateResp
	DeleteNoticeReq              = sysclient.DeleteNoticeReq
	DeleteNoticeResp             = sysclient.DeleteNoticeResp
	DeleteOperateLogReq          = sysclient.DeleteOperateLogReq
	DeleteOperateLogResp         = sysclient.DeleteOperateLogResp
	DeletePostReq                = sysclient.DeletePostReq
	DeletePostResp               = sysclient.DeletePostResp
	DeleteRoleReq                = sysclient.DeleteRoleReq
	DeleteRoleResp               = sysclient.DeleteRoleResp
	DeleteUserReq                = sysclient.DeleteUserReq
	DeleteUserResp               = sysclient.DeleteUserResp
	DeptData                     = sysclient.DeptData
	DeptListData                 = sysclient.DeptListData
	DictItemListData             = sysclient.DictItemListData
	DictTypeListData             = sysclient.DictTypeListData
	GovernanceScope              = sysclient.GovernanceScope
	InfoReq                      = sysclient.InfoReq
	InfoResp                     = sysclient.InfoResp
	LoginLogListData             = sysclient.LoginLogListData
	LoginReq                     = sysclient.LoginReq
	LoginResp                    = sysclient.LoginResp
	MenuData                     = sysclient.MenuData
	MenuListData                 = sysclient.MenuListData
	MenuListTree                 = sysclient.MenuListTree
	MenuTemplateListData         = sysclient.MenuTemplateListData
	OperateLogListData           = sysclient.OperateLogListData
	PostData                     = sysclient.PostData
	PostListData                 = sysclient.PostListData
	QueryDeptAndPostListReq      = sysclient.QueryDeptAndPostListReq
	QueryDeptAndPostListResp     = sysclient.QueryDeptAndPostListResp
	QueryDeptDetailReq           = sysclient.QueryDeptDetailReq
	QueryDeptDetailResp          = sysclient.QueryDeptDetailResp
	QueryDeptListReq             = sysclient.QueryDeptListReq
	QueryDeptListResp            = sysclient.QueryDeptListResp
	QueryDictItemDetailReq       = sysclient.QueryDictItemDetailReq
	QueryDictItemDetailResp      = sysclient.QueryDictItemDetailResp
	QueryDictItemListReq         = sysclient.QueryDictItemListReq
	QueryDictItemListResp        = sysclient.QueryDictItemListResp
	QueryDictTypeDetailReq       = sysclient.QueryDictTypeDetailReq
	QueryDictTypeDetailResp      = sysclient.QueryDictTypeDetailResp
	QueryDictTypeListReq         = sysclient.QueryDictTypeListReq
	QueryDictTypeListResp        = sysclient.QueryDictTypeListResp
	QueryLoginLogDetailReq       = sysclient.QueryLoginLogDetailReq
	QueryLoginLogDetailResp      = sysclient.QueryLoginLogDetailResp
	QueryLoginLogListReq         = sysclient.QueryLoginLogListReq
	QueryLoginLogListResp        = sysclient.QueryLoginLogListResp
	QueryMenuDetailReq           = sysclient.QueryMenuDetailReq
	QueryMenuDetailResp          = sysclient.QueryMenuDetailResp
	QueryMenuListReq             = sysclient.QueryMenuListReq
	QueryMenuListResp            = sysclient.QueryMenuListResp
	QueryMenuTemplateByScope     = sysclient.QueryMenuTemplateByScope
	QueryMenuTemplateByScopeResp = sysclient.QueryMenuTemplateByScopeResp
	QueryMenuTemplateDetailReq   = sysclient.QueryMenuTemplateDetailReq
	QueryMenuTemplateDetailResp  = sysclient.QueryMenuTemplateDetailResp
	QueryMenuTemplateListReq     = sysclient.QueryMenuTemplateListReq
	QueryMenuTemplateListResp    = sysclient.QueryMenuTemplateListResp
	QueryNoticeDetailReq         = sysclient.QueryNoticeDetailReq
	QueryNoticeDetailResp        = sysclient.QueryNoticeDetailResp
	QueryNoticeListData          = sysclient.QueryNoticeListData
	QueryNoticeListReq           = sysclient.QueryNoticeListReq
	QueryNoticeListResp          = sysclient.QueryNoticeListResp
	QueryOperateLogDetailReq     = sysclient.QueryOperateLogDetailReq
	QueryOperateLogDetailResp    = sysclient.QueryOperateLogDetailResp
	QueryOperateLogListReq       = sysclient.QueryOperateLogListReq
	QueryOperateLogListResp      = sysclient.QueryOperateLogListResp
	QueryPostDetailReq           = sysclient.QueryPostDetailReq
	QueryPostDetailResp          = sysclient.QueryPostDetailResp
	QueryPostListReq             = sysclient.QueryPostListReq
	QueryPostListResp            = sysclient.QueryPostListResp
	QueryRoleDetailReq           = sysclient.QueryRoleDetailReq
	QueryRoleDetailResp          = sysclient.QueryRoleDetailResp
	QueryRoleListReq             = sysclient.QueryRoleListReq
	QueryRoleListResp            = sysclient.QueryRoleListResp
	QueryRoleMenuListReq         = sysclient.QueryRoleMenuListReq
	QueryRoleMenuListResp        = sysclient.QueryRoleMenuListResp
	QueryRoleUserListReq         = sysclient.QueryRoleUserListReq
	QueryRoleUserListResp        = sysclient.QueryRoleUserListResp
	QueryTenantDetailReq         = sysclient.QueryTenantDetailReq
	QueryTenantDetailResp        = sysclient.QueryTenantDetailResp
	QueryTenantListReq           = sysclient.QueryTenantListReq
	QueryTenantListResp          = sysclient.QueryTenantListResp
	QueryUserDetailReq           = sysclient.QueryUserDetailReq
	QueryUserDetailResp          = sysclient.QueryUserDetailResp
	QueryUserListReq             = sysclient.QueryUserListReq
	QueryUserListResp            = sysclient.QueryUserListResp
	QueryUserRoleListReq         = sysclient.QueryUserRoleListReq
	QueryUserRoleListResp        = sysclient.QueryUserRoleListResp
	ReSetPasswordReq             = sysclient.ReSetPasswordReq
	ReSetPasswordResp            = sysclient.ReSetPasswordResp
	RoleData                     = sysclient.RoleData
	RoleListData                 = sysclient.RoleListData
	TenantData                   = sysclient.TenantData
	UpdateDeptReq                = sysclient.UpdateDeptReq
	UpdateDeptResp               = sysclient.UpdateDeptResp
	UpdateDeptStatusReq          = sysclient.UpdateDeptStatusReq
	UpdateDeptStatusResp         = sysclient.UpdateDeptStatusResp
	UpdateDictItemReq            = sysclient.UpdateDictItemReq
	UpdateDictItemResp           = sysclient.UpdateDictItemResp
	UpdateDictItemStatusReq      = sysclient.UpdateDictItemStatusReq
	UpdateDictItemStatusResp     = sysclient.UpdateDictItemStatusResp
	UpdateDictTypeReq            = sysclient.UpdateDictTypeReq
	UpdateDictTypeResp           = sysclient.UpdateDictTypeResp
	UpdateDictTypeStatusReq      = sysclient.UpdateDictTypeStatusReq
	UpdateDictTypeStatusResp     = sysclient.UpdateDictTypeStatusResp
	UpdateMenuReq                = sysclient.UpdateMenuReq
	UpdateMenuResp               = sysclient.UpdateMenuResp
	UpdateMenuStatusReq          = sysclient.UpdateMenuStatusReq
	UpdateMenuStatusResp         = sysclient.UpdateMenuStatusResp
	UpdateMenuTemplateReq        = sysclient.UpdateMenuTemplateReq
	UpdateMenuTemplateResp       = sysclient.UpdateMenuTemplateResp
	UpdateNoticeReq              = sysclient.UpdateNoticeReq
	UpdateNoticeResp             = sysclient.UpdateNoticeResp
	UpdateNoticeStatusReq        = sysclient.UpdateNoticeStatusReq
	UpdateNoticeStatusResp       = sysclient.UpdateNoticeStatusResp
	UpdatePostReq                = sysclient.UpdatePostReq
	UpdatePostResp               = sysclient.UpdatePostResp
	UpdatePostStatusReq          = sysclient.UpdatePostStatusReq
	UpdatePostStatusResp         = sysclient.UpdatePostStatusResp
	UpdateRoleMenuReq            = sysclient.UpdateRoleMenuReq
	UpdateRoleMenuResp           = sysclient.UpdateRoleMenuResp
	UpdateRoleReq                = sysclient.UpdateRoleReq
	UpdateRoleResp               = sysclient.UpdateRoleResp
	UpdateRoleStatusReq          = sysclient.UpdateRoleStatusReq
	UpdateRoleStatusResp         = sysclient.UpdateRoleStatusResp
	UpdateUserReq                = sysclient.UpdateUserReq
	UpdateUserResp               = sysclient.UpdateUserResp
	UpdateUserRoleListReq        = sysclient.UpdateUserRoleListReq
	UpdateUserRoleListResp       = sysclient.UpdateUserRoleListResp
	UpdateUserStatusReq          = sysclient.UpdateUserStatusReq
	UpdateUserStatusResp         = sysclient.UpdateUserStatusResp
	UserData                     = sysclient.UserData
	UserListData                 = sysclient.UserListData

	TenantService interface {
		CreateTenant(ctx context.Context, in *CreateTenantReq, opts ...grpc.CallOption) (*CreateTenantResp, error)
		QueryTenantDetail(ctx context.Context, in *QueryTenantDetailReq, opts ...grpc.CallOption) (*QueryTenantDetailResp, error)
		QueryTenantList(ctx context.Context, in *QueryTenantListReq, opts ...grpc.CallOption) (*QueryTenantListResp, error)
		EnableTenant(ctx context.Context, in *ChangeTenantStatusReq, opts ...grpc.CallOption) (*ChangeTenantStatusResp, error)
		DisableTenant(ctx context.Context, in *ChangeTenantStatusReq, opts ...grpc.CallOption) (*ChangeTenantStatusResp, error)
		ArchiveTenant(ctx context.Context, in *ChangeTenantStatusReq, opts ...grpc.CallOption) (*ChangeTenantStatusResp, error)
	}

	defaultTenantService struct {
		cli zrpc.Client
	}
)

func NewTenantService(cli zrpc.Client) TenantService {
	return &defaultTenantService{
		cli: cli,
	}
}

func (m *defaultTenantService) CreateTenant(ctx context.Context, in *CreateTenantReq, opts ...grpc.CallOption) (*CreateTenantResp, error) {
	client := sysclient.NewTenantServiceClient(m.cli.Conn())
	return client.CreateTenant(ctx, in, opts...)
}

func (m *defaultTenantService) QueryTenantDetail(ctx context.Context, in *QueryTenantDetailReq, opts ...grpc.CallOption) (*QueryTenantDetailResp, error) {
	client := sysclient.NewTenantServiceClient(m.cli.Conn())
	return client.QueryTenantDetail(ctx, in, opts...)
}

func (m *defaultTenantService) QueryTenantList(ctx context.Context, in *QueryTenantListReq, opts ...grpc.CallOption) (*QueryTenantListResp, error) {
	client := sysclient.NewTenantServiceClient(m.cli.Conn())
	return client.QueryTenantList(ctx, in, opts...)
}

func (m *defaultTenantService) EnableTenant(ctx context.Context, in *ChangeTenantStatusReq, opts ...grpc.CallOption) (*ChangeTenantStatusResp, error) {
	client := sysclient.NewTenantServiceClient(m.cli.Conn())
	return client.EnableTenant(ctx, in, opts...)
}

func (m *defaultTenantService) DisableTenant(ctx context.Context, in *ChangeTenantStatusReq, opts ...grpc.CallOption) (*ChangeTenantStatusResp, error) {
	client := sysclient.NewTenantServiceClient(m.cli.Conn())
	return client.DisableTenant(ctx, in, opts...)
}

func (m *defaultTenantService) ArchiveTenant(ctx context.Context, in *ChangeTenantStatusReq, opts ...grpc.CallOption) (*ChangeTenantStatusResp, error) {
	client := sysclient.NewTenantServiceClient(m.cli.Conn())
	return client.ArchiveTenant(ctx, in, opts...)
}
