// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: rpc/search/search.proto

package search

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GovernanceScope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScopeType     string                 `protobuf:"bytes,1,opt,name=scope_type,json=scopeType,proto3" json:"scope_type,omitempty"`     // 主体范围(platform/tenant/merchant)
	PlatformId    int64                  `protobuf:"varint,2,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"` // 平台ID
	TenantId      int64                  `protobuf:"varint,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`       // 租户ID
	MerchantId    int64                  `protobuf:"varint,4,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"` // 商户ID
	ScopeLabel    string                 `protobuf:"bytes,5,opt,name=scope_label,json=scopeLabel,proto3" json:"scope_label,omitempty"`  // 主体范围标签
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GovernanceScope) Reset() {
	*x = GovernanceScope{}
	mi := &file_rpc_search_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GovernanceScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GovernanceScope) ProtoMessage() {}

func (x *GovernanceScope) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_search_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GovernanceScope.ProtoReflect.Descriptor instead.
func (*GovernanceScope) Descriptor() ([]byte, []int) {
	return file_rpc_search_search_proto_rawDescGZIP(), []int{0}
}

func (x *GovernanceScope) GetScopeType() string {
	if x != nil {
		return x.ScopeType
	}
	return ""
}

func (x *GovernanceScope) GetPlatformId() int64 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

func (x *GovernanceScope) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *GovernanceScope) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *GovernanceScope) GetScopeLabel() string {
	if x != nil {
		return x.ScopeLabel
	}
	return ""
}

type CreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*ProductData         `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReq) Reset() {
	*x = CreateReq{}
	mi := &file_rpc_search_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReq) ProtoMessage() {}

func (x *CreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_search_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReq.ProtoReflect.Descriptor instead.
func (*CreateReq) Descriptor() ([]byte, []int) {
	return file_rpc_search_search_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReq) GetData() []*ProductData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ProductData struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                                 //商品SpuId
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                              //商品名称
	CategoryId          int64                  `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`                               //商品分类ID
	CategoryIds         string                 `protobuf:"bytes,4,opt,name=category_ids,json=categoryIds,proto3" json:"category_ids,omitempty"`                             //商品分类ID集合
	CategoryName        string                 `protobuf:"bytes,5,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`                          //商品分类名称
	BrandId             int64                  `protobuf:"varint,6,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`                                        //品牌ID
	BrandName           string                 `protobuf:"bytes,7,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`                                   //品牌名称
	Unit                string                 `protobuf:"bytes,8,opt,name=unit,proto3" json:"unit,omitempty"`                                                              //单位
	Weight              float32                `protobuf:"fixed32,9,opt,name=weight,proto3" json:"weight,omitempty"`                                                        //重量(kg)
	Keywords            string                 `protobuf:"bytes,10,opt,name=keywords,proto3" json:"keywords,omitempty"`                                                     //关键词
	Brief               string                 `protobuf:"bytes,11,opt,name=brief,proto3" json:"brief,omitempty"`                                                           //简介
	Description         string                 `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`                                               //详细描述
	AlbumPics           string                 `protobuf:"bytes,13,opt,name=album_pics,json=albumPics,proto3" json:"album_pics,omitempty"`                                  //画册图片，最多8张，以逗号分割
	MainPic             string                 `protobuf:"bytes,14,opt,name=main_pic,json=mainPic,proto3" json:"main_pic,omitempty"`                                        //主图
	PriceRange          string                 `protobuf:"bytes,15,opt,name=price_range,json=priceRange,proto3" json:"price_range,omitempty"`                               //价格区间
	PublishStatus       int32                  `protobuf:"varint,16,opt,name=publish_status,json=publishStatus,proto3" json:"publish_status,omitempty"`                     //上架状态：0-下架，1-上架
	NewStatus           int32                  `protobuf:"varint,17,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"`                                 //新品状态:0->不是新品；1->新品
	RecommendStatus     int32                  `protobuf:"varint,18,opt,name=recommend_status,json=recommendStatus,proto3" json:"recommend_status,omitempty"`               //推荐状态；0->不推荐；1->推荐
	VerifyStatus        int32                  `protobuf:"varint,19,opt,name=verify_status,json=verifyStatus,proto3" json:"verify_status,omitempty"`                        //审核状态：0->未审核；1->审核通过
	PreviewStatus       int32                  `protobuf:"varint,20,opt,name=preview_status,json=previewStatus,proto3" json:"preview_status,omitempty"`                     //是否为预告商品：0->不是；1->是
	Sort                int32                  `protobuf:"varint,21,opt,name=sort,proto3" json:"sort,omitempty"`                                                            //排序
	NewStatusSort       int32                  `protobuf:"varint,22,opt,name=new_status_sort,json=newStatusSort,proto3" json:"new_status_sort,omitempty"`                   //新品排序
	RecommendStatusSort int32                  `protobuf:"varint,23,opt,name=recommend_status_sort,json=recommendStatusSort,proto3" json:"recommend_status_sort,omitempty"` //推荐排序
	Sales               int32                  `protobuf:"varint,24,opt,name=sales,proto3" json:"sales,omitempty"`                                                          //销量
	Stock               int32                  `protobuf:"varint,25,opt,name=stock,proto3" json:"stock,omitempty"`                                                          //库存
	LowStock            int32                  `protobuf:"varint,26,opt,name=low_stock,json=lowStock,proto3" json:"low_stock,omitempty"`                                    //预警库存
	PromotionType       int32                  `protobuf:"varint,27,opt,name=promotion_type,json=promotionType,proto3" json:"promotion_type,omitempty"`                     //促销类型：0->没有促销使用原价;1->使用促销价；2->使用会员价；3->使用阶梯价格；4->使用满减价格；5->秒杀
	DetailTitle         string                 `protobuf:"bytes,28,opt,name=detail_title,json=detailTitle,proto3" json:"detail_title,omitempty"`                            //详情标题
	DetailDesc          string                 `protobuf:"bytes,29,opt,name=detail_desc,json=detailDesc,proto3" json:"detail_desc,omitempty"`                               //详情描述
	DetailHtml          string                 `protobuf:"bytes,30,opt,name=detail_html,json=detailHtml,proto3" json:"detail_html,omitempty"`                               //产品详情网页内容
	DetailMobileHtml    string                 `protobuf:"bytes,31,opt,name=detail_mobile_html,json=detailMobileHtml,proto3" json:"detail_mobile_html,omitempty"`           //移动端网页详情
	CreateBy            int64                  `protobuf:"varint,32,opt,name=create_by,json=createBy,proto3" json:"create_by,omitempty"`                                    //创建人ID
	CreateTime          string                 `protobuf:"bytes,33,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`                               //创建时间
	UpdateBy            int64                  `protobuf:"varint,34,opt,name=update_by,json=updateBy,proto3" json:"update_by,omitempty"`                                    //更新人ID
	UpdateTime          string                 `protobuf:"bytes,35,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`                               //更新时间
	Scope               *GovernanceScope       `protobuf:"bytes,36,opt,name=scope,proto3" json:"scope,omitempty"`                                                           //治理范围(platform/tenant/merchant)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProductData) Reset() {
	*x = ProductData{}
	mi := &file_rpc_search_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductData) ProtoMessage() {}

func (x *ProductData) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_search_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductData.ProtoReflect.Descriptor instead.
func (*ProductData) Descriptor() ([]byte, []int) {
	return file_rpc_search_search_proto_rawDescGZIP(), []int{2}
}

func (x *ProductData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductData) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ProductData) GetCategoryIds() string {
	if x != nil {
		return x.CategoryIds
	}
	return ""
}

func (x *ProductData) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *ProductData) GetBrandId() int64 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

func (x *ProductData) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *ProductData) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *ProductData) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ProductData) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

func (x *ProductData) GetBrief() string {
	if x != nil {
		return x.Brief
	}
	return ""
}

func (x *ProductData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductData) GetAlbumPics() string {
	if x != nil {
		return x.AlbumPics
	}
	return ""
}

func (x *ProductData) GetMainPic() string {
	if x != nil {
		return x.MainPic
	}
	return ""
}

func (x *ProductData) GetPriceRange() string {
	if x != nil {
		return x.PriceRange
	}
	return ""
}

func (x *ProductData) GetPublishStatus() int32 {
	if x != nil {
		return x.PublishStatus
	}
	return 0
}

func (x *ProductData) GetNewStatus() int32 {
	if x != nil {
		return x.NewStatus
	}
	return 0
}

func (x *ProductData) GetRecommendStatus() int32 {
	if x != nil {
		return x.RecommendStatus
	}
	return 0
}

func (x *ProductData) GetVerifyStatus() int32 {
	if x != nil {
		return x.VerifyStatus
	}
	return 0
}

func (x *ProductData) GetPreviewStatus() int32 {
	if x != nil {
		return x.PreviewStatus
	}
	return 0
}

func (x *ProductData) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *ProductData) GetNewStatusSort() int32 {
	if x != nil {
		return x.NewStatusSort
	}
	return 0
}

func (x *ProductData) GetRecommendStatusSort() int32 {
	if x != nil {
		return x.RecommendStatusSort
	}
	return 0
}

func (x *ProductData) GetSales() int32 {
	if x != nil {
		return x.Sales
	}
	return 0
}

func (x *ProductData) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ProductData) GetLowStock() int32 {
	if x != nil {
		return x.LowStock
	}
	return 0
}

func (x *ProductData) GetPromotionType() int32 {
	if x != nil {
		return x.PromotionType
	}
	return 0
}

func (x *ProductData) GetDetailTitle() string {
	if x != nil {
		return x.DetailTitle
	}
	return ""
}

func (x *ProductData) GetDetailDesc() string {
	if x != nil {
		return x.DetailDesc
	}
	return ""
}

func (x *ProductData) GetDetailHtml() string {
	if x != nil {
		return x.DetailHtml
	}
	return ""
}

func (x *ProductData) GetDetailMobileHtml() string {
	if x != nil {
		return x.DetailMobileHtml
	}
	return ""
}

func (x *ProductData) GetCreateBy() int64 {
	if x != nil {
		return x.CreateBy
	}
	return 0
}

func (x *ProductData) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *ProductData) GetUpdateBy() int64 {
	if x != nil {
		return x.UpdateBy
	}
	return 0
}

func (x *ProductData) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *ProductData) GetScope() *GovernanceScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

type CreateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pong          string                 `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResp) Reset() {
	*x = CreateResp{}
	mi := &file_rpc_search_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResp) ProtoMessage() {}

func (x *CreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_search_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResp.ProtoReflect.Descriptor instead.
func (*CreateResp) Descriptor() ([]byte, []int) {
	return file_rpc_search_search_proto_rawDescGZIP(), []int{3}
}

func (x *CreateResp) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

type DeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReq) Reset() {
	*x = DeleteReq{}
	mi := &file_rpc_search_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReq) ProtoMessage() {}

func (x *DeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_search_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReq.ProtoReflect.Descriptor instead.
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return file_rpc_search_search_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pong          string                 `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResp) Reset() {
	*x = DeleteResp{}
	mi := &file_rpc_search_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResp) ProtoMessage() {}

func (x *DeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_search_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResp.ProtoReflect.Descriptor instead.
func (*DeleteResp) Descriptor() ([]byte, []int) {
	return file_rpc_search_search_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResp) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

type SearchSimpleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`                    //关键字
	PageNum       int64                  `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`    //页码
	PageSize      int64                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` //每页数量
	Scope         *GovernanceScope       `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`                        //治理范围(platform/tenant/merchant)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSimpleReq) Reset() {
	*x = SearchSimpleReq{}
	mi := &file_rpc_search_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSimpleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSimpleReq) ProtoMessage() {}

func (x *SearchSimpleReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_search_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSimpleReq.ProtoReflect.Descriptor instead.
func (*SearchSimpleReq) Descriptor() ([]byte, []int) {
	return file_rpc_search_search_proto_rawDescGZIP(), []int{6}
}

func (x *SearchSimpleReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchSimpleReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *SearchSimpleReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchSimpleReq) GetScope() *GovernanceScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

type SearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`                          //关键字
	PageNum       int64                  `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`          //页码
	PageSize      int64                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`       //每页数量
	Sort          int32                  `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`                               //排序字段:0->按相关度；1->按新品；2->按销量；3->价格从低到高；4->价格从高到低
	CategoryId    int64                  `protobuf:"varint,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"` //商品分类ID
	BrandId       int64                  `protobuf:"varint,6,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`          //品牌ID
	Scope         *GovernanceScope       `protobuf:"bytes,7,opt,name=scope,proto3" json:"scope,omitempty"`                              //治理范围(platform/tenant/merchant)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchReq) Reset() {
	*x = SearchReq{}
	mi := &file_rpc_search_search_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchReq) ProtoMessage() {}

func (x *SearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_search_search_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchReq.ProtoReflect.Descriptor instead.
func (*SearchReq) Descriptor() ([]byte, []int) {
	return file_rpc_search_search_proto_rawDescGZIP(), []int{7}
}

func (x *SearchReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *SearchReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchReq) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *SearchReq) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *SearchReq) GetBrandId() int64 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

func (x *SearchReq) GetScope() *GovernanceScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

type SearchResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*ProductData         `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`    //商品列表
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` //总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResp) Reset() {
	*x = SearchResp{}
	mi := &file_rpc_search_search_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResp) ProtoMessage() {}

func (x *SearchResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_search_search_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResp.ProtoReflect.Descriptor instead.
func (*SearchResp) Descriptor() ([]byte, []int) {
	return file_rpc_search_search_proto_rawDescGZIP(), []int{8}
}

func (x *SearchResp) GetData() []*ProductData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SearchResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RecommendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`                          //关键字
	PageNum       int64                  `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`          //页码
	PageSize      int64                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`       //每页数量
	Sort          string                 `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`                                //排序
	CategoryId    int64                  `protobuf:"varint,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"` //商品分类ID
	BrandId       int64                  `protobuf:"varint,6,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`          //品牌ID
	Scope         *GovernanceScope       `protobuf:"bytes,7,opt,name=scope,proto3" json:"scope,omitempty"`                              //治理范围(platform/tenant/merchant)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendReq) Reset() {
	*x = RecommendReq{}
	mi := &file_rpc_search_search_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendReq) ProtoMessage() {}

func (x *RecommendReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_search_search_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendReq.ProtoReflect.Descriptor instead.
func (*RecommendReq) Descriptor() ([]byte, []int) {
	return file_rpc_search_search_proto_rawDescGZIP(), []int{9}
}

func (x *RecommendReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *RecommendReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *RecommendReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *RecommendReq) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *RecommendReq) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *RecommendReq) GetBrandId() int64 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

func (x *RecommendReq) GetScope() *GovernanceScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

type RecommendResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*ProductData         `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"` //商品列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendResp) Reset() {
	*x = RecommendResp{}
	mi := &file_rpc_search_search_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendResp) ProtoMessage() {}

func (x *RecommendResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_search_search_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendResp.ProtoReflect.Descriptor instead.
func (*RecommendResp) Descriptor() ([]byte, []int) {
	return file_rpc_search_search_proto_rawDescGZIP(), []int{10}
}

func (x *RecommendResp) GetData() []*ProductData {
	if x != nil {
		return x.Data
	}
	return nil
}

type SearchRelatedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"` //关键字
	Scope         *GovernanceScope       `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`     //治理范围(platform/tenant/merchant)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRelatedReq) Reset() {
	*x = SearchRelatedReq{}
	mi := &file_rpc_search_search_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRelatedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRelatedReq) ProtoMessage() {}

func (x *SearchRelatedReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_search_search_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRelatedReq.ProtoReflect.Descriptor instead.
func (*SearchRelatedReq) Descriptor() ([]byte, []int) {
	return file_rpc_search_search_proto_rawDescGZIP(), []int{11}
}

func (x *SearchRelatedReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchRelatedReq) GetScope() *GovernanceScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

type SearchRelatedResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrandNames    []string               `protobuf:"bytes,1,rep,name=brand_names,json=brandNames,proto3" json:"brand_names,omitempty"`          //品牌名称集合
	CategoryNames []string               `protobuf:"bytes,2,rep,name=category_names,json=categoryNames,proto3" json:"category_names,omitempty"` //分类名称集合
	ProductAttrs  []*ProductAttr         `protobuf:"bytes,3,rep,name=productAttrs,proto3" json:"productAttrs,omitempty"`                        //属性集合
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRelatedResp) Reset() {
	*x = SearchRelatedResp{}
	mi := &file_rpc_search_search_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRelatedResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRelatedResp) ProtoMessage() {}

func (x *SearchRelatedResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_search_search_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRelatedResp.ProtoReflect.Descriptor instead.
func (*SearchRelatedResp) Descriptor() ([]byte, []int) {
	return file_rpc_search_search_proto_rawDescGZIP(), []int{12}
}

func (x *SearchRelatedResp) GetBrandNames() []string {
	if x != nil {
		return x.BrandNames
	}
	return nil
}

func (x *SearchRelatedResp) GetCategoryNames() []string {
	if x != nil {
		return x.CategoryNames
	}
	return nil
}

func (x *SearchRelatedResp) GetProductAttrs() []*ProductAttr {
	if x != nil {
		return x.ProductAttrs
	}
	return nil
}

type ProductAttr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttrId        int64                  `protobuf:"varint,1,opt,name=attrId,proto3" json:"attrId,omitempty"`        //属性id
	AttrName      string                 `protobuf:"bytes,2,opt,name=attrName,proto3" json:"attrName,omitempty"`     //属性名称
	AttrValues    []string               `protobuf:"bytes,3,rep,name=attrValues,proto3" json:"attrValues,omitempty"` //属性值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductAttr) Reset() {
	*x = ProductAttr{}
	mi := &file_rpc_search_search_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAttr) ProtoMessage() {}

func (x *ProductAttr) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_search_search_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAttr.ProtoReflect.Descriptor instead.
func (*ProductAttr) Descriptor() ([]byte, []int) {
	return file_rpc_search_search_proto_rawDescGZIP(), []int{13}
}

func (x *ProductAttr) GetAttrId() int64 {
	if x != nil {
		return x.AttrId
	}
	return 0
}

func (x *ProductAttr) GetAttrName() string {
	if x != nil {
		return x.AttrName
	}
	return ""
}

func (x *ProductAttr) GetAttrValues() []string {
	if x != nil {
		return x.AttrValues
	}
	return nil
}

var File_rpc_search_search_proto protoreflect.FileDescriptor

const file_rpc_search_search_proto_rawDesc = "" +
	"\n" +
	"\x17rpc/search/search.proto\x12\x06search\"\xb0\x01\n" +
	"\x0fGovernanceScope\x12\x1d\n" +
	"\n" +
	"scope_type\x18\x01 \x01(\tR\tscopeType\x12\x1f\n" +
	"\vplatform_id\x18\x02 \x01(\x03R\n" +
	"platformId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\x03R\btenantId\x12\x1f\n" +
	"\vmerchant_id\x18\x04 \x01(\x03R\n" +
	"merchantId\x12\x1f\n" +
	"\vscope_label\x18\x05 \x01(\tR\n" +
	"scopeLabel\"4\n" +
	"\tCreateReq\x12'\n" +
	"\x04data\x18\x01 \x03(\v2\x13.search.ProductDataR\x04data\"\x8a\t\n" +
	"\vProductData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x03R\n" +
	"categoryId\x12!\n" +
	"\fcategory_ids\x18\x04 \x01(\tR\vcategoryIds\x12#\n" +
	"\rcategory_name\x18\x05 \x01(\tR\fcategoryName\x12\x19\n" +
	"\bbrand_id\x18\x06 \x01(\x03R\abrandId\x12\x1d\n" +
	"\n" +
	"brand_name\x18\a \x01(\tR\tbrandName\x12\x12\n" +
	"\x04unit\x18\b \x01(\tR\x04unit\x12\x16\n" +
	"\x06weight\x18\t \x01(\x02R\x06weight\x12\x1a\n" +
	"\bkeywords\x18\n" +
	" \x01(\tR\bkeywords\x12\x14\n" +
	"\x05brief\x18\v \x01(\tR\x05brief\x12 \n" +
	"\vdescription\x18\f \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"album_pics\x18\r \x01(\tR\talbumPics\x12\x19\n" +
	"\bmain_pic\x18\x0e \x01(\tR\amainPic\x12\x1f\n" +
	"\vprice_range\x18\x0f \x01(\tR\n" +
	"priceRange\x12%\n" +
	"\x0epublish_status\x18\x10 \x01(\x05R\rpublishStatus\x12\x1d\n" +
	"\n" +
	"new_status\x18\x11 \x01(\x05R\tnewStatus\x12)\n" +
	"\x10recommend_status\x18\x12 \x01(\x05R\x0frecommendStatus\x12#\n" +
	"\rverify_status\x18\x13 \x01(\x05R\fverifyStatus\x12%\n" +
	"\x0epreview_status\x18\x14 \x01(\x05R\rpreviewStatus\x12\x12\n" +
	"\x04sort\x18\x15 \x01(\x05R\x04sort\x12&\n" +
	"\x0fnew_status_sort\x18\x16 \x01(\x05R\rnewStatusSort\x122\n" +
	"\x15recommend_status_sort\x18\x17 \x01(\x05R\x13recommendStatusSort\x12\x14\n" +
	"\x05sales\x18\x18 \x01(\x05R\x05sales\x12\x14\n" +
	"\x05stock\x18\x19 \x01(\x05R\x05stock\x12\x1b\n" +
	"\tlow_stock\x18\x1a \x01(\x05R\blowStock\x12%\n" +
	"\x0epromotion_type\x18\x1b \x01(\x05R\rpromotionType\x12!\n" +
	"\fdetail_title\x18\x1c \x01(\tR\vdetailTitle\x12\x1f\n" +
	"\vdetail_desc\x18\x1d \x01(\tR\n" +
	"detailDesc\x12\x1f\n" +
	"\vdetail_html\x18\x1e \x01(\tR\n" +
	"detailHtml\x12,\n" +
	"\x12detail_mobile_html\x18\x1f \x01(\tR\x10detailMobileHtml\x12\x1b\n" +
	"\tcreate_by\x18  \x01(\x03R\bcreateBy\x12\x1f\n" +
	"\vcreate_time\x18! \x01(\tR\n" +
	"createTime\x12\x1b\n" +
	"\tupdate_by\x18\" \x01(\x03R\bupdateBy\x12\x1f\n" +
	"\vupdate_time\x18# \x01(\tR\n" +
	"updateTime\x12-\n" +
	"\x05scope\x18$ \x01(\v2\x17.search.GovernanceScopeR\x05scope\" \n" +
	"\n" +
	"CreateResp\x12\x12\n" +
	"\x04pong\x18\x01 \x01(\tR\x04pong\"\x1d\n" +
	"\tDeleteReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\" \n" +
	"\n" +
	"DeleteResp\x12\x12\n" +
	"\x04pong\x18\x01 \x01(\tR\x04pong\"\x92\x01\n" +
	"\x0fSearchSimpleReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x19\n" +
	"\bpage_num\x18\x02 \x01(\x03R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x03R\bpageSize\x12-\n" +
	"\x05scope\x18\x04 \x01(\v2\x17.search.GovernanceScopeR\x05scope\"\xdc\x01\n" +
	"\tSearchReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x19\n" +
	"\bpage_num\x18\x02 \x01(\x03R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x03R\bpageSize\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\x05R\x04sort\x12\x1f\n" +
	"\vcategory_id\x18\x05 \x01(\x03R\n" +
	"categoryId\x12\x19\n" +
	"\bbrand_id\x18\x06 \x01(\x03R\abrandId\x12-\n" +
	"\x05scope\x18\a \x01(\v2\x17.search.GovernanceScopeR\x05scope\"K\n" +
	"\n" +
	"SearchResp\x12'\n" +
	"\x04data\x18\x01 \x03(\v2\x13.search.ProductDataR\x04data\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xdf\x01\n" +
	"\fRecommendReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x19\n" +
	"\bpage_num\x18\x02 \x01(\x03R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x03R\bpageSize\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\tR\x04sort\x12\x1f\n" +
	"\vcategory_id\x18\x05 \x01(\x03R\n" +
	"categoryId\x12\x19\n" +
	"\bbrand_id\x18\x06 \x01(\x03R\abrandId\x12-\n" +
	"\x05scope\x18\a \x01(\v2\x17.search.GovernanceScopeR\x05scope\"8\n" +
	"\rRecommendResp\x12'\n" +
	"\x04data\x18\x01 \x03(\v2\x13.search.ProductDataR\x04data\"[\n" +
	"\x10SearchRelatedReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12-\n" +
	"\x05scope\x18\x02 \x01(\v2\x17.search.GovernanceScopeR\x05scope\"\x94\x01\n" +
	"\x11SearchRelatedResp\x12\x1f\n" +
	"\vbrand_names\x18\x01 \x03(\tR\n" +
	"brandNames\x12%\n" +
	"\x0ecategory_names\x18\x02 \x03(\tR\rcategoryNames\x127\n" +
	"\fproductAttrs\x18\x03 \x03(\v2\x13.search.ProductAttrR\fproductAttrs\"a\n" +
	"\vProductAttr\x12\x16\n" +
	"\x06attrId\x18\x01 \x01(\x03R\x06attrId\x12\x1a\n" +
	"\battrName\x18\x02 \x01(\tR\battrName\x12\x1e\n" +
	"\n" +
	"attrValues\x18\x03 \x03(\tR\n" +
	"attrValues2\xd5\x02\n" +
	"\x06Search\x12/\n" +
	"\x06create\x12\x11.search.CreateReq\x1a\x12.search.CreateResp\x12/\n" +
	"\x06delete\x12\x11.search.DeleteReq\x1a\x12.search.DeleteResp\x12;\n" +
	"\fsearchSimple\x12\x17.search.SearchSimpleReq\x1a\x12.search.SearchResp\x12/\n" +
	"\x06search\x12\x11.search.SearchReq\x1a\x12.search.SearchResp\x125\n" +
	"\trecommend\x12\x14.search.RecommendReq\x1a\x12.search.SearchResp\x12D\n" +
	"\rsearchRelated\x12\x18.search.SearchRelatedReq\x1a\x19.search.SearchRelatedRespB\n" +
	"Z\b./searchb\x06proto3"

var (
	file_rpc_search_search_proto_rawDescOnce sync.Once
	file_rpc_search_search_proto_rawDescData []byte
)

func file_rpc_search_search_proto_rawDescGZIP() []byte {
	file_rpc_search_search_proto_rawDescOnce.Do(func() {
		file_rpc_search_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_search_search_proto_rawDesc), len(file_rpc_search_search_proto_rawDesc)))
	})
	return file_rpc_search_search_proto_rawDescData
}

var file_rpc_search_search_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_rpc_search_search_proto_goTypes = []any{
	(*GovernanceScope)(nil),   // 0: search.GovernanceScope
	(*CreateReq)(nil),         // 1: search.CreateReq
	(*ProductData)(nil),       // 2: search.ProductData
	(*CreateResp)(nil),        // 3: search.CreateResp
	(*DeleteReq)(nil),         // 4: search.DeleteReq
	(*DeleteResp)(nil),        // 5: search.DeleteResp
	(*SearchSimpleReq)(nil),   // 6: search.SearchSimpleReq
	(*SearchReq)(nil),         // 7: search.SearchReq
	(*SearchResp)(nil),        // 8: search.SearchResp
	(*RecommendReq)(nil),      // 9: search.RecommendReq
	(*RecommendResp)(nil),     // 10: search.RecommendResp
	(*SearchRelatedReq)(nil),  // 11: search.SearchRelatedReq
	(*SearchRelatedResp)(nil), // 12: search.SearchRelatedResp
	(*ProductAttr)(nil),       // 13: search.ProductAttr
}
var file_rpc_search_search_proto_depIdxs = []int32{
	2,  // 0: search.CreateReq.data:type_name -> search.ProductData
	0,  // 1: search.ProductData.scope:type_name -> search.GovernanceScope
	0,  // 2: search.SearchSimpleReq.scope:type_name -> search.GovernanceScope
	0,  // 3: search.SearchReq.scope:type_name -> search.GovernanceScope
	2,  // 4: search.SearchResp.data:type_name -> search.ProductData
	0,  // 5: search.RecommendReq.scope:type_name -> search.GovernanceScope
	2,  // 6: search.RecommendResp.data:type_name -> search.ProductData
	0,  // 7: search.SearchRelatedReq.scope:type_name -> search.GovernanceScope
	13, // 8: search.SearchRelatedResp.productAttrs:type_name -> search.ProductAttr
	1,  // 9: search.Search.create:input_type -> search.CreateReq
	4,  // 10: search.Search.delete:input_type -> search.DeleteReq
	6,  // 11: search.Search.searchSimple:input_type -> search.SearchSimpleReq
	7,  // 12: search.Search.search:input_type -> search.SearchReq
	9,  // 13: search.Search.recommend:input_type -> search.RecommendReq
	11, // 14: search.Search.searchRelated:input_type -> search.SearchRelatedReq
	3,  // 15: search.Search.create:output_type -> search.CreateResp
	5,  // 16: search.Search.delete:output_type -> search.DeleteResp
	8,  // 17: search.Search.searchSimple:output_type -> search.SearchResp
	8,  // 18: search.Search.search:output_type -> search.SearchResp
	8,  // 19: search.Search.recommend:output_type -> search.SearchResp
	12, // 20: search.Search.searchRelated:output_type -> search.SearchRelatedResp
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_rpc_search_search_proto_init() }
func file_rpc_search_search_proto_init() {
	if File_rpc_search_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_search_search_proto_rawDesc), len(file_rpc_search_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_search_search_proto_goTypes,
		DependencyIndexes: file_rpc_search_search_proto_depIdxs,
		MessageInfos:      file_rpc_search_search_proto_msgTypes,
	}.Build()
	File_rpc_search_search_proto = out.File
	file_rpc_search_search_proto_goTypes = nil
	file_rpc_search_search_proto_depIdxs = nil
}
