// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: sms.proto

package server

import (
	"context"

	"github.com/feihua/zero-admin/rpc/sms/internal/logic/drawactivityservice"
	"github.com/feihua/zero-admin/rpc/sms/internal/svc"
	"github.com/feihua/zero-admin/rpc/sms/smsclient"
)

type DrawActivityServiceServer struct {
	svcCtx *svc.ServiceContext
	smsclient.UnimplementedDrawActivityServiceServer
}

func NewDrawActivityServiceServer(svcCtx *svc.ServiceContext) *DrawActivityServiceServer {
	return &DrawActivityServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *DrawActivityServiceServer) AddDrawActivity(ctx context.Context, in *smsclient.AddDrawActivityReq) (*smsclient.AddDrawActivityResp, error) {
	l := drawactivityservicelogic.NewAddDrawActivityLogic(ctx, s.svcCtx)
	return l.AddDrawActivity(in)
}

func (s *DrawActivityServiceServer) UpdateDrawActivity(ctx context.Context, in *smsclient.UpdateDrawActivityReq) (*smsclient.UpdateDrawActivityResp, error) {
	l := drawactivityservicelogic.NewUpdateDrawActivityLogic(ctx, s.svcCtx)
	return l.UpdateDrawActivity(in)
}

func (s *DrawActivityServiceServer) DeleteDrawActivity(ctx context.Context, in *smsclient.DeleteDrawActivityReq) (*smsclient.DeleteDrawActivityResp, error) {
	l := drawactivityservicelogic.NewDeleteDrawActivityLogic(ctx, s.svcCtx)
	return l.DeleteDrawActivity(in)
}

func (s *DrawActivityServiceServer) UpdateDrawActivityStatus(ctx context.Context, in *smsclient.UpdateDrawActivityStatusReq) (*smsclient.UpdateDrawActivityStatusResp, error) {
	l := drawactivityservicelogic.NewUpdateDrawActivityStatusLogic(ctx, s.svcCtx)
	return l.UpdateDrawActivityStatus(in)
}

func (s *DrawActivityServiceServer) QueryDrawActivityDetail(ctx context.Context, in *smsclient.QueryDrawActivityDetailReq) (*smsclient.QueryDrawActivityDetailResp, error) {
	l := drawactivityservicelogic.NewQueryDrawActivityDetailLogic(ctx, s.svcCtx)
	return l.QueryDrawActivityDetail(in)
}

func (s *DrawActivityServiceServer) QueryDrawActivityList(ctx context.Context, in *smsclient.QueryDrawActivityListReq) (*smsclient.QueryDrawActivityListResp, error) {
	l := drawactivityservicelogic.NewQueryDrawActivityListLogic(ctx, s.svcCtx)
	return l.QueryDrawActivityList(in)
}

func (s *DrawActivityServiceServer) PreviewDrawActivityPublishReadiness(ctx context.Context, in *smsclient.PreviewDrawActivityPublishReadinessReq) (*smsclient.PreviewDrawActivityPublishReadinessResp, error) {
	l := drawactivityservicelogic.NewPreviewDrawActivityPublishReadinessLogic(ctx, s.svcCtx)
	return l.PreviewDrawActivityPublishReadiness(in)
}
