// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: sms.proto

package server

import (
	"context"

	"github.com/feihua/zero-admin/rpc/sms/internal/logic/cardassetservice"
	"github.com/feihua/zero-admin/rpc/sms/internal/svc"
	"github.com/feihua/zero-admin/rpc/sms/smsclient"
)

type CardAssetServiceServer struct {
	svcCtx *svc.ServiceContext
	smsclient.UnimplementedCardAssetServiceServer
}

func NewCardAssetServiceServer(svcCtx *svc.ServiceContext) *CardAssetServiceServer {
	return &CardAssetServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *CardAssetServiceServer) EnsureCardInstanceByParticipationRecord(ctx context.Context, in *smsclient.EnsureCardInstanceByParticipationRecordReq) (*smsclient.EnsureCardInstanceByParticipationRecordResp, error) {
	l := cardassetservicelogic.NewEnsureCardInstanceByParticipationRecordLogic(ctx, s.svcCtx)
	return l.EnsureCardInstanceByParticipationRecord(in)
}

func (s *CardAssetServiceServer) QueryCardInstanceByParticipationRecord(ctx context.Context, in *smsclient.QueryCardInstanceByParticipationRecordReq) (*smsclient.QueryCardInstanceByParticipationRecordResp, error) {
	l := cardassetservicelogic.NewQueryCardInstanceByParticipationRecordLogic(ctx, s.svcCtx)
	return l.QueryCardInstanceByParticipationRecord(in)
}

func (s *CardAssetServiceServer) BackfillWinningCardInstances(ctx context.Context, in *smsclient.BackfillWinningCardInstancesReq) (*smsclient.BackfillWinningCardInstancesResp, error) {
	l := cardassetservicelogic.NewBackfillWinningCardInstancesLogic(ctx, s.svcCtx)
	return l.BackfillWinningCardInstances(in)
}
